### ISSUE TITLE
Error in yml file for conda environment

### ISSUE THREAD

**Issue by micha-silver** [EnMAP-Box/enmap-box#1010]
The yml file:
https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/.env/conda/enmapbox_full_longterm.yml

referred to in the conda installation instructions has, I believe, a spelling error.
The `h5py` package appears (misspelled) as `hy5py`

**Comment by jakimowb** [comment]
@janzandr conda packages need to be defined in ``scripts/update_conda_environments.py``, which generates / updates all conda environments in `.env/conda`
""""yaml
# EnMAP-Box conda environment
# generated with scripts/update_conda_environemts.py (MANUAL CHANGES WILL BE OVERWRITTEN!)
""""
