### ISSUE TITLE
[Import XYZ product] performance issue with scaled reflectance raster

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#1028]
_Discussed with @jakimowb and @danschef ._

Imported sensor products store proper data gain/offset values for scaling the reflectance data into the 0 to 1 range. When visualizing such raster in QGIS/EnMAP-Box, very large default histograms are stored in the raster with 10 mio bins. This is slowing down raster handling/visualization.
![image](https://github.com/user-attachments/assets/d9c6bbb3-c16d-41f8-98b3-49229509fc6d)

This is most likely a GDAL related bug, which should be reported. As a wordaround, we can just precalculate the histograms with reasonable bin counts and store into the raster. 

```python
for band_index in range(1, dataset.RasterCount + 1):
    band = dataset.GetRasterBand(band_index)
    min_val, max_val = band.ComputeRasterMinMax()
    histogram = band.GetHistogram(min=min_val, max=max_val, buckets=1000, approx_ok=False)
    band.SetDefaultHistogram(min_val, max_val, histogram,)

```
- [x] procalculate histograms
- [x] report issue to QGIS project

**Comment by jakimowb** [comment]
Is this caused by gdal or QGIS?

**Comment by janzandr** [comment]
Visualizing the raster in QGIS will trigger the creation of the histograms.

**Comment by janzandr** [comment]
I will report it in the QGIS issue tracker. @rouault will hopefully take care of it ;-)

**Comment by rouault** [comment]
> @rouault will hopefully take care of it ;-)

I'm like everybody: I only work 25 hours / day... More seriously: the whole point of open source is that you can try fixing bug that annoy you, without being depend on the availability/willingness of someone else to do it for you.

**Comment by janzandr** [comment]
Hi @rouault, we will fix this on our side (Python plugin) and hopefully, someone on the C++ side will also take care of it. We here, very value your past effords regarding improving raster integration in QGIS. Have a nice day, looking forward seeing you at one of the next QGIS conferences. All the best, Andreas.

**Comment by janzandr** [comment]
@jakimowb, the workaround is working only kind of. For the default rendering **Accuracy: Estimate (faster)** it works fine, but when the user switches to  **Accuracy: Actual (slower)**, the big histograms are calculated again, and are stored next to my precalculated histograms:
![image](https://github.com/user-attachments/assets/4d67f275-2941-4bbf-9b5d-b4e9c9894f30)

Not sure how to workaround this on the Python side.

Shall we remove the scaling factor?

**Comment by janzandr** [comment]
@rouault maybe you have a hint for us?
