### ISSUE TITLE
Lossing wavelength info in GTIF file

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#1051]
How is enmapbox geting the wavelength information from a geotif file?
I have imported a Landsat L2 product to 
LC08_L2SP_20230718_enmapbox.tif 
and get correct spectra with wavelength in the x axis. But then I do some processing in R and while I have managed to write the same kind of geotif with the same DESCRIPTION field, 
L8W_mv2.tif
I do not get the spectra along wavelength in this case.
I have saved the output of gdal info to
https://www.dropbox.com/scl/fi/8ii0x9ljtce8951na2mx4/LC08_L2SP_20230718_enmapbox_gdalinfo.txt?rlkey=anpm7o26iujxjc1hu5zylpisp&dl=0
and
https://www.dropbox.com/scl/fi/07veqentfqc2jk13pp0ii/L8W_mv2_gdalinfo.txt?rlkey=fv6795a8o8u6tne179dyvj0qk&dl=0

and I copy the output of diff between both gdalinfo outputs here (left, enmapbox original geotif; right, my R output geotif):

```



(base) alobo@pop-os:/media/alobo/SP PHD U3/Islandia/Landsat/LC08_L2SP_220015_20230718_20230802_02_T1$ diff -y LC08_L2SP_20230718_enmapbox_gdalinfo.txt L8W_mv2_gdalinfo.txt
Driver: GTiff/GeoTIFF						Driver: GTiff/GeoTIFF
Files: LC08_L2SP_20230718_enmapbox.tif			      |	Files: L8W_mv2.tif
Size is 8331, 8391						Size is 8331, 8391
Coordinate System is:						Coordinate System is:
PROJCRS["WGS 84 / UTM zone 27N",				PROJCRS["WGS 84 / UTM zone 27N",
    BASEGEOGCRS["WGS 84",					    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",			        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,		            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],			                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,					        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],		            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],					        ID["EPSG",4326]],
    CONVERSION["UTM zone 27N",					    CONVERSION["UTM zone 27N",
        METHOD["Transverse Mercator",				        METHOD["Transverse Mercator",
            ID["EPSG",9807]],					            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,		        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],		            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],					            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-21,		        PARAMETER["Longitude of natural origin",-21,
            ANGLEUNIT["degree",0.0174532925199433],		            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],					            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,	        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],				            SCALEUNIT["unity",1],
            ID["EPSG",8805]],					            ID["EPSG",8805]],
        PARAMETER["False easting",500000,			        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],				            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],					            ID["EPSG",8806]],
        PARAMETER["False northing",0,				        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],				            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],					            ID["EPSG",8807]]],
    CS[Cartesian,2],						    CS[Cartesian,2],
        AXIS["(E)",east,					        AXIS["(E)",east,
            ORDER[1],						            ORDER[1],
            LENGTHUNIT["metre",1]],				            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,					        AXIS["(N)",north,
            ORDER[2],						            ORDER[2],
            LENGTHUNIT["metre",1]],				            LENGTHUNIT["metre",1]],
    USAGE[							    USAGE[
        SCOPE["Navigation and medium accuracy spatial referen	        SCOPE["Navigation and medium accuracy spatial referen
        AREA["Between 24°W and 18°W, northern hemisphere betw	        AREA["Between 24°W and 18°W, northern hemisphere betw
        BBOX[0,-24,84,-18]],					        BBOX[0,-24,84,-18]],
    ID["EPSG",32627]]						    ID["EPSG",32627]]
Data axis to CRS axis mapping: 1,2				Data axis to CRS axis mapping: 1,2
Origin = (368085.000000000000000,7247415.000000000000000)	Origin = (368085.000000000000000,7247415.000000000000000)
Pixel Size = (30.000000000000000,-30.000000000000000)		Pixel Size = (30.000000000000000,-30.000000000000000)
Metadata:							Metadata:
  AREA_OR_POINT=Area						  AREA_OR_POINT=Area
Image Structure Metadata:					Image Structure Metadata:
  COMPRESSION=LZW						  COMPRESSION=LZW
  INTERLEAVE=BAND					      |	  INTERLEAVE=PIXEL
Corner Coordinates:						Corner Coordinates:
Upper Left  (  368085.000, 7247415.000) ( 23d49'56.51"W, 65d1	Upper Left  (  368085.000, 7247415.000) ( 23d49'56.51"W, 65d1
Lower Left  (  368085.000, 6995685.000) ( 23d36'38.84"W, 63d 	Lower Left  (  368085.000, 6995685.000) ( 23d36'38.84"W, 63d 
Upper Right (  618015.000, 7247415.000) ( 18d27'56.55"W, 65d1	Upper Right (  618015.000, 7247415.000) ( 18d27'56.55"W, 65d1
Lower Right (  618015.000, 6995685.000) ( 18d39'50.48"W, 63d 	Lower Right (  618015.000, 6995685.000) ( 18d39'50.48"W, 63d 
Center      (  493050.000, 7121550.000) ( 21d 8'35.59"W, 64d1	Center      (  493050.000, 7121550.000) ( 21d 8'35.59"W, 64d1
Band 1 Block=256x256 Type=Float32, ColorInterp=Gray	      |	Band 1 Block=8331x1 Type=Float32, ColorInterp=Gray
  Description = Coastal aerosol (443 Nanometers)		  Description = Coastal aerosol (443 Nanometers)
  Min=0.000 Max=1.014 					      |	  Min=0.000 Max=0.596 
  Minimum=0.000, Maximum=1.014, Mean=0.233, StdDev=0.045      |	  Minimum=0.000, Maximum=0.596, Mean=-9999.000, StdDev=-9999.
  NoData Value=0					      |	  NoData Value=nan
  Metadata:						      |	  Metadata:
    bbl=1						      |	    STATISTICS_MAXIMUM=0.59601497650146
    STATISTICS_APPROXIMATE=YES				      |	    STATISTICS_MEAN=-9999
    STATISTICS_MAXIMUM=1.0139194726944			      |	    STATISTICS_MINIMUM=7.4999998105341e-06
    STATISTICS_MEAN=0.23273195438495			      |	    STATISTICS_STDDEV=-9999
    STATISTICS_MINIMUM=0.00035200000274926		      |	Band 2 Block=8331x1 Type=Float32, ColorInterp=Undefined
    STATISTICS_STDDEV=0.044643262561122			      <
    STATISTICS_VALID_PERCENT=58.3			      <
Band 2 Block=256x256 Type=Float32, ColorInterp=Undefined      <
  Description = Blue ( 482 Nanometers)				  Description = Blue ( 482 Nanometers)
  Min=0.001 Max=1.059 					      |	  Min=0.000 Max=0.640 
  Minimum=0.001, Maximum=1.059, Mean=0.240, StdDev=0.048      |	  Minimum=0.000, Maximum=0.640, Mean=-9999.000, StdDev=-9999.
  NoData Value=0					      |	  NoData Value=nan
  Metadata:						      |	  Metadata:
    bbl=1						      |	    STATISTICS_MAXIMUM=0.64042747020721
    STATISTICS_APPROXIMATE=YES				      |	    STATISTICS_MEAN=-9999
    STATISTICS_MAXIMUM=1.0594869852066			      |	    STATISTICS_MINIMUM=0.00019999999494758
    STATISTICS_MEAN=0.2401980196162			      |	    STATISTICS_STDDEV=-9999
    STATISTICS_MINIMUM=0.0012319999514148		      |	Band 3 Block=8331x1 Type=Float32, ColorInterp=Undefined
    STATISTICS_STDDEV=0.04844631826941			      <
    STATISTICS_VALID_PERCENT=58.3			      <
Band 3 Block=256x256 Type=Float32, ColorInterp=Undefined      <
  Description = Green ( 562 Nanometers)				  Description = Green ( 562 Nanometers)
  Min=0.045 Max=1.059 					      |	  Min=0.003 Max=0.705 
  Minimum=0.045, Maximum=1.059, Mean=0.265, StdDev=0.053      |	  Minimum=0.003, Maximum=0.705, Mean=-9999.000, StdDev=-9999.
  NoData Value=0					      |	  NoData Value=nan
  Metadata:						      |	  Metadata:
    bbl=1						      |	    STATISTICS_MAXIMUM=0.70453000068665
    STATISTICS_APPROXIMATE=YES				      |	    STATISTICS_MEAN=-9999
    STATISTICS_MAXIMUM=1.0585244894028			      |	    STATISTICS_MINIMUM=0.0032250001095235
    STATISTICS_MEAN=0.26483634498341			      |	    STATISTICS_STDDEV=-9999
    STATISTICS_MINIMUM=0.044654499739408		      |	Band 4 Block=8331x1 Type=Float32, ColorInterp=Undefined
    STATISTICS_STDDEV=0.052898834620425			      <
    STATISTICS_VALID_PERCENT=58.31			      <
Band 4 Block=256x256 Type=Float32, ColorInterp=Undefined      <
  Description = Red ( 655 Nanometers)				  Description = Red ( 655 Nanometers)
  NoData Value=0					      |	  Min=0.001 Max=0.764 
  Metadata:						      |	  Minimum=0.001, Maximum=0.764, Mean=-9999.000, StdDev=-9999.
    bbl=1						      |	  NoData Value=nan
Band 5 Block=256x256 Type=Float32, ColorInterp=Undefined      |	  Metadata:
							      >	    STATISTICS_MAXIMUM=0.76423251628876
							      >	    STATISTICS_MEAN=-9999
							      >	    STATISTICS_MINIMUM=0.00077749998308718
							      >	    STATISTICS_STDDEV=-9999
							      >	Band 5 Block=8331x1 Type=Float32, ColorInterp=Undefined
  Description = NIR ( 865 Nanometers)				  Description = NIR ( 865 Nanometers)
  NoData Value=0					      |	  Min=0.000 Max=0.792 
  Metadata:						      |	  Minimum=0.000, Maximum=0.792, Mean=-9999.000, StdDev=-9999.
    bbl=1						      |	  NoData Value=nan
Band 6 Block=256x256 Type=Float32, ColorInterp=Undefined      |	  Metadata:
							      >	    STATISTICS_MAXIMUM=0.79211747646332
							      >	    STATISTICS_MEAN=-9999
							      >	    STATISTICS_MINIMUM=0.00017250000382774
							      >	    STATISTICS_STDDEV=-9999
							      >	Band 6 Block=8331x1 Type=Float32, ColorInterp=Undefined
  Description = SWIR-1 ( 1610 Nanometers)			  Description = SWIR-1 ( 1610 Nanometers)
  NoData Value=0					      |	  Min=0.034 Max=0.957 
  Metadata:						      |	  Minimum=0.034, Maximum=0.957, Mean=-9999.000, StdDev=-9999.
    bbl=1						      |	  NoData Value=nan
Band 7 Block=256x256 Type=Float32, ColorInterp=Undefined      |	  Metadata:
							      >	    STATISTICS_MAXIMUM=0.95684248209
							      >	    STATISTICS_MEAN=-9999
							      >	    STATISTICS_MINIMUM=0.033585000783205
							      >	    STATISTICS_STDDEV=-9999
							      >	Band 7 Block=8331x1 Type=Float32, ColorInterp=Undefined
  Description = SWIR-2 ( 2200 Nanometers)			  Description = SWIR-2 ( 2200 Nanometers)
  NoData Value=0					      |	  Min=0.018 Max=0.999 
  Metadata:						      |	  Minimum=0.018, Maximum=0.999, Mean=-9999.000, StdDev=-9999.
    bbl=1						      |	  NoData Value=nan
							      >	  Metadata:
							      >	    STATISTICS_MAXIMUM=0.99949502944946
							      >	    STATISTICS_MEAN=-9999
							      >	    STATISTICS_MINIMUM=0.017635000869632
							      >	    STATISTICS_STDDEV=-9999

```
enmapbox original GTIF
![image](https://github.com/user-attachments/assets/29a8c9ff-2ea6-4f08-8000-b88d1eaa7f9d)

My GTIF file:
![image](https://github.com/user-attachments/assets/6e5b0e0c-fce4-4cdb-a92c-6311406b6ca9)

Also, why is enmapbox saving a *.tif.vrt (LC08_L2SP_20230718_enmapbox.tif.vrt in this case) file?

**Comment by janzandr** [comment]
> How is enmapbox geting the wavelength information from a geotif file?

Please have a look here:
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/metadata_guide.html#

> But then I do some processing in R and while I have managed to write the same kind of geotif with the same DESCRIPTION field,

>I copy the output of diff between both gdalinfo outputs

Looks like _gdalinfo_ is not reporting all dataset-level metadata, e.g. the relevant wavelength info is not reported, but you can see it in the GDAL Metadata widget:
![image](https://github.com/user-attachments/assets/171723a1-3b79-4228-97ac-aa153a13b890)

This information is not preserved by your external R algorithm. You have to set relevant metadata afterwards. E.g. by using the GDAL API.

**Comment by aloboa** [comment]
> Please have a look here:
> https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/metadata_guide.html#

I had looked into that info indeed, but while it is a clear explanation, it is not clear at all how to put it in practice. For example,
the most practical might be at the end:

>  This should allow for simple copy&paste approaches, when moving metadata from an ENVI Header file to a GDAL PAM file:

but how should we do it? In which file should that info go? A demo file would be very useful. 

> This information is not preserved by your external R algorithm. You have to set relevant metadata afterwards. E.g. by using the GDAL API.

But if we know what is needed and where ("what" is quite well documented, but "where" is not), I can try to do it myself or, best, fill a feature request to https://github.com/rspatial/terra

**Comment by janzandr** [comment]
Yes, agreed, getting started with STAC-like files is not well explained. Here are some example files, which we use for testing:
[TestRasterReader.zip](https://github.com/user-attachments/files/18109132/TestRasterReader.zip)

Maybe it is also helpful to look at the actual unittests, where we create such STAC files programmatically:
https://github.com/EnMAP-Box/enmap-box/blob/main/tests/enmap-box/enmapboxprocessing/test_rasterreader.py#L558

BUT, maybe not using STAC is also an option. You can also just use the standard GDAL Metadata Model for specifying metadata, which is then stored in the GTiff itself, or (if metadata is too large) is stored inside the aux.xml sidecar file.

**Comment by aloboa** [comment]
> Here are some example files, which we use for testing:
> [TestRasterReader.zip](https://github.com/user-attachments/files/18109132/TestRasterReader.zip)

The GDAL PAM file `raster.tif.aux.xml` in `TestRasterReader/test_stacMetadata_enviStyle/`
has nothing to see with a hdr file and is not related to what is shown in the last paragraph of
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/metadata_guide.html#
```

<PAMDataset>
  <PAMRasterBand band="1">
    <Metadata>
      <MDI key="STATISTICS_MINIMUM">0</MDI>
      <MDI key="STATISTICS_MAXIMUM">0</MDI>
      <MDI key="STATISTICS_MEAN">0</MDI>
      <MDI key="STATISTICS_STDDEV">0</MDI>
      <MDI key="STATISTICS_VALID_PERCENT">100</MDI>
    </Metadata>
  </PAMRasterBand>
  <PAMRasterBand band="2">
    <Metadata>
      <MDI key="STATISTICS_MINIMUM">0</MDI>
      <MDI key="STATISTICS_MAXIMUM">0</MDI>
      <MDI key="STATISTICS_MEAN">0</MDI>
      <MDI key="STATISTICS_STDDEV">0</MDI>
      <MDI key="STATISTICS_VALID_PERCENT">100</MDI>
    </Metadata>
  </PAMRasterBand>
</PAMDataset>
```

**Comment by janzandr** [comment]
> How? Is there a tool or script to,eg, include the info from a hdr file into the Gtif itself or in a companion GDAL PAM file?

Use the GDAL API for that. You can just ask ChatGPT: "How set band metadata with PyGDAL."

> Also, why is enmapbox saving a *.tif.vrt (LC08_L2SP_20230718_enmapbox.tif.vrt in this case) file?

This is just an implementation detail. We always create a VRT file first, which may then be translated into a GTiff or ENVI BSQ.
Feel free to delete the VRT.

> The useful example would include a tif file, its hdr and its corresponding GDAL PAM file.

We don't have that, because it is not the goal to have identical metadata in several locations.
Our goal is to support multiple metadata standards.
In your case, all metadata is stored in the STAC file. The GDAL PAM file was just created automatically by GDAL.

**Comment by aloboa** [comment]
> In your case, all metadata is stored in the STAC file

I wish they were, the problem is that the wavelength info is not, and I want to include it. 
You say in the doc

> This should allow for simple copy&paste approaches, when moving metadata from an ENVI Header file to a GDAL PAM file

therfore having an example of both an ENVI hdr and the GDAL PARAM file would make sense.

**Comment by janzandr** [comment]
> I wish they were, the problem is that the wavelength info is not, and I want to include it.

Here is a STAC example that includes wavelength in an ENVI-like style:
![image](https://github.com/user-attachments/assets/61357da3-2730-4270-a312-89c20c9c958a)

It should be very easy to copy and paste the list of wavelength from an ENVI *.hdr to the STACK file, by replacing this section:
![image](https://github.com/user-attachments/assets/ca14571d-4752-4d9b-ac73-609b5d323054)

**Comment by aloboa** [comment]
1. Tried with the STAC (*.stac.json) metadata file,
(although I was asking about the PAM GDAL (*.aux.xml) file because the files I get through enmapbox (and that I could use as templates) are *.aux.xml )

This is the file L8W_m.stac.json I made for L8_m.tif:

```
{
  "properties": {
    "envi:metadata": {
      "band_names": [
        "Coastal aerosol (443 Nanometers)",
        "Blue ( 482 Nanometers)",
        "Green ( 562 Nanometers)", 
        "Red ( 655 Nanometers)",
        "NIR (865 Nanometers)",
        "SWIR-1 (1610 Nanometers)",
        "SWIR-2 (2200 Nanometers)" 
      ],
      "wavelength": [
        443,
        482,
        562,
        655,
        865,
        1610,
        2200
      ],
      "wavelength_units": "nanometers",
      "fwhm": [
        15.98,
        60.04,
        57.33,
        37.47,
        28.25,
        84.72,
        186.66
      ],
      "bbl": [
        1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      "acquisition_time": "2023-07-18T12:00:00",
      "my_key": 42
    }
  }
}

```


2. I followed your advice and this is what I get through pygdal from the gtiff saved by Project/Add Product:

```
> >>> from osgeo import gdal
> >>> raster = gdal.Open('LC08_L2SP_20230718_enmapbox.tif', gdal.GA_ReadOnly)
> >>> raster_metadata = raster.GetMetadata()
> >>> print(raster_metadata)
> {'AREA_OR_POINT': 'Area'}
> >>> band = raster.GetRasterBand(1)
> >>> 
> >>> # Get the metadata for the specified band
> >>> band_metadata = band.GetMetadata()
> >>> 
> >>> # Print the band metadata dictionary
> >>> print("Band 1 Metadata:")
> Band 1 Metadata:
> >>> print(band_metadata)
> {'bbl': '1', 'STATISTICS_APPROXIMATE': 'YES', 'STATISTICS_MAXIMUM': '1.0139194726944', 'STATISTICS_MEAN': '0.23273195438495', 'STATISTICS_MINIMUM': '0.00035200000274926', 'STATISTICS_STDDEV': '0.044643262561122', 'STATISTICS_VALID_PERCENT': '58.3'}

```
Note this is the file displaying the wavelength in the x-axis of the spectra, but apparently the wavelength info is not in the Geotif. Furthermore, I get less information with pygdal than using gdalinfo.

**Comment by janzandr** [comment]
Please share the files.

**Comment by aloboa** [comment]
Landsat8 imported with enmapbox (works right):
* GTiff: https://saco.csic.es/s/nKxagnQnHPecwGc
* aux.xml: https://saco.csic.es/s/eXmTtmLgdiBqdw8
* log: https://saco.csic.es/s/7aNYZJeq7YfG7Ty
* vrt: https://saco.csic.es/s/NbLJNzsogDEYr5K
*gdalinfo output: https://saco.csic.es/s/8rdna27yTgAbaCP

The same image, processed and saved as GTiff with R:
* GTiff: https://saco.csic.es/s/xyW2ejTR7oD3EpK
* gdalinfo output: https://saco.csic.es/s/Xfg4caYDWEqXjqo
* stac.json (made by me): https://saco.csic.es/s/cz4xawAy2gQTX67


Also, please note that the example you sent 

> Yes, agreed, getting started with STAC-like files is not well explained. Here are some example files, which we use for testing:
> [TestRasterReader.zip](https://github.com/user-attachments/files/18109132/TestRasterReader.zip)

has no metadata according to enmapbox:

![image](https://github.com/user-attachments/assets/fd35e8cf-4ddc-4403-8ce1-8e58ec561082)

**Comment by janzandr** [comment]
> has no metadata according to enmapbox

That is correct. The GDAL Metadata widget is not yet supporting the STAC-like information, so you want see those in the GUI.
@jakimowb, please correct my if I'm wrong, as I remember it, we didn't want to have STAC-like metadata inside the GDAL Metadata widget, to not confuse both types of sources.

Currently, only processing algorithms and most app (those which are using the RasterReader API) are supporting STAC-like metadata.

All widgets and apps that rely on the QPS API for metadata handling aren't supporting Stac-like metadata.

I would agree, that this situation is not optimal.
@jakimowb if you feel like, maybe you should think about extending the QPS metadata handling. Maybe just by using the RasterReader API to avoid duplicated implementations (?). But you can do as you wish, I'm fine with it.

**Comment by janzandr** [comment]
> The same image, processed and saved as GTiff with R... stac.json (made by me)

The name of the sidecar file is slightly wrong. You need to include the ".tif" part.
![image](https://github.com/user-attachments/assets/dbd0803d-7ea0-4e63-8334-f7e5cdbac2a9)

Now it is working as expected:
```
reader = RasterReader(r'C:\Users\Andreas\Downloads\L8W_mv2.tif')
print(reader.wavelength(1))
```
prints:
`443.0`

**Comment by janzandr** [comment]
Final remarks: for now you really should use the GDAL Metadata API, if you want to have full compatibility with the GUI.

**Comment by aloboa** [comment]
> > The same image, processed and saved as GTiff with R... stac.json (made by me)
> 
> The name of the sidecar file is slightly wrong. You need to include the ".tif" part. ![image](https://private-user-images.githubusercontent.com/45030715/395574086-dbd0803d-7ea0-4e63-8334-f7e5cdbac2a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMDI2OTQsIm5iZiI6MTczNDEwMjM5NCwicGF0aCI6Ii80NTAzMDcxNS8zOTU1NzQwODYtZGJkMDgwM2QtN2VhMC00ZTYzLTgzMzQtZjdlNWNkYmFjMmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDE1MDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YWViOTRiYTMzZDE5MzQ1Y2EyYjg4NzNhM2ViZjljNGIzYjg1NjBiYjRkYWEzOGYxNmY1NDRkMGY1ODI4OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Eaf5sYGt0VoRt7vF63jx0_abjAueSYLOM_E-BDtzvLU)
> 
> Now it is working as expected:
>

No, it does not: the spectra cannot be displayed along wavelength (even after renaming as you indicate):
![image](https://github.com/user-attachments/assets/caaf9198-1370-4edb-b72c-ba9a219e76a9)

Please, check on your side, perhaps it does with your dev version.

**Comment by aloboa** [comment]
Also, please note that this code does not print any wavelength information **for the image resulting from your product import** (please run it):
```

from osgeo import gdal
raster = gdal.Open('LC08_L2SP_20230718_enmapbox.tif', gdal.GA_ReadOnly)
raster_metadata = raster.GetMetadata()
print(raster_metadata)
band = raster.GetRasterBand(1)
band_metadata = band.GetMetadata()
print(band_metadata)
```

Regarding your code, it seems I am missing a module to be imported for RasterReader (I import following minimumexample):

```
>>> import os
>>> from qgis.PyQt.QtGui import QIcon
>>> from qgis.PyQt.QtWidgets import QMenu, QAction, QWidget, QHBoxLayout, QLabel, QPushButton
>>> from enmapbox.gui.applications import EnMAPBoxApplication
>>> from qgis.core import QgsProcessingAlgorithm, QgsProcessingParameterRasterLayer, QgsProcessingParameterNumber, \
...     QgsProcessingParameterRasterDestination, QgsProcessingContext, QgsProcessingFeedback, QgsProcessingParameterBand, \
...     QgsProcessingParameterVectorLayer, QgsProcessingParameterField, QgsProcessingParameterMapLayer, \
...     QgsProcessingParameterFile, QgsProcessingParameterString, QgsProcessingParameterBoolean, QgsProcessingParameterEnum, \
...     QgsProcessingParameterVectorDestination, QgsProcessingParameterFileDestination, \
...     QgsProcessingParameterFolderDestination
>>> 
>>> reader = RasterReader('LC08_L2SP_20230718_enmapbox.tif')
    Traceback (most recent call last):
      File "/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/pyqtgraph/pyqtgraph/console/repl_widget.py", line 104, in runCmd
        exec(cmdCode, self.globals(), self.locals())
      File "<input>", line 1, in <module>
    NameError: name 'RasterReader' is not defined
```

**Comment by aloboa** [comment]
> Final remarks: for now you really should use the GDAL Metadata API, if you want to have full compatibility with the GUI.

I tried to do that for L8W_mv2.tif from the very beginning: the wavelength is in the "Description" field,and gdalinfo does not report differences with LC08_L2SP_20230718_enmapbox.tif (which is the image that works fine). 
And no alternative solutions work : 
* Copy and paste metadata in enmapbox does not work.
* Having a correct .tif.stac.json file does not work.
* I do not know how and where I should write the wavelength info within the GTIff as pyGDAL does not report it.

**Comment by janzandr** [comment]
> No, it does not: the spectra cannot be displayed along wavelength (even after renaming as you indicate):

The SpectralView is using QPS API which is not yet supporting STAC.

You could use the Profile Analytics tool:
![image](https://github.com/user-attachments/assets/3091b812-6949-4290-9209-3781bdc68138)

**Comment by janzandr** [comment]
>  NameError: name 'RasterReader' is not defined

from enmapboxprocessing.rasterreader import RasterReader

**Comment by janzandr** [comment]
> Also, please note that this code does not print any wavelength information for the image resulting from your product import (please run it):

GDAL Metadata is stored in different domains. To get all domains (incl. the ENVI domain), you can use:
`raster.GetMetadata_Dict()`

**Comment by aloboa** [comment]
`

> from enmapboxprocessing.rasterreader import RasterReader

`

OK, rasterreader works now, but this does not seem to be what I need as I need to write the gdal metadata.
I have found
https://enmap-box.readthedocs.io/en/release_3.13/usr_section/usr_cookbook/wavelength_information.html
which seems the way to go (with GetMetadataItem() and SetMetadataItem() .

> 
> GDAL Metadata is stored in different domains. To get all domains (incl. the ENVI domain), you can use:
> raster.GetMetadata_Dict()

```
>>> from osgeo import gdal
>>> path = 'LC08_L2SP_20230718_enmapbox.tif'
>>> dataset: gdal.Dataset = gdal.Open(path)
>>> print(dataset.GetMetadataItem('wavelength_units', 'ENVI'))
nanometers
>>> print(dataset.GetMetadataItem('wavelengths', 'ENVI'))
{490, 560, 665}
>>> print(dataset.GetMetadataItem('wavelength', 'ENVI'))
{443, 482, 562, 655, 865, 1610, 2200}
>>> print(dataset.GetMetadata_Dict())
{'AREA_OR_POINT': 'Area'}
```
weird...


BTW, why enmapbox wrote 1 line "wavelength" with 7 values (row 3) and another "wavelengths" (row 4) in GDAL/OGR Metadata?

![image](https://github.com/user-attachments/assets/d396c49e-f9ee-4186-ac17-a8a5bbf88bbd)

**Comment by aloboa** [comment]
> The SpectralView is using QPS API which is not yet supporting STAC.

This should be noted in https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/metadata_guide.html# ...

**Comment by janzandr** [comment]
> > The SpectralView is using QPS API which is not yet supporting STAC.
> 
> This should be noted in https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/metadata_guide.html# ...

I created a FR here: https://github.com/EnMAP-Box/enmap-box/issues/1058

**Comment by aloboa** [comment]
I refer to the 
`{490, 560, 665}`
which is wrong but coincident with the info in the last example of:
https://enmap-box.readthedocs.io/en/release_3.13/usr_section/usr_cookbook/wavelength_information.html

By some reason, this wrong info got into the .tif.aux.xml file:
```
<PAMDataset>
  <Metadata domain="ENVI">
    <MDI key="wavelengths">{490, 560, 665}</MDI>
  </Metadata>
```

I can't tell why; it certainly was not a manual edit in the file. It was probably an error trying to set the wavelength values in the Python console. 
What is strange is that the values appear in the .tif.aux.xml file.
I just recover the original .tif.aux.xml file and forget about this,
This issue raises the point of the potential conflicts originating from having multiple files for the same purpose. But this should be discussed elsewhere.

**Comment by janzandr** [comment]
> It was probably an error trying to set the wavelength values in the Python console.

Alright, if this is the case, all is fine.
If the values are written by using the EnMAP-Box, it would be a problem.
