### ISSUE TITLE
Blank red band when adding multiband raster layer in default colors (RGB)

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#106]
When adding a raster in default colors the red band is left unassigned in Multiband color renderer
![grafik](https://user-images.githubusercontent.com/15610561/193842070-438a7dd0-0855-4b63-8f6f-63487f0f3dcf.png)

Log shows this warning:
`Warning: Logged warning: Band 0 does not exist.`

Version 3.11.20221001T022425.main Code 3ddc7f39f87

**Comment by janzandr** [comment]
That is the same problem as in #80.
