### ISSUE TITLE
improve units guessing for old FORCE TSI raster

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#111]
In FORCE v.1,2_beta, date time info is coded as ENVI wavelength, without specification of wavelength units:
```
ENVI
description = {FORCE v. 1.2_beta Time Series Analysis}
...
wavelength = {2015.003, 2015.025, 2015.047, 2015.068, 2015.090, 2015.112, 2015.134, 2015.156, 2015.178, 2015.199, 2015.221, 2015.243, 2015.265, 2015.287, 2015.309, 2015.331, 2015.352, 2015.374, 2015.396, 2015.418, 2015.440, 2015.462, 2015.484, 2015.505, 2015.527, 2015.549, 2015.571, 2015.593, 2015.615, 2015.637, 2015.658, 2015.680, 2015.702, 2015.724, 2015.746, 2015.768, 2015.790, 2015.812, 2015.833, 2015.855, 2015.877, 2015.899, 2015.921, 2015.943, 2015.964}
```

Example data for whole Turkey can be found here: SAN_RSDBrazil\LandsatData\Landsat_Turkey\07_FORCE\level4

It is proposed to correctly recognize such raster as temporal and not as spectral.

1. `RasterReader.wavelength(bandNo)` should return `None`
2. `RasterReader.centerTime(bandNo)` should return the `QDateTime` that corresponds to the given decimal year.

**Comment by janzandr** [comment]
Done
![image](https://user-images.githubusercontent.com/45030715/193942179-534ed814-30fc-4ec4-9736-1c6405d5a439.png)

**Comment by janzandr** [comment]
Hi @jakimowb , you may want to concider this also for the QPS metadata handling. Currently, it's not working:
![image](https://user-images.githubusercontent.com/45030715/193942605-0e7e28a7-2f14-4fd9-9588-cdeaca1008bd.png)

**Comment by jakimowb** [comment]
What "wavelenght unit" is given in that case?

**Comment by janzandr** [comment]
![image](https://user-images.githubusercontent.com/45030715/193998559-045aab43-661a-4df5-93d4-58c5fea232f8.png)

**Comment by janzandr** [comment]
You may adopt my unittest: _enmapboxprocessing\test\test_rasterreader.py_

   ```
 def test_centerTime_ForceTSIFormat_v1_2(self):  # see #111
        writer = self.rasterFromArray(np.zeros((1, 1, 1)))
        writer.setMetadataItem('wavelength', 2015.003, '', 1)
        writer.setMetadataItem('description', '{FORCE v. 1.2_beta Time Series Analysis}', 'ENVI')
        writer.close()
        reader = RasterReader(writer.source())
        self.assertIsNone(reader.wavelength(1))
        self.assertEqual(Utils.decimalYearToDateTime(2015.003), reader.centerTime(1))
        self.assertIsNone(reader.wavelengthUnits(1))
```
