### ISSUE TITLE
Update readme_enmapboxtestdata.pdf

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#114]
Currently at least the file endings in `enmapboxplugin/enmapbox/exampledata/readme_enmapboxtestdata.pdf` are not up to date. And some are missing.
https://github.com/EnMAP-Box/enmap-box/blob/main/enmapbox/exampledata/readme_enmapboxtestdata.pdf
Low priority issue.

**Comment by janzandr** [comment]
Hi @thielfab , I think we decided to create new example datasets, when we have real EnMAP data. That is not far away, so I think this is just a won't fix.
