### ISSUE TITLE
[Spectral Index Creator] GUI glitch in table

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#118]
[glitch.webm](https://user-images.githubusercontent.com/15610561/194032623-76c6dcd4-b373-4235-8d3f-d25bc41f185d.webm)

**Comment by janzandr** [comment]
Can't reproduce this on my Windows 10 system.

**Comment by thielfab** [comment]
![](https://i.redd.it/6otkjd8gobl11.jpg)
Ok, then probably an issue with linux and/or my local implementation
