### ISSUE TITLE
QgsMapLayer menus are not created in case of ModuleNotFound exceptions in sub-applications

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#143]
Basic QGIS installations do not come with packages like sklear, scipy, matplotlib etc. In that case the EnMAP-Box throws a warning during startup.

In case one of these none-standard PyQGIS packages is missing but required in an app that can be accessed from a map layer context menu, the entire context menu fails to be created.

**Comment by janzandr** [comment]
Please show an example.
Which dependency should be deinstalled to reproduce this.

**Comment by janzandr** [comment]
The setup for testing non-blocking-dependencies is gone.
@jakimowb have you removed it? If so, please put it back.
![image](https://user-images.githubusercontent.com/45030715/194718458-d42670c4-44ae-412c-ace9-4a8cc507807d.png)

**Comment by jakimowb** [comment]
@janzandr as far as I can remember the errors were produced by missing matplotlib and scipy modules. 
Both packages may be not installed, e.g. if QGIS gets installed with the OSGEO network installer.

**Comment by janzandr** [comment]
I'm still not sure about the status.
Have you already fixed the problem, right?
What do you want me to test?
Or can we just close this issue?

**Comment by jakimowb** [comment]
No, because you closed https://github.com/EnMAP-Box/enmap-box/pull/144 the bug is now released with 3.11

**Comment by janzandr** [comment]
No problem. We can still fix it.
Please show an example of that bug.
Which dependency should be deinstalled to reproduce this.

**Comment by jakimowb** [comment]
> packages like sklear, scipy, matplotlib

This is the case if you install a fresh QGIS with the OSGeo4W installer.

````
Traceback (most recent call last):
  File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\dataviews\dockmanager.py", line 1578, in createContextMenu
    self.addRasterLayerMenuItems(node, menu)
  File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\dataviews\dockmanager.py", line 1706, in addRasterLayerMenuItems
    from bivariatecolorrasterrendererapp import BivariateColorRasterRendererApp
  File "D:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\geo_beja\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\bivariatecolorrasterrendererapp\__init__.py", line 1, in 
    from bivariatecolorrasterrendererapp.bivariatecolorrasterrendererdialog import BivariateColorRasterRendererDialog
  File "D:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\geo_beja\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\bivariatecolorrasterrendererapp\bivariatecolorrasterrendererdialog.py", line 4, in 
    from scipy.interpolate import interp2d
  File "D:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'scipy'
````

**Comment by jakimowb** [comment]
Probably only these, but this might change in future if more packages are required by apps that contribute to context menues.

scipy, for example, was never listed in the [none-blocking-dependencies folder](https://bitbucket.org/hu-geomatics/enmap-box/src/develop/tests/non-blocking-dependencies/). If not testing in a "fresh" QGIS environment, we would have never found bug using the "mock-off" approach.

**Comment by janzandr** [comment]
True, I wasn't aware that you can have a QGIS installation without scipy.
Your approach sound really cool.
Just to understand it: you will actually install all the different QGIS versions for all the operating systems inside your testing environment?
It sounds like a hell of a job.
Keep me updated!

**Comment by janzandr** [comment]
@jakimowb I tested your solution for handling missing packages when building the context menu:
![image](https://user-images.githubusercontent.com/45030715/195301032-23d4bc38-af20-4901-bfe5-6b29f7d630fc.png)

Looks good to me.

**Comment by janzandr** [comment]
But, until you have implemented your **_testing in a "fresh" QGIS environment_** approach, I will reintroduce the dependency mocks for the optional modules.

**Comment by janzandr** [comment]
@jakimowb - FYI
![image](https://user-images.githubusercontent.com/45030715/195304856-c2f09412-ca06-4c6e-b101-2d20ada4ba06.png)
