### ISSUE TITLE
[GDAL Metadata] editing metadata is broken

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#147]
![animation9](https://user-images.githubusercontent.com/45030715/194727379-694921b9-6e1f-496b-9711-bacffe6c8050.gif)

**Comment by jakimowb** [comment]
already fixed via https://github.com/OSGeo/gdal/issues/6444
Test with e.g. TIF. In qgis-dev you already have GDAL 3.6 to see that it works.

**Comment by janzandr** [comment]
So it will start working with QGIS 3.28+, right?

**Comment by jakimowb** [comment]
If using GDAL 3.6, that for ENVI files as well.
I don't know if this will be the case for Linux/conda/macOS

**Comment by janzandr** [comment]
Is the editor currently working for GTiff raster?
