### ISSUE TITLE
reimplement Reclassify app and algorithm

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#15]
The current Reclassify app is broken and needs to be reimplemented.

**Comment by jakimowb** [comment]
Feature required to be implemented for re-implemented GUI interface

- [ ] automatic matching of classes between source and target classes
- [ ] visualization of source and target class names and colors
- [ ] interactive modification of target classification scheme

**Comment by janzandr** [comment]
@jakimowb , I looked into your app, and I don't think, that I need to reimplement your GUI, I will just reimplement the algorithm and connect it inside your app.

**Comment by janzandr** [comment]
Implemented new processing algorithm:
![image](https://user-images.githubusercontent.com/45030715/189068244-829a4375-07d3-4aa7-8b1c-aaed1cf749c3.png)
