### ISSUE TITLE
implement a Raster Band Stacking (EO4Q) app

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#155]
The existing _Virtual Raster Builder_ (props to @jakimowb) plugin is a mighty, but complex, and not very intuitive tool:
![image](https://user-images.githubusercontent.com/45030715/194730856-e29c0b9a-4d70-482b-859c-ff20e8f0fade.png)

It is proposed to implement a simplified, more intuitive version for stacking raster bands.

**Comment by vprint** [comment]
Hello,
what will be the differences between this tool and the Stack Raster Layers tool ?

**Comment by janzandr** [comment]
You can already check it out: 
https://github.com/EnMAP-Box/enmap-box/releases/tag/v3.12-alpha.0
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/eo4q.html#raster-band-stacking
