### ISSUE TITLE
remove "float" button for already floating views

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#157]
_Requested by Sebastian van der Linden._

The "float" button for an already floating view is still visible an clickable:
![image](https://user-images.githubusercontent.com/45030715/194731341-0887e492-4cbe-4d89-9010-abc3d198a746.png)

**Comment by jakimowb** [comment]
Not a bug. This button needs to be there (and is in pyqtgraph the default). 

Imagine you added other views to that DockArea in your screenshot. Than the float button allows you to release a view into a new DockArea

**Comment by janzandr** [comment]
Ah, a single floating view is already a new DockArea. Now it makes (technically) sense.

**Comment by jakimowb** [comment]
Use EnMAP-Box maps and speclib views on as many screens you like ;-)
