### ISSUE TITLE
[Map View] remove "QGIS..." from context menu

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#159]
_Requested by Sebastian van der Linden._

Those are confusing and should be removed:
![image](https://user-images.githubusercontent.com/45030715/194731469-8da551d2-389b-438d-b4fa-87c8d2ea6a45.png)

**Comment by janzandr** [comment]
I would agree with Sebastian.

**Comment by thielfab** [comment]
Do not remove. I don't see the confusion...

**Comment by janzandr** [comment]
@jakimowb could we actually link the QGIS map canvas with the EnMAP-Box MapView canvases?

**Comment by jakimowb** [comment]
I also do not see any confusion.
@janzandr yes, it is technically possible.

**Comment by janzandr** [comment]
Alright, let's keep it as is.
Also, actual linking of QGIS map canvas with EnMAP-Box map views would be cool.
