### ISSUE TITLE
[Map View] simplify Crosshair > Pixel Grid menu

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#160]
_Requested by Sebastian van der Linden._

Remove those options:
![image](https://user-images.githubusercontent.com/45030715/194731537-1d2ce99d-5703-448d-9aac-82f6d067ee29.png)

**Comment by janzandr** [comment]
I agree with Sebastian.
@thielfab any comments?

**Comment by thielfab** [comment]
Yes maybe, if top raster is the default anyway...

**Comment by janzandr** [comment]
Ah sorry, I didn't understand what those options are doing.
We should keep them!
