### ISSUE TITLE
Add example data does -- nothing

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#175]
"Add example data" is brokent with EnMAP-Box 3.11.0

The data gets downloaded for 3.10, but after that nothing happens  
![grafik](https://user-images.githubusercontent.com/1404870/194808431-9eeffd7a-5875-46ef-b0d3-44817d44b1b1.png)

**Comment by janzandr** [comment]
Can't reproduce this. Have you restarted your QGIS after installing the EnMAP-Box?
