### ISSUE TITLE
The setup for testing non-blocking-dependencies is gone.

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#176]
The setup for testing non-blocking-dependencies is gone.
@jakimowb have you removed it? If so, please put it back.
![image](https://user-images.githubusercontent.com/45030715/194718458-d42670c4-44ae-412c-ace9-4a8cc507807d.png)

_Originally posted by @janzandr in https://github.com/EnMAP-Box/enmap-box/issues/143#issuecomment-1272357129_

**Comment by jakimowb** [comment]
Seems this non-blocking-dependencies folder was never copied into the GH repo. 
Feel free to add it, but I think it is not worth to do so
- it simulates the abscence of modules only for modules, from which we know that they might be missing. 
- If another module is available in your local installation but not in the non-blocking-dependencies, you will not be able to test what happens in case it is missing in a real QGIS installation
- it adds uncessesary code to the repo

Instead, we should better test the plugin itself and in well-defined QGIS installation, as done here
https://github.com/qgis/QGIS/blob/master/.docker/README.md

**Comment by janzandr** [comment]
Alright, no dependency checks anymore. But why have you created that issue?

**Comment by jakimowb** [comment]
> Alright, no dependency checks anymore. But why have you created that issue?

Of course we need to check what happens in case of missing optional dependencies. It just needs to be ensured that these optional dependencies indeed are missing. Therefore testing the EnMAP-Box should be done in a fresh QGIS installation, not by "mocking the missing packages"

**Comment by janzandr** [comment]
Thanks @jakimowb , then I will wait until the _"testing inside a fresh QGIS installation"_ is running.

**Comment by janzandr** [comment]
Actually, due to #143 it makes sense to have the mocks in place for quick testing.
