### ISSUE TITLE
[Spectral Library View] use speclib default style 

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#197]
Currently, speclib profiles are always visualized in white, even if a default style is defined (QML file):
![image](https://user-images.githubusercontent.com/45030715/195722965-a4297661-cf49-4045-9f9c-92baf271c289.png)

It is proposed to use the colors from the default style as line colors directly:
![image](https://user-images.githubusercontent.com/45030715/195723087-90eec9e3-1da8-4375-ac82-4ef7d3779ac4.png)

**Comment by jakimowb** [comment]
Implemented

**Comment by janzandr** [comment]
Many thanks!
