### ISSUE TITLE
allow to store project settings

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#201]
_Discussed with the team and requested by multiple users. Is kind of a hot topic. Several users didn't want to use the EnMAP-Box GUI, because complex GUI setups get lost after every crash or after closing the EnMAP-Box._

Replaces issue on bitbucket: https://bitbucket.org/hu-geomatics/enmap-box/issues/36/project-settings

- [x] save EnMAP-Box settings as part of QGIS Project (*.qgs file):
- [x] implement an EnMAPBoxProjectSettings class managing all settings
- [x] implement a mechanism that allows Core/User Apps to get/set individual project settings
- [x] implement a mechanism that allows QgsDockWidgets to get/set individual project settings
- [x] project settings are stored and restored using the QGIS menu buttons; replicate those buttons inside the EnMAP-Box project menu
![image](https://user-images.githubusercontent.com/45030715/205910934-1c8daa26-2fa8-4387-8591-33f599c3f736.png)
- [x] provide two interfaces for getting/setting project settings: 1) via dictionary, 2) via QDomDocument

**Comment by ernstste** [comment]
Ideally, this would include all layer styles, plot options, etc..., that make up complex setups (e.g., for reference data generation) to keep the time required for setting up the workspace to a minimum after closing the project or a crash.
