### ISSUE TITLE
allow human-readable JSON version of the PKL dataset

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#21]
_Requested by @jakimowb ._

**Comment by jakimowb** [comment]
JSON may be more easy to implement, however, a CSV file that list features + labels is even more readible for humans.
Furthermore, a CSV-based format eases the exchange of training datasets. 

CSV datasets can be easily transformed into input file to train a classifier in [FORCE](https://force-eo.readthedocs.io/en/latest/components/auxilliary/train-param.html), or use FORCE training data to train models in the EnMAP-Box

**Comment by janzandr** [comment]
If you really need this, I could implement CSV a third option. 
Please open a new issue for that and share an example CSV file with the same content as:
/enmap-box/tests/testdata/classifier.pkl.json

**Comment by janzandr** [comment]
> CSV datasets can be easily transformed into input file to train a classifier in [FORCE](https://force-eo.readthedocs.io/en/latest/components/auxilliary/train-param.html), or use FORCE training data to train models in the EnMAP-Box

Almost forgot, that we already have that :-)
![image](https://user-images.githubusercontent.com/45030715/189110849-f6e3f94f-fa65-4713-886b-13291db8d028.png)

@jakimowb please test, if this is what you need.

**Comment by janzandr** [comment]
Implemented new algorithm:
![image](https://user-images.githubusercontent.com/45030715/189117393-ab230e07-d72b-4084-aded-07c283f3f9de.png)

**Comment by janzandr** [comment]
Add new option to the ClassificationDatasetSelection widgets:
![image](https://user-images.githubusercontent.com/45030715/189117583-6684d74b-36d5-4aca-aee0-81e909ed51a6.png)

**Comment by janzandr** [comment]
Need to do that for regression and unsupervised datasets as well.

**Comment by jakimowb** [comment]
> > CSV datasets can be easily transformed into input file to train a classifier in [FORCE](https://force-eo.readthedocs.io/en/latest/components/auxilliary/train-param.html), or use FORCE training data to train models in the EnMAP-Box
> 
> Almost forgot, that we already have that :-) ![image](https://user-images.githubusercontent.com/45030715/189110849-f6e3f94f-fa65-4713-886b-13291db8d028.png)
> 
> @jakimowb please test, if this is what you need.

Unfortunately it's not what we discussed. My fault, I should have described it more in detail when opening this issue.

**Comment by janzandr** [comment]
Hi @jakimowb , not quite sure what is missing?
1. JSON can now be selected as one of the many input sources.
2. CSV-FORCE-Format was already implemented:
![image](https://user-images.githubusercontent.com/45030715/189485866-61f701d4-2b70-4e98-a838-0fdb0b6da68a.png)

Please explain a bit better, what needs to be changed.

**Comment by jakimowb** [comment]
This is possible?

![image](https://user-images.githubusercontent.com/1404870/189486235-af04160d-abc9-49bf-bf82-02a0006f48d7.png)

**Comment by janzandr** [comment]
No. 
CSV-FORCE-format is an external format with **two CSV files,
You need to use this algo:
![image](https://user-images.githubusercontent.com/45030715/189487019-4ce44615-d174-4a65-9815-c12eb0f119b8.png)

**Comment by janzandr** [comment]
Not sure if we are done here. Please re-open, for further questions.

**Comment by janzandr** [comment]
> This is possible and runs?
> 
> ![image](https://user-images.githubusercontent.com/1404870/189486235-af04160d-abc9-49bf-bf82-02a0006f48d7.png)
> 
> What exactly don't you understand in [#21 (comment)](https://github.com/EnMAP-Box/enmap-box/issues/21#issuecomment-1239888669) ?

This is now possible with JSON files. 
CSV-Force is still not possible, because the data is scattered over multiple files.

**Comment by jakimowb** [comment]
Can you pin a mini example for such a  JSON or CSV Training data file here?

**Comment by janzandr** [comment]
https://github.com/EnMAP-Box/enmap-box/blob/main/tests/testdata/classifier.pkl.json
