### ISSUE TITLE
implement a custom BuildVrtStack function

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#217]
**_gdal.BuildVrt_** can only stack bands that are stored inside single-band raster files. So usually we need to create single-band raster files, before we can stack the bands together.

E.g. when creating a stack of vegetation indices, we would create a VRT (using Pixel Functions) for each index first:
![image](https://user-images.githubusercontent.com/45030715/197241175-36b9b6f5-34a5-4cab-881c-a91ac907e8ba.png)

Now we would use gdal.BuildVrt to put the bands together into an _indices.vrt_ stack:
![image](https://user-images.githubusercontent.com/45030715/197241470-e273d1d6-f957-4967-b68f-0945f9616f68.png)

This works fine, but the  _indices.vrt_ stack is pointing to the single band VRTs. So we can't delete them:
![image](https://user-images.githubusercontent.com/45030715/197242025-3465571d-305c-4949-874a-678bdee01600.png)

It is proposed to have a **_BuildVrtStack_** function that builds a VRT that includes all source definitions and isn't dependent on the temp files.
Therefor we need to include the **VRTRasterBand** blocks, e.g.
![image](https://user-images.githubusercontent.com/45030715/197249016-7ea6570b-a1f0-48e9-8a94-bfdb50734466.png)

**Comment by jakimowb** [comment]
The VRT Raster Builder implements an object based model of a VRT Raster. This could be easily enhanced to allow for the definition of arbitrary XML elements, like the <PixelFunction*> tags.

**Comment by janzandr** [comment]
Thanks @jakimowb. 
The VRTs with Pixel Functions was just an example.
I want to be able to stack any single band VRT together without depending on the source VRTs afterwards.

Technically this should be quite easy. I just have to write my own VRT file containing the **VRTRasterBand** block of every single-band VRT:
![image](https://user-images.githubusercontent.com/45030715/197346618-52c0ae92-16fe-4848-9e42-8fc4209b5208.png)

A special handling of XML elements seams to be to complicated.

But I understand, that you don't have a solution that works out of the box, so I will write it myself.

I'll keep you updated!

**Comment by jakimowb** [comment]
That's actually what the VRT Raster Builder does: you can add as many source bands into a VRTRasterBand, as as many VRTRasterBands into a VRTRaster

**Comment by janzandr** [comment]
Maybe, but the plugin seams to be broken. No matter what I do, QGIS crashes.
Even if I just use the first band of _enmap_berlin.bsq_:
![image](https://user-images.githubusercontent.com/45030715/197358096-e8d653bc-be41-4854-b0f1-0bf21a04f874.png)

**Comment by janzandr** [comment]
> That's actually what the VRT Raster Builder does: you can add as many source bands into a VRTRasterBand, as as many VRTRasterBands into a VRTRaster

Also @jakimowb, I'm not sure if you got the important point here. If I would select the **EVI** and the **NDVI** band from those two VRTs...
![image](https://user-images.githubusercontent.com/45030715/197358226-8bd9b733-5dc4-4520-a505-cf70e0c47eaf.png)

... would the resulting VRT Stack still point to the **EVI.vrt** and the **NDVI.vrt**?

Could I delete the **EVI.vrt** and the **NDVI.vrt* files? Would the VRT Stack still work?

That's the whole point of the proposed **BuildVrtStack** function.

**Comment by janzandr** [comment]
Hi @jakimowb, just implemented it, you may want to check out the unittests:
[enmap-box/tests/enmap-box/enmapboxprocessing/test_gdalutils.py](https://github.com/EnMAP-Box/enmap-box/blob/main/tests/enmap-box/enmapboxprocessing/test_gdalutils.py)
