### ISSUE TITLE
make example sensor product locations importable

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#224]
We have a collection of sensor products, that is to big (> 22 GB) to have it inside the code repo:
![image](https://user-images.githubusercontent.com/45030715/197415538-f3114605-827e-4b02-862f-498c66ab1602.png)

But we still need that data to run some unittests on it.

Currently, we have all the data available on SAN EnMAP. A developer is expected to make a local copy of the data, or access the server directly.

In any case, it would be nice, if the actual sensor product locations could be imported, e.g.
```
>>>from enmapboxtestdata import SensorProducts
>>>SensorProducts.EnMAP_L1B
D:\data\sensors\enmap\ENMAP01-____L1B-DT0000004135_20221005T023547Z_010_V010106_20221014T102746Z
```
The root directory "D:\data\sensors" has to be properly set to an ENV variable. Default root points to SAN EnMAP server.

**Comment by janzandr** [comment]
Hi @jakimowb, would that be helpful to you?

**Comment by jakimowb** [comment]
Using an environmental variable is a good choice. The __init__.py could also check if the data exists in the local location
