### ISSUE TITLE
[Map View] 'QgsPointXY' object has no attribute 'toCrs'

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#243]
How to reproduce:
* Open **two** Map Views
* Click inside Map View

Changes in QGIS 3.28?

```
An error has occurred while executing Python code: 

AttributeError: 'QgsPointXY' object has no attribute 'toCrs' 
Traceback (most recent call last):
  File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/gui/enmapboxgui.py", line 1375, in onCrosshairPositionChanged
    mapCanvas.setCrosshairPosition(spatialPoint, emitSignal=False)
  File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/gui/mapcanvas.py", line 934, in setCrosshairPosition
    point = spatialPoint.toCrs(self.mapSettings().destinationCrs())
AttributeError: 'QgsPointXY' object has no attribute 'toCrs'


Python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] 
QGIS version: 3.28.0-Firenze Firenze, ed3ad0430f 
```

QGIS version | 3.28.0-Firenze | QGIS code revision | ed3ad0430f3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.2
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
DataPlotly | 3.9.2
ee_plugin | 0.0.5
enmapboxplugin | 3.11.0
latlontools | 3.6.6
ORStools | 1.5.2
profiletool | 4.2.2
QuickOSM | 2.1.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

**Comment by janzandr** [comment]
Confirmed.

**Comment by jakimowb** [comment]
Does the error occure if enMAP-Box was started from QGIS?
relates to #242

**Comment by janzandr** [comment]
Yes, in QGIS!

**Comment by jakimowb** [comment]
I cannot reproduce this with plugins build from [243-map-view-qgspointxy-object-has-no-attribute-tocrs](https://github.com/EnMAP-Box/enmap-box/tree/243-map-view-qgspointxy-object-has-no-attribute-tocrs)

**Comment by thielfab** [comment]
> I cannot reproduce this with plugins build from [243-map-view-qgspointxy-object-has-no-attribute-tocrs](https://github.com/EnMAP-Box/enmap-box/tree/243-map-view-qgspointxy-object-has-no-attribute-tocrs)

Issue still present on the mentioned branch

**Comment by janzandr** [comment]
Backport still missing:
![image](https://user-images.githubusercontent.com/45030715/203031564-b51c83bb-44ec-42aa-b0ae-17c9306d3b35.png)
