### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#258]
Reporting is anyoing, in particular if numbers have to be collect from websites.

A script that collect the following stats would be very helpful:

* [x] collect the number of opened and closed issues from https://github.com/EnMAP-Box/enmap-box/issues (`scripts/issue_tracker_stats.py` has done so via some detours for the bitbucket repo. It should now make use of github REST API)
* [x] collect the number of EnMAP-Box downloads from https://plugins.qgis.org/plugins/enmapboxplugin/
* [x] allow to limit the date range of interest to focus on the report period of interest (re.g. 1st half of 2022)
* [x] list all processing algorithms provided by the EnMAPBoxProcessingProvider (output to CSV/XLSX)
* [x] list the EnMAPBoxApplications

**Comment by janzandr** [comment]
Ah cool, wasn't aware that we can use a checklist of tasks inside an issue.

**Comment by janzandr** [comment]
Very similar to #938.
