### ISSUE TITLE
Layer Styling defaults and wavelength values

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box#266]
When viewing an EnMAP spectral data set, the "predefined" layer combinations are not available and the band wavelength values are not displayed. Using EnMAP-Box 3 (3.12alpha2.20221008T092702.main version).

**Comment by janzandr** [comment]
Have you downloaded the product from the EnMAP data portal?
https://planning.enmap.org/

Have you properly imported it?
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/tools.html#add-product
Or
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/eo4q.html#sensor-product-import

**Comment by grantboxer** [comment]
Hi Andreas,

 

Many thanks. I was opening up the tif file not the metadata file! I can’t remember if that was in the user notes?

 

Seems to work now.

 

Cheers Grant
