### ISSUE TITLE
[S2 Product Import] Dataset Metadata is dropped in the stacking

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#269]
When importing Sentinel-2 L2A, the Dataset specific metadata is not included in the vrt stack, but available in the vrt of the individual bands. Not crucial, but maybe nice to include them?

![grafik](https://user-images.githubusercontent.com/15610561/202679584-861e792b-4b44-4996-9154-cf05787ba807.png)

**Comment by janzandr** [comment]
Hmm, maybe there was a change in the GDAL API. I'm pretty sure that was not always the case.
Thanks @thielfab , I'll fix this.

**Comment by thielfab** [comment]
I also noted that the band (center) wavelength differs (metadata item vs description)
![grafik](https://user-images.githubusercontent.com/15610561/203083377-7f8a45b0-3eb0-4a55-9625-0f890fee2e66.png)
