### ISSUE TITLE
Color Space Explorer becomes unresponsive after using Decorrelation Stretch Renderer

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#27]
After using Decorrelation Stretch Renderer, Color Space Explorer becomes
unresponsive (you click the different options but the display is not updated).
Opening the Raster Layer Styling works, and then the Color Space Explorer works as well.

**Comment by janzandr** [comment]
Ah yes, that is a bug.
The Color Space Explorer is only working with layers using an RGB renderer.
The Decorrelation Strech Renderer is replacing the original RGB renderer, which is causing the bug.
