### ISSUE TITLE
[Raster math] Fix broken link in algorithm help text

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#271]
As the Raster math documentation moved, the link to [RasterMath cookbook recipe](https://enmap-box.readthedocs.io/en/latest/usr_section/usr_cookbook/raster_math.html) is no longer valid.
This should be the correct link:
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/applications.html#raster-math

**Comment by janzandr** [comment]
already fixed
