### ISSUE TITLE
implement a simple and interactive 3D spectral data cube visualization

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#272]
It is proposed to implement a simple 3D spectral data cube visualization like known from ENVI.
Such a cube consists of:

- the spectral raster layer itself used as the top-plane (1)
- the two side-planes showing the spectral profile of the first image row (2) and the last image column (3)

![image](https://user-images.githubusercontent.com/45030715/203725581-ff15ab54-4225-4c76-bc7b-bdb6c1ca5fdd.png)

The current extent of the cube is given by the map canvas, so that the user can interactively explore different visualizations of the cube.

In contrast to the existing **Image Cube** app, implemented by @jakimowb, the visualization uses a static 45° isometric perspective and is done inside a QGIS map canvas, so we don't need extra dependencies like OpenGL.

**Comment by janzandr** [comment]
The ROI for the cube can be a rectangle or a polygon:
![image](https://user-images.githubusercontent.com/45030715/224690168-716dd81b-ce0d-4763-bd9c-039207b9606b.png)

**Comment by janzandr** [comment]
The angle (alpha) and length of the vector along the side plane should be a free parameter:
![image](https://user-images.githubusercontent.com/45030715/224691229-c2d6c75a-e11a-4706-8436-2bd135ce20df.png)

**Comment by janzandr** [comment]
Could be implemented as a raster renderer that updates on-demand, or as an algorithm that precalculates the result for a single setting (vector angle and length) in full resolution.
A renderer would be better for interactive usage.

**Comment by jakimowb** [comment]
Could also be implemented as QgsPointCloudLayer to True 3D feeling

**Comment by janzandr** [comment]
Good point. But I'm not sure if a **QgsPointCloudLayer** is the right choice. Do you think that it can produce such a "crisp" visualization?:
![image](https://user-images.githubusercontent.com/45030715/224755991-abdf3f93-c8df-40ee-a79d-2e08289639ee.png)

Do you have an example image, that indicates, that it could work in principle?

I only found images like this one here, which does't give me much hope:
![image](https://user-images.githubusercontent.com/45030715/224758265-820c6e81-218a-47c1-8796-841385c5a8e2.png)

**Comment by janzandr** [comment]
Processing algorithm implemented. The default settings produce a 3D cube like known from ENVI Classic: 
![image](https://user-images.githubusercontent.com/45030715/226932896-244c66c9-7016-4ccd-a784-6b9d3a1301b8.png)

**Comment by janzandr** [comment]
With the delta x/y settings, the user can tilt the cube in different directions:
![image](https://user-images.githubusercontent.com/45030715/226934396-48dcb9fc-b68e-46f1-92ee-407cb0c932ac.png)

**Comment by janzandr** [comment]
Later we could add a more interactive GUI that uses the algorithm in the background and adds more gimmics, like spatial subsetting to a bounding box, or masking by a polygon.
