### ISSUE TITLE
Regrouping of processing algorithms

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#274]
The EnMAP-Box processing algorithms are ordered by group.
Some groups contain a single PA only, in other cases PAs seem to fit better into other groups.
Here are some recommendation to be discussed:

[PA.Names.xlsx](https://github.com/EnMAP-Box/enmapPro-box/files/10084761/PA.Names.xlsx)

**Comment by janzandr** [comment]
Link is not working:
![image](https://user-images.githubusercontent.com/45030715/203791363-3de91e0a-ef9d-4824-a942-23c61bac33bd.png)

**Comment by jakimowb** [comment]
It's a XLSX. You can download (context menu -> save as) it and open in Word / LibreOffice

**Comment by janzandr** [comment]
Also not working:
![image](https://user-images.githubusercontent.com/45030715/228549311-e48fe01b-cca2-4764-ac7a-c454828db0fd.png)

Anyways, I think this is better discussed in the EnMAP-Box Team Meeting. I'll create a Trello card.
