### ISSUE TITLE
implement EMIT L2A sensor product import algorithm

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#278]
Use testdata: \sensors\EMIT\EMIT_L2A\EMIT_L2A_RFL_001_20220815T042838_2222703_003.nc

EMIT L2 data is stored in a NetCDF container in sensor geometry, but the interleave is messed up. The column and band dimensions are wrongly ordered, so that when opening the product in QGIS, you are looking at the side of the image cube (similar to PRISMA data):
![qLUt0fpb9UWcJ2Ie](https://user-images.githubusercontent.com/45030715/204311926-7eb06802-1590-4191-abc3-1eba05fc7fda.png)

The product import algorithm should:

1. fix the interleave
2. use the geolocation arrays for proper spatial visualization
3. add center wavelength and FWHM information

![image](https://user-images.githubusercontent.com/45030715/204313358-8e8ebefc-b40c-42b6-8c28-3c0ebd1b720b.png)

![image](https://user-images.githubusercontent.com/45030715/204313417-1b4c500b-1ba3-47f7-9269-d8edabdd16e1.png)

**Comment by pgbrodrick** [comment]
Great to see this here!  I'll note that the GLT that's embedded in the netcdf can be used for faster spatial visualization.  There's an example in the reformatter:

https://github.com/emit-sds/emit-utils/blob/develop/emit_utils/reformat.py

Also - if there are metadata tags that I could add so that QGIS properly recognizes the interleave, please let me know and we'll try to add.

**Comment by janzandr** [comment]
> Also - if there are metadata tags that I could add so that QGIS properly recognizes the interleave, please let me know and we'll try to add.

Hi @pgbrodrick, I don't think that it is possible to change a netCDF metadata tag so that QGIS is reformatting the interleave of the data cube on-the-fly.
Data is stored inside the netCDF in the order: _samples x lines x bands_
QGIS is using the GDAL API for raster data IO, which assumes data to be stored as: _bands x lines x samples_

But I'm also not an expert on netCDF, so maybe it is possible (?).
Currently, I just rewrite the orthorectified data into a new raster file.

**Comment by janzandr** [comment]
Implemented processing algorithm
![image](https://user-images.githubusercontent.com/45030715/222458560-4e79ead3-5bbf-44df-a75c-efe788e4d20d.png)

**Comment by janzandr** [comment]
Integration into the main menu
![image](https://user-images.githubusercontent.com/45030715/222459447-c5b82518-2023-4ed5-9e28-79edcd040e40.png)

**Comment by janzandr** [comment]
Added drag&drop support, from system file browser to EnMAP-Box.

**Comment by janzandr** [comment]
@pgbrodrick noted (via email), that a bad band list metadata (_‘good_wavelengths’_ item in the _sensor_band_parameters_) is available. Bad bands have pixel values of -0.01:
1. It is proposed to properly use the bad band list metadata, so that bad bands can be hidden in the Z-profile plot.
![image](https://user-images.githubusercontent.com/45030715/222672825-70f25ee6-f183-4c49-a660-711ef2c69e04.png)

2. It is proposed to have a 'Skip bad bands' option inside the algorithm dialog.
3. We need to download a new EMIT L2A product for testing. Our current product EMIT_L2A_RFL_001_20220815T042838_2222703_003.nc, which is an early sample scene, is missing the bad band list metadata.
