### ISSUE TITLE
Read and apply hdr field "default bands" if present for initial color composite display

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#28]
hdr files may have a useful field
default bands = {170, 3, 86}

which states those bands to be used for initial color composite display.
It would be great if EnMapBox could read and apply this information whenever is present.

**Comment by janzandr** [comment]
Hi Agus, I think that is already implemented by @jakimowb .
![image](https://user-images.githubusercontent.com/45030715/189079908-9f1cd5c3-aabf-440b-b420-770f32e5684e.png)

If that is not loading the 170-3-86 bands as RGB in your case, I would concider it a bug.
Please check that.

**Comment by aloboa** [comment]
Cannot reproduce this problem now, maybe it was a consequence of #27. 
Note though the bands are shifted by 1:
![image](https://user-images.githubusercontent.com/6074054/189192737-dd032b6b-31de-4bf0-87b1-e5128b0965fa.png)

**Comment by jakimowb** [comment]
Because many more users may benefit from, this issue should be better fixed in GDAL instead of the EnMAP-Box only. I therefore created this issue: https://github.com/OSGeo/gdal/issues/6339

**Comment by jakimowb** [comment]
@aloboa please note that the "default bands" could later on be overwritten by individual layer styles (*.qml).

**Comment by janzandr** [comment]
@jakimowb wasn't that the bug?:
![image](https://user-images.githubusercontent.com/45030715/189486085-df015fc2-3dc4-4e01-a38d-332b9d83dfab.png)

**Comment by jakimowb** [comment]
It's just a missing feature, known from another software. 
Just because the EnMAP-Box or other software like SNAP does not evaluate it, they are not buggy.

**Comment by janzandr** [comment]
The feature is already implemented inside the EnMAP-Box:
![image](https://user-images.githubusercontent.com/45030715/189486834-0e798751-8e6d-4edb-a8fa-f905fd16d2c5.png)

The bug is, that the bands are shifted by 1. That is at least how I understand the reported behaviour.
So, instead of band number 10, you set band number 9.

**Comment by jakimowb** [comment]
Your screenshot is a bit missleading, as it shows the enmap_berlin.bsq image which has a *.qml defined.
I think the main question is what should be define the "default" renderer. QML (in line with QGIS concepts) or *.hdr?
Relates to our discussion in https://github.com/EnMAP-Box/enmap-box/discussions/47

Anyway, thanks for the reported band number shift.

**Comment by janzandr** [comment]
Oh, I really thought, that **Default Colors** refers to the ENVI metadata.
Sorry, the Default Style from the QML makes also sense.

**Comment by jakimowb** [comment]
@aloboa FYI, Event Rouault has been so kind to implement the GDAL support for RGB band definitions (like `default = {5, 3, 1}`)
see https://github.com/OSGeo/gdal/pull/6353

**Comment by jakimowb** [comment]
closed via https://github.com/OSGeo/gdal/pull/6353

becomes effective with next QGIS version (tested with QGIS version | 3.27.0-Master | QGIS code revision | 95e00c50d2)
