### ISSUE TITLE
PRISMA L2C Data import in coordinate reference system

### ISSUE THREAD

**Issue by KhalilM94** [EnMAP-Box/enmap-box#282]
Isn't supposed for PRISMA L2C product import from HE5 file to QGIS/GDAL to be done in the proper coordinate reference system (similar to L2D)?
![Screenshot 2022-12-02 at 10 47 43 PM](https://user-images.githubusercontent.com/39563541/205395890-01f3fff5-f7d1-4e35-b4df-cdee39cb59f8.png)

**Comment by janzandr** [comment]
No, L2C is in instrument geometry:
![image](https://user-images.githubusercontent.com/45030715/205886316-f619fefc-12f8-4e50-8076-f8d3009f55b3.png)

**Comment by KhalilM94** [comment]
the L2C product comes with a geolocation raster field layer though. It only puts another step to properly project it in place. Couldn't this feature be added to l2c as well(optionally set)? (I've seen it implemented in the prismaread library in R).

**Comment by janzandr** [comment]
Yes, you can do this. It is an additional step. Use the "Geolocate raster layer" algorithm:
![image](https://user-images.githubusercontent.com/45030715/205891238-8a005a8b-7a4d-4df9-9195-688bab962fe5.png)

And there is a reason why we don't integrate it into the import algorithm directly. You should use the L2D raster as the target grid. This way your L2C pixel exactly match the L2D pixel!
![image](https://user-images.githubusercontent.com/45030715/205892921-b5ddc916-4048-416b-af9f-e72d46bcb438.png)

**Comment by janzandr** [comment]
BTW - if you would like to combine both algorithms into one, you could use the QGIS Model Designer:
![image](https://user-images.githubusercontent.com/45030715/205908778-084972e8-ddd1-45dc-988c-6f682c98f09a.png)

**Comment by KhalilM94** [comment]
YESS! and I wrapped up the entire process into a python script.
Thank you for the suggestion!
