### ISSUE TITLE
[Data Sources] Opening vector sources with multiple layers (e.g. GPKG)

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#286]
Currently when opening vector sources containing multiple layers only the first one will be opened. 
QGIS shows a selection dialog to choose which layer to open:

![grafik](https://user-images.githubusercontent.com/15610561/205872694-03e4071b-20c1-47ac-99c7-196e68e04d5b.png)

Is that something we should support?

**Comment by janzandr** [comment]
I would say that this is a bug.

**Comment by jakimowb** [comment]
Relates to https://github.com/qgis/QGIS-Enhancement-Proposals/issues/216

QgsSublayersDialog is deprecated. Waiting for move of QgsProviderSublayersDialog from src/apps to src/gui (QGIS 3.19 https://github.com/qgis/QGIS/commit/caadcb42e8de86fcc74fcfacf9561130492c0085)
