### ISSUE TITLE
install instructions fail on OSGeo4W Shell

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#3]
When following the instructions given here: https://github.com/janzandr/enmap-box#tldr

![image](https://user-images.githubusercontent.com/45030715/187849585-d756f58f-6228-43ba-9afe-68dcacdf9a7c.png)

**Comment by janzandr** [comment]
Still not working in OSGeo4W Shell.

**Comment by janzandr** [comment]
I'm sure I could fix that problem if I want to, but I just played a dumb user following the instructions.
At this point, a dumb user, just following the instructions will fail:
![image](https://user-images.githubusercontent.com/45030715/188116228-1f1a0749-832f-49ab-a67f-4e33fa1de348.png)

**Comment by jakimowb** [comment]
It's already written there: "allows to run ... PyQGIS", as well how to ensure that (via link), see below.

**Comment by janzandr** [comment]
A user following the intructions will run into this error.
The **"allows to run ... PyQGIS"** part is way down in another subsection of the document.
