### ISSUE TITLE
Import USGS ASCII Speclib

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#302]
Implement a SpectralLibraryIO + QgsProcessingAlgorithm to import USGS spectral libraries of type:

* [ ] #303
* [ ] SPECPR (profiles + photos): https://www.sciencebase.gov/catalog/item/586e8bf2e4b0f5ce109fcca2
* [ ] QgsProcessingAlgorithm for bulk import of folder structure (including Photo BLOBs)

related to #299

**Comment by janzandr** [comment]
Oh no, SPECPR reader is in IDL/ENVI:
https://www.usgs.gov/spectroscopy-lab/software-specpr-files

Couldn't find a Python implementation yet.

**Comment by janzandr** [comment]
Python API for SPECPR format:
https://formats.kaitai.io/specpr/
https://formats.kaitai.io/specpr/src/python/specpr.py

**Comment by janzandr** [comment]
Done
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/9b5b5f57-7f92-4efc-b032-6b201728c7a1)
