### ISSUE TITLE
[Spectral View] Save Edits is messing up attribute table values

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#315]
_Reported by Sebastian van der Linden._

![animation26](https://user-images.githubusercontent.com/45030715/210976387-7c7dadc7-05ce-4073-b836-4f7f1376f70c.gif)

**Comment by jakimowb** [comment]
Not a bug, same behaviour as in QGIS.
1. Cell edits need to be confirmed first by leaving the edit context. I.e. the mouse cursor needs to leave the "b" cell, e.g. by clicking on the next. If not, the modifications are not stored to the QgsVectorLayers modification store and will not be saved when pressing the "Save" button.
2. Saveing the edits just applies the "name" columns sort order, and NULL (see 1) is ordered before "a".

**Comment by jakimowb** [comment]
The layer needs to be "very new" and not have reccorded any modifcations before (which seems to be the case in your example):

See here:
![QGIS_tempvalues](https://user-images.githubusercontent.com/1404870/218425215-ddd6ab7c-51e5-439e-81ff-8e9a36048126.gif)

**Comment by jakimowb** [comment]
The solution to click into another cell before saving the modifications works for me.

**Comment by janzandr** [comment]
> The layer needs to be "very new" and not have reccorded any modifcations before (which seems to be the case in your example)

Thanks @jakimowb, makes sense. So it is a QGIS bug.
