### ISSUE TITLE
enmapboxtestdata.SensorProducts problems

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#318]
The `enmapboxtestdata.SensorProducts` class encloses other sensor-specific classes that provide access to large big example datasets.
It is expected that the required datasets are located in a `root ` directory, defined as:
  ```
  # external sensor products
  # - let's have some developer-dependent default locations
  root = {
      'Andreas@PC-21-0602': r'd:\data\sensors'
  }.get(os.getlogin() + '@' + platform.node())
  
  # - check environment variable
  if root is None:
      root = os.environ.get('ENMAPBOX_SENSOR_PRODUCT_ROOT')
  
  # - fall back to SAN EnMAP server
  if root is None:
      root = r'\\141.20.140.91\san\_EnMAP\Rohdaten\EnmapBoxExternalSensorProducts'
  ```

We need to test the EnMAP-Box with "real large" data. The `SensorProducts` is helpful class to write tests for that.
However, as implemented now, there are some problems:

- `root ` is a private folder. It cannot be used in unittests that run, e.g. on github / any other none-local pipeline, many developers may never get access to. This needs to be well documented. Unit tests that use SensorProduct, e.g. calling `SensorProduct.Landsat.LC09_L1`, should be skipped in case 'root' is not accessible.
- `141.20.140.91\san\_EnMAP\Rohdaten\EnmapBoxExternalSensorProducts` does not exist
- in case it does not exist, `root` should not be defined as string variable at module level. As now it crashes `test_exampledata.test_tests_testdata()`, which checks module level paths like `from enmapboxtestdata  import landcover_polygon_1m` exists in the repository (for convineance, will rename it test to `test_enmapboxtestdata`).

I recommend to move the entire handling related to the ENMAPBOX_SENSOR_PRODUCT_ROOT into the SensorProducts class. 
In addition it could implement a static function that checks if the data folder is available and a dependent unit test can be run:

```
@unittest.skipIf(SensorProducts.available(), 'Test requires ENMAPBOX_SENSOR_PRODUCT_ROOT folder with sensor data')
    def test_with_enmapbox(self):
    ...
```

**Comment by janzandr** [comment]
As discussed with @jakimowb:

1. Root folder is now derived by a function:
```
def sensororProductsRoot() -> Optional[str]:
    # - let's have some developer-dependent default locations
    root = {
        'Andreas@PC-21-0602': r'd:\data\sensors'
    }.get(os.getlogin() + '@' + platform.node())

    # - check environment variable
    if root is None:
        root = os.environ.get('ENMAPBOX_SENSOR_PRODUCT_ROOT')

    return root
```
2. We don't fall back to the SAN location as root.
3. Unittets can be skipped if sensororProductsRoot() returns None
