### ISSUE TITLE
Impossible to add created vector to a new/existing map via data source context menu

### ISSUE THREAD

**Issue by vprint** [EnMAP-Box/enmap-box#32]
Hello,

It is not possible to add created vector to a new/existing map via data source context menu. You can still drop the vector into a map however

Reproduction : 
1) Project/Create datasource/New GeoPackage layer
2) Fill up mendatory parameters and click ok
3) Right click on the new file in Data source panels and check if option add "Open in new map" or "Open in existing map" is present

<img width="351" alt="image" src="https://user-images.githubusercontent.com/42189444/189326102-a9652455-fc4f-400d-99b7-a72958fd4f6e.png">

**Comment by jakimowb** [comment]
@vprint thank you for your report
