### ISSUE TITLE
Predefined windows and settings

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#320]
In order not to waste time every time we open an image,  we would like to:
* Get EnMap open as I open QGIS,
Then, once  I drop an image to Map#1, I would like to have:
Map#1
buttons on: 
* identify a cursor location and collect pixel values...
* identify pixel profiles and show them in...

Have Window Spectral Library open
with these buttons on: 
* Show profile plot on
* “Shows the visualization settings” on,
*  then on “AddRsterLayerRenderer”, have automatically selected the image that was dropped on Map#1

Is there a way to save these settings? We often have to do this for inspecting scanned hyperspectral images and
are actually hating to repeat these settings.

**Comment by janzandr** [comment]
Hi @aloboa, 
thanks for the suggestions. We recently introduced a concept for storing EnMAP-Box Project Settings: #201 
Now we need to implement it for the different components of the EnMAP-Box.
For **Data Views** (e.g. Map Views and Spectral Views) we have a seperated issue here, where we can discuss this further: #308
