### ISSUE TITLE
Attribute form doesn't appears on EnMAP-Box map

### ISSUE THREAD

**Issue by vprint** [EnMAP-Box/enmap-box#33]
Hello,

Attribute form doesn't appears when digitizing new features on EnMAP-Box map. This is a minor problem but form can be very usefull to draw training classification polygons

Reproduction :
1) Create new layers (Project/Create Data Source)
2) Create a "type" field (string) and click "Ok"
3) Drop the vector in a new map
4) Right clik / layers properties / Attributes Form
5) Create new form on "type" field (youcan refer to the following screen for an exemple) and click on "Apply"
6) Start digitizing new features in EnMAP-Box map
7) Form doesn't  appears

<img width="902" alt="image" src="https://user-images.githubusercontent.com/42189444/189330740-08d503bf-347b-4afb-83c5-383648518217.png">

**Comment by jakimowb** [comment]
@vprint Thanks for your report. 

I changed a couple of lines in our [QgsFeatureAction reimplementation](https://github.com/EnMAP-Box/qgispluginsupport/blob/master/qps/maptools.py ) of https://github.com/qgis/QGIS/blob/master/src/app/qgsfeatureaction.cpp

It now uses the settings for default behavior from [QgsSettingsRegistryCore](https://api.qgis.org/api/classQgsSettingsRegistryCore.html), which was introduced with QGIS 3.20

In the QGIS Settings > Options your can control if the attribute dialog appears or not and if previous entered values should be shown again
![image](https://user-images.githubusercontent.com/1404870/189473472-d867e085-c7ab-4750-8f37-7a8543ba2bf2.png)
