### ISSUE TITLE
[Sensor data import] EnMAP L1C data import fails 

### ISSUE THREAD

**Issue by Satalert** [EnMAP-Box/enmap-box#338]
I am using QGIS 3.28 and EnMAP-Box 3.11. Trying to import an EnMAP L1C data packet (produced July 19, 2022). on Ubuntu 22.10 
Two issues: 
EnMAP-Box fails to find the metadata file in the EnMAP data directory due to the file extension being .XML in capitals. Changing the extension to .xml fixes this issue. 

Once found, EnMAPBox claims this is an invalid EnMAP L1C product (it was openable with version 3.9 of EnMAP-box)

Error: 
QGIS version: 3.28.2-Firenze
QGIS code revision: b47e00ba60
Qt version: 5.15.6
Python version: 3.10.7
GDAL version: 3.5.1
GEOS version: 3.11.0-CAPI-1.17.0
PROJ version: Rel. 9.0.1, June 15th, 2022
Algorithm started at: 2023-01-24T20:15:40
Algorithm 'Import EnMAP L1C product' starting…
Input parameters:
{ 'file' : '/home/dan/aaPython/Observer/enmap/dims_op_oc_oc-en_700323207_1/ENMAP.HSI.L1C/ENMAP-HSI-L1CDT0000001715_01-2022-07-19T00:55:01.967_2022-11-08T15:54:04/ENMAP01-____L1C-DT0000001715_20220719T005501Z_001_V010110_20221108T103650Z/ENMAP01-____L1C-DT0000001715_20220719T005501Z_001_V010110_20221108T103650Z-METADATA.xml', 'outputEnmapL1CRaster' : 'TEMPORARY_OUTPUT' }

not a valid EnMAP L1C product: /home/dan/aaPython/Observer/enmap/dims_op_oc_oc-en_700323207_1/ENMAP.HSI.L1C/ENMAP-HSI-L1CDT0000001715_01-2022-07-19T00:55:01.967_2022-11-08T15:54:04/ENMAP01-____L1C-DT0000001715_20220719T005501Z_001_V010110_20221108T103650Z/ENMAP01-____L1C-DT0000001715_20220719T005501Z_001_V010110_20221108T103650Z-METADATA.xml
Execution failed after 0.07 seconds

Loading resulting layers
Algorithm 'Import EnMAP L1C product' finished

Same issue occurs when attempting to load an EnMAP L1B product. 

I am able to drag the metadata file (with .XML extension, but not with .xml) into EnMAP-Box and successfully load the raster. 

Thanks

**Comment by janzandr** [comment]
> EnMAP-Box fails to find the metadata file in the EnMAP data directory due to the file extension being .XML in capitals. Changing the extension to .xml fixes this issue.

Interesting, all products I've seen have upper case .XML extentions. I will fix this.

**Comment by janzandr** [comment]
On Windows systems, we had a similar problem, that was caused by the very long filename:
/home/dan/aaPython/Observer/enmap/dims_op_oc_oc-en_700323207_1/ENMAP.HSI.L1C/ENMAP-HSI-L1CDT0000001715_01-2022-07-19T00:55:01.967_2022-11-08T15:54:04/ENMAP01-____L1C-DT0000001715_20220719T005501Z_001_V010110_20221108T103650Z/ENMAP01-____L1C-DT0000001715_20220719T005501Z_001_V010110_20221108T103650Z-METADATA.xml

Please try to copy the product to a shorter path, e.g.
/home/dan/aaPython/Observer/enmap/ENMAP01-____L1C-DT0000001715_20220719T005501Z_001_V010110_20221108T103650Z-METADATA.xml

If that isn't solving the problem, please share the product (you may send an email for that to andreas.janz@geo.hu-berlin.de)

**Comment by Satalert** [comment]
Thanks for the fast reply. I just tried it with a shorter filepath and I couldn't test it properly as it was only recognising the metadata file with lower case extension, which fails immediately. There must be a check for an upper case extension in EnMAP-Box when loading data, or something? The files are the same apart from the extension.

**Comment by janzandr** [comment]
Hi @Satalert, can you please share one of your scenes for testing. I downloaded some scenes, but I always have upper case file extensions.

**Comment by Satalert** [comment]
Hi Andreas, 



Yes the metadata file has an upper case extension, that is how it should be. The issue I'm raising is that EnMAP Box on Ubuntu (QGIS 3.22, EnMAP-Box 3.11.1) is looking for a lower-case metadata file extension, and therefore cannot find the file in the load window. 



I can load an EnMAP package by dragging/dropping a metadata file into the main EnMAP-Box window, but if I go to Project > Load Product > EnMAP L1C > Metadata file ... > the file list is empty, because it's looking for a lowercase extension when it should be looking for an uppercase one. I tested this by renaming the metadata file to .xml from .XML and it showed up in the folder list, but still couldn't load this package because EnMAP-Box considers a metadata file with a lowercase extension to be corrupted/invalid. 



Hope this helps. 












---- On Tue, 07 Mar 2023 03:17:26 +1100 Andreas Janz ***@***.***> wrote ---





Hi https://github.com/Satalert, can you please share one of your scenes for testing. I downloaded some scenes, but I always have upper case file extensions.

**Comment by janzandr** [comment]
Oh ok, now I understand. 
We are talking about the file selection dialog here:
![image](https://user-images.githubusercontent.com/45030715/223355517-f948298d-4428-4787-ba6d-fdabb92af4d7.png)
As you can see, under Windows, upper and lower extensions are shown.
Anyways, I will set the extension filter to an uppercase XML and that should solve the problem under Linux.
Thanks!
