### ISSUE TITLE
[Data source tree] GEE Data Catalog Plugin color composition doesn't work

### ISSUE THREAD

**Issue by vprint** [EnMAP-Box/enmap-box#34]
Hello,

Opening an image with GEE Data Catalog Plugin color composition doesn't work and always show the same color composition

Reproduction : 
1) Open a sentinel-2 image / or EnMAP demo data
2) Right click on image in data source panel and select "Open in new map"/"GEE Data Catalog Plugin"and select "Natural colors"
3) Image is opened in a new map but with the following bands : red: band 151, green: band 62, blue: band 21
4) Try to use some other GEE Data Catalog Plugin colors compositions : the same bands will be used

<img width="689" alt="image" src="https://user-images.githubusercontent.com/42189444/189331456-0355a272-b2af-45bc-8220-210550e3266e.png">

**Comment by janzandr** [comment]
Confirmed.
As a workaround, use the RasterLayerStyling panel:
![image](https://user-images.githubusercontent.com/45030715/189334600-57a0060d-7d9b-4146-9cf2-4ad7a596d9cb.png)

**Comment by vprint** [comment]
Thank you, this workaround works

**Comment by vprint** [comment]
Thank you, the modification works fine.

However "Raster Layer Styling Panel" show GEE Colors compositions for EnMAP data but not for Sentinel-2.

**Comment by janzandr** [comment]
How do you open the Sentinel-2 product?
When using the import algo, proper wavelength information is added:
![image](https://user-images.githubusercontent.com/45030715/189817863-57014c29-fa19-457d-8724-efdb39e8daae.png)

**Comment by janzandr** [comment]
To streamline the usage of Sentinel-2 products inside EnMAP-Box, dropping the MTD_MSIL2A.xml into the MapView area should automatically open the Import dialog.
![image](https://user-images.githubusercontent.com/45030715/189818971-fd8f9959-9847-46b7-9d87-e09f0ba29b5c.png)

Unfortunately, the not so useful "Select Sub-Datasets" dialog is shown instead, which is not properly dealing with wavelength information:
![image](https://user-images.githubusercontent.com/45030715/189819258-8718332b-a0a4-4284-ad1b-22312649fb90.png)

**Comment by janzandr** [comment]
Follow-up issue #42

**Comment by vprint** [comment]
Hello i just tried dev version 3.11 and the problem is solved for the raster layer styling panel

However for 3.10 version here is a gif description of the problem :

![bug_gee](https://user-images.githubusercontent.com/42189444/189875729-19ae6199-2029-409d-98be-79626b3b4859.gif)

**Comment by janzandr** [comment]
That was a bug and is fixed now.
