### ISSUE TITLE
Line plots in the spectral library panel

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#354]
Probably, I am overseeing something, but how can I change the figure style from a point plot to a solid line plot in the Spectral Library panel? Sometimes, line plots are useful to inspect, e.g., spectral spikes.

![grafik](https://user-images.githubusercontent.com/16669114/214882348-9c46b69d-2164-43d1-a73a-ece74e8419bb.png)

**Comment by danschef** [comment]
Ok, I found it:
![grafik](https://user-images.githubusercontent.com/16669114/214883694-b7bbc868-9850-4ff7-8b93-47ee80907b33.png)

Probably, the "No Pen" in the "Line" row confused me:
![grafik](https://user-images.githubusercontent.com/16669114/214883871-63f64eb1-3a9a-4be0-b3ab-5627ccfd5aa0.png)

Would be more intuitive to have "No Line" there.

**Comment by danschef** [comment]
Ok, this helps to add a line in the current plot. However, as soon as I move the crosshair to another position of the image, the line signature is gone and I am back at a point plot. This should not happen.

**Comment by janzandr** [comment]
Hi @danschef, can you show this in an animated GIF?

**Comment by danschef** [comment]
It should be very easy to reproduce. Just load some hyperspectral data, start the Spectral Library panel, activate the line plot and move the crosshair.

**Comment by janzandr** [comment]
Hi @danschef, I can't reproduce this. please show an animated GIF.

**Comment by jakimowb** [comment]
@danschef you can set the appearence of temporal / current profiles in the Spectral Profile source panel

![grafik](https://user-images.githubusercontent.com/1404870/220378023-eb1153c9-e8c8-4d25-8b95-5f5f3b3fc987.png)

This allows you to pre-define different style for different profile sources or sampling methods which all are to be loaded into the spectral library viewer:

![grafik](https://user-images.githubusercontent.com/1404870/220378752-2b6bfa42-bb51-45a0-b186-c728fab12cee.png)

These style settings apply for "current" / "temporary" profiles only. After adding them into the spectral library ( +button) they will as defined for other library profiles:

![grafik](https://user-images.githubusercontent.com/1404870/220379741-16f48c7e-7272-4298-b44e-5ef54e80f93a.png)

(The `@symbol_color` expression make them use the same color as in the settings for layer geometries. You can use other QgsExpression to define the line colors, e.g. based on attribute values.)

**Comment by danschef** [comment]
Thanks @jakimowb! I tested it again on Windows and Linux.

> However, as soon as I move the crosshair to another position of the image, the line signature is gone and I am back at a point plot.

This works now as expected with the EnMAP-Box 3.12 alpha 8. The only thing to be improved is the default string at "Line" in this screenshot:

![grafik](https://user-images.githubusercontent.com/16669114/221718077-a2a6e6b2-6053-4f88-8085-08f19b972665.png)

The default is "No Pen" or "Kein Stift" but "No Line" would be more intuitive.

**Comment by jakimowb** [comment]
Your're right, but the [QgsPenStyleComboBox](https://www.qgis.com/api/classQgsPenStyleComboBox.html) is part of the QGIS API.

**Comment by danschef** [comment]
Ok I see. Thanks.

**Comment by jakimowb** [comment]
It just requires a small change in qgspenstylecombobox.cpp line 32 - and +35 *.ts files that "No Pen" into other languages.

**Comment by danschef** [comment]
Is this a file included in the EnMAP-Box repository? I understood that this a change in the QGIS repo would be needed.

**Comment by janzandr** [comment]
Technically, we could change the "No Pen" string inside the widget. It's part of our code.
As I understand @jakimowb: we should keep it as is, because the option is also named "No Pen" inside the PyQtGrapth API.
So it is a pure design decision to keep it as is. Right @jakimowb?

**Comment by janzandr** [comment]
> It just requires a small change in qgspenstylecombobox.cpp line 32 - and +35 *.ts files that "No Pen" into other languages.

Ah ok, you are really using a QGS widget. Sorry.

**Comment by jakimowb** [comment]
@danschef FYI: https://github.com/qgis/QGIS/pull/52048
