### ISSUE TITLE
Installation is missing h5py

### ISSUE THREAD

**Issue by jsta** [EnMAP-Box/enmap-box#355]
After following the instructions at: https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation.html#usr-installation
I open up enmap-box and it says I'm missing `h5py` should that be added to [requirements.txt](../blob/main/requirements.txt)?

**Comment by janzandr** [comment]
If you are under Windows, you need to use OSGeo4W to install h5py.
Please see this issue for details: https://bitbucket.org/hu-geomatics/enmap-box/issues/868/dll-importerror-for-h5py

**Comment by janzandr** [comment]
Hi @jsta, could you solve it? Please re-open if required.
