### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources' 

### ISSUE THREAD

**Issue by smblnts21** [EnMAP-Box/enmap-box#357]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexander/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 5, in 
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
Versión de Python: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] 
Versión de QGIS: 3.22.16-Białowieża Białowieża, exported

**Comment by jakimowb** [comment]
This seems to be a problem of the Google Earth engine plugin. Which version do you have installed? According to my QGIS Plugin installer, the most-recent version is 0.0.6
![grafik](https://user-images.githubusercontent.com/1404870/218422506-dcf215a3-bd62-4a1a-8747-37d3a4dec038.png)

**Comment by smblnts21** [comment]
> This seems to be a problem of the Google Earth engine plugin. Which version do you have installed? According to my QGIS Plugin installer, the most-recent version is 0.0.6 ![grafik](https://user-images.githubusercontent.com/1404870/218422506-dcf215a3-bd62-4a1a-8747-37d3a4dec038.png)
![Screenshot_20230214_074159](https://user-images.githubusercontent.com/62901775/218742075-a7b00ae6-4668-4866-92e7-30119a0088c5.png)

**Comment by smblnts21** [comment]
the same version is installed

**Comment by janzandr** [comment]
Haven't yet testet GEE v0.0.6. I will check this out.

**Comment by thielfab** [comment]
The reported QGIS version is 3.22.16, it should be >=3.24 in order for the EnMAP-Box to work, right?

**Comment by janzandr** [comment]
Yes, v3.11 requires QGIS v3.24: https://plugins.qgis.org/plugins/enmapboxplugin/

**Comment by janzandr** [comment]
@smblnts21 please install a recent QGIS version (e,g, the QGIS 3.28 long term release) and test again.
If the problem persist, just reopen this issue.
