### ISSUE TITLE
Moving Spectral Library view causes AttributeError: 'NoneType' object has no attribute 'moveDock' 

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#375]
In the EnMAP-Box 3.12alpha8, I opened 2 map views + the spectral library view. The two map windows were linked (center + scale): 

![grafik](https://user-images.githubusercontent.com/16669114/221834223-6052b287-9025-49a3-8da7-044df41d54fe.png)

Then I moved the spectral library view to arrange the windows differently and the EnMAP-Box crashed with the following AttributeError:

```python
AttributeError: 'NoneType' object has no attribute 'moveDock' 
Traceback (most recent call last):
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph\pyqtgraph\dockarea\Dock.py", line 264, in dropEvent
    DockDrop.dropEvent(self, *args)
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph\pyqtgraph\dockarea\DockDrop.py", line 83, in dropEvent
    self.area.moveDock(ev.source(), area, self)
AttributeError: 'NoneType' object has no attribute 'moveDock'
```

Python-Version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.28.3-Firenze Firenze, exported 

QGIS and the EnMAP-Box are installed into the same MambaForge environment, which I updated today.

**Comment by danschef** [comment]
Not sure if it has something to do with the OS but I could not reproduce this on Linux now (error occurred on Windows).

**Comment by janzandr** [comment]
Maybe you haven't restarted QGIS after installation?

**Comment by danschef** [comment]
I think I restarted QGIS after the update but it seems like at the moment, I cannot reproduce it.

**Comment by janzandr** [comment]
Ok, so I would suggest to close this for now.

**Comment by danschef** [comment]
Ah, it looks like I could reproduce it again on Linux by clicking on the "Float Window" button of the Spectral Profile View:

![grafik](https://user-images.githubusercontent.com/16669114/222761975-73e6f236-5c43-4664-a830-44166bc13456.png)

I guess this was also the problem that @jakimowb had in the workshop today.

**Comment by danschef** [comment]
No, it seems like this triggers a different issue. I opened https://github.com/EnMAP-Box/enmap-box/issues/379.
