### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dataSources'

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#377]
I just got this error when doing a right-click on a layer opened in the `data views` panel:

```python
AttributeError: 'NoneType' object has no attribute 'dataSources' 
Traceback (most recent call last):
  File "C:\Users/Daniel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\dataviews\dockmanager.py", line 1587, in createContextMenu
    self.addRasterLayerMenuItems(node, menu)
  File "C:\Users/Daniel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\dataviews\dockmanager.py", line 1799, in addRasterLayerMenuItems
    for modelDataSource in enmapBox.dataSources('MODEL', False):
AttributeError: 'NoneType' object has no attribute 'dataSources'
```

The EnMAP-Box keeps opened but now a right-click on any layer in the "data views" panel does not have an effect anymore.

I am using EnMAP-Box 3.12.alpha9 within QGIS 3.28.3.

**Comment by janzandr** [comment]
Hi @danschef, is this a reproducable error?
I just started the EnMAP-Box, loaded the testdata and right-click on a layer without a problem:
![image](https://user-images.githubusercontent.com/45030715/222743635-ba965a8b-a426-4bff-b0b1-b94d05f17a2e.png)

Please restart QGIS and EnMAP-Box and show a screenshot of your Data Sources/Views setup, which reproduces the error.

**Comment by danschef** [comment]
Well, here is a screenshot but I guess it does not help much:

![grafik](https://user-images.githubusercontent.com/16669114/222748596-b854ba1a-b527-46a1-92c2-cbc19c328dc5.png)

When I restart the EnMAP-Box, I cannot reproduce it. However, my hope was rather that you might have a look at the code and and probably have an idea why the `enmapBox` variable can get `None` at this point in the code. Probably, there is also a way to catch that and raise a more useful error message,

**Comment by janzandr** [comment]
The **enmapBox** variable shouldn't be **None**, if the EnMAP-Box GUI is running. So, it's unclear why this happens.
Anyways, why can't you reproduce the error?

**Comment by danschef** [comment]
I guess because it was not exactly the right-click which triggered the problem but something else.

**Comment by janzandr** [comment]
Ok, maybe @jakimowb has an idea. Otherwise I would suggest to close it for now.
