### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'floatDock'

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#379]
Clicking on the Float Window button of the Spectral Profile View on Linux triggers the following error (EnMAP-Box 3.12alpha9):

```python
Traceback (most recent call last):
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph\pyqtgraph\dockarea\Dock.py", line 210, in float
    self.area.floatDock(self)
AttributeError: 'NoneType' object has no attribute 'floatDock'
```

![grafik](https://user-images.githubusercontent.com/16669114/222763031-ee63bd34-100c-4e55-a043-1cbd45ad0dfc.png)

@jakimowb

**Comment by jakimowb** [comment]
@danschef seems to be fixed. I cannot reproduce it on Ubuntu 22.04.2, mamba forge QGIS 3.30.
Please re-open if the error occurs agains.
