### ISSUE TITLE
Can't change Band Rendering in Layer properties

### ISSUE THREAD

**Issue by EO-Science** [EnMAP-Box/enmap-box#385]
Hi developers,

I installed the EnMap Box plugin in QGIS 3.22.16. I opened the plugin and loaded the sample data provided. Experimenting with the data I realised that I'm not able to customize band rendering of the .bsq files. Whenever I chose a different band combination in the symbology tab of the layer properties, the setting changes back to the default as soon as I click Apply or OK.

I'm not sure if this is a bug or if I missed something.

Best regards,
Lena

**Comment by janzandr** [comment]
I think I remember this issue. Should be already fixed in the current EnMAP-Box v3.11.
Please install a recent QGIS version (e.g. QGIS 3.28 long term release), install the latest EnMAP-Box version, and try again.
If the problem still exists, just reopen this issue.
