### ISSUE TITLE
Problems with Spectral Viewer

### ISSUE THREAD

**Issue by katja-berger** [EnMAP-Box/enmap-box#392]
![Error_spectral-lib2023-03-14 210158](https://user-images.githubusercontent.com/110786369/225123097-c6bb15f0-9870-43fe-8e13-881c3cadc5dc.png)
![image](https://user-images.githubusercontent.com/110786369/225123326-59f60460-48ed-49c5-b217-ffee5a5581f1.png)
Hi, it seems impossible to use the spectral library viewer, neither with Sentinel-2 nor with EnMAP scenes. What can I do? Thanks!!

**Comment by Maesiu** [comment]
Can confirm & reproduce this error

![grafik](https://user-images.githubusercontent.com/30070733/225233815-a52f1d91-5c9c-490f-81ee-3a0ba481018e.png)

**Comment by janzandr** [comment]
Hi @katja-berger, we are currently developing on the QGIS 3.28 LTR only. Probably a bug related to the new QGIS 3.30.0 RC version. We will check it out. Thanks, Andreas.

**Comment by janzandr** [comment]
Confirmed on QGIS 3.30.0

**Comment by janzandr** [comment]
Workaround: if you can, also install the QGIS LTR in your OSGeo4W environment.
