### ISSUE TITLE
[Spectral View] raster layer renderer bar not shown for SingleBandPseudocolor renderer

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#394]
![image](https://user-images.githubusercontent.com/45030715/225728609-ac3f6c2f-7a53-4f2c-9f27-08e5d179a838.png)

**Comment by jakimowb** [comment]
Which QGIS do you use?

**Comment by janzandr** [comment]
QGIS LTR 3.28.4
