### ISSUE TITLE
Application path not initialized

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#4]
Starting the EnMAP-Box from shell by

```bash
cd enmap-box-repository
python enmap-box
```
print 5x a `Application path not initialized` warning before the QgsApplication is started.

**Comment by janzandr** [comment]
Under OSGeo4W Shell you have this error:
![image](https://user-images.githubusercontent.com/45030715/188104146-10d40600-e4d2-4793-8d1d-cb3c587a0aa4.png)

**Comment by janzandr** [comment]
Ah sorry, I see, the OSGeoShell bug is already solved in #3 .

**Comment by jakimowb** [comment]
Indeed, you Screenshot is not related to this issue at all ;-)

**Comment by jakimowb** [comment]
I rekaveled this to "enhancement". This is a log message appears only if Imports are made from the processing plugin before the QgsApplication has been initialized. 
So far not a problem.

**Comment by jakimowb** [comment]
The message "Application path not initialized" will always be shown if something is imported from the "processing" module before a QgsApplication has been initialized. This is only the case in development environments, but not if started from QGIS.
