### ISSUE TITLE
version in splash screen not updating with actual version

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#40]
Current dev version is 3.11:
![image](https://user-images.githubusercontent.com/45030715/189622893-686debac-c38d-42bd-9ba5-f2568eb1c241.png)

splash screen still shows 3.10
![image](https://user-images.githubusercontent.com/45030715/189623289-477f17d2-bd97-4f55-8d97-eaf85df5d668.png)

**Comment by jakimowb** [comment]
You have to increase the number in the screenshot.svg. 
And it has to look nice!

**Comment by jakimowb** [comment]
I removed the bug label. For the resons mentioned above, it has never been an automatized feature which may be considered as "broken".
