### ISSUE TITLE
Transform raster layer use 4 bands instead of 12 for sentinel-2

### ISSUE THREAD

**Issue by vprint** [EnMAP-Box/enmap-box#41]
Hello,

Transform raster layer only use 4 bands for sentinel-2 ( i guess these are the 4 10m bands)
![image](https://user-images.githubusercontent.com/42189444/189756086-fe1083ed-0b3c-42f2-860b-e049a860b0d7.png)

Reproduction : 
1) Import Sentinel-2 L2A product
2) Run Fit PCA tools with defaut settings
3) Run Transform raster layer : 

The following message appears :
Create Raster [10980x10980x4](Float32) -co INTERLEAVE=BAND COMPRESS=LZW TILED=YES BIGTIFF=YES

While it should be 
Create Raster [10980x10980x12](Float32) -co INTERLEAVE=BAND COMPRESS=LZW TILED=YES BIGTIFF=YES

**Comment by janzandr** [comment]
If you are using the default parameterization for PCA, the number of extracted components is limitted to 95% explained variance:
![image](https://user-images.githubusercontent.com/45030715/189821381-a5a26b2e-3e72-4912-92b5-683c31d0aa7f.png)

Please read the docs: https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html
![image](https://user-images.githubusercontent.com/45030715/189821808-fd4f0b83-341b-4cbf-aae4-4a0a1e8a84ee.png)
