### ISSUE TITLE
[QPS] SpectralLibrary class is deprecated, replace usages with SpectralLibraryUtils

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#417]
Several unittests aren't passing because of a problem with the QPS **SpectralLibrary** class:
```
from enmapbox.qgispluginsupport.qps.speclib.core.spectrallibrary import SpectralLibrary
library = SpectralLibrary()
print(library)
```

Error:
```
Traceback (most recent call last):
library = SpectralLibrary()
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\qgispluginsupport\qps\speclib\core\spectrallibrary.py", line 1208, in __init__
    assert self.editorWidgetSetup(i).type() == EDITOR_WIDGET_REGISTRY_KEY
AssertionError
```

**Comment by jakimowb** [comment]
and which unittest does not pass?

**Comment by janzandr** [comment]
E.g.
![image](https://user-images.githubusercontent.com/45030715/227911329-33cf0e37-9cd0-4a52-8f91-b5c8a75a9250.png)

**Comment by jakimowb** [comment]
Sorry, I forgot to add a deprectation warning on the SpectralLibrary class. Since ~1 year it should not be used any more.
Instead, use QgsVectorLayers and use the SpectralLibraryUtils to add fields to store spectral profile data.

**Comment by janzandr** [comment]
Thanks @jakimowb.
I will use **SpectralLibraryUtils.createSpectralLibrary()** to create an in-memory library and addProfiles() to add data.
Which routine can be used to export the in-memory library to GeoPackage?

**Comment by janzandr** [comment]
@jakimowb, after 1 year of deprecation, I think you should delete the **SpectralLibrary** class, if it isn't working anymore.

**Comment by jakimowb** [comment]
is in progress.

To store a vector layer as new vector layer you can use
QgsVectorLayerExporter or QgsVectorFileWriter

**Comment by janzandr** [comment]
How about supporting not only in-memory here?
`SpectralLibraryUtils.createSpectralLibrary()`
Would be nice if I could do the creation of the Speclib-Layer using the **SpectralLibraryUtils** class as well.

**Comment by janzandr** [comment]
For now I just create GeoJSON files, because it is currently the most simplest way to create a speclib.
After #423 is implemented, GeoJSONs will also work better out of the box.
