### ISSUE TITLE
Upgrade Python

### ISSUE THREAD

**Issue by MMouafik** [EnMAP-Box/enmap-box#421]
Hello
My QGIS has Python 3.9.5 by default. I can't update it to Python 3.10 or upper version of Python. So please I need help and thanks in advance.
Best Regards

**Comment by janzandr** [comment]
My QGIS Python is 3.9.5 as well.
No need to update to 3.10?
Why do you want to do that?

**Comment by MMouafik** [comment]
I thought it was the prroblem into running the agricultural apps because show me many error in python panel.

**Comment by janzandr** [comment]
Please show the error messages.

**Comment by MMouafik** [comment]
You could find it in this website: https://github.com/EnMAP-Box/enmap-box/issues/409
