### ISSUE TITLE
[Spectral View] content of GeoJSON file not correctly recognized

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#422]
I want to prepare a spectral library in GeoJSON format outside of QGIS, e.g. inside a R script or manually inside a text editor.

Here is an example:
```
{
    "type": "FeatureCollection",
    "name": "Spectral Response Function",
    "description": "",
    "features": [
        {
			"type": "Feature", 
			"properties": {
				"fid": 1,
				"name": "profile 1", 
				"profiles": {
					"x": [1, 2, 3], 
					"xUnit": "Nanometers", 
					"y": [3, 2, 1]
				}
			}, 
			"geometry": null
		}
    ]
}
```

Problem: the EnMAP-Box isn't supporting the GeoJSON file as is:
![image](https://user-images.githubusercontent.com/45030715/228464338-bd1907e1-4d85-4719-b390-492dcfa9c059.png)

**Comment by janzandr** [comment]
Also, even selecting the SpectralProfile widget inside QGIS didn't solve the problem:
![image](https://user-images.githubusercontent.com/45030715/228465380-ab1a6586-f7e9-4a0a-b53a-9b3bee2dac5c.png)

**Comment by jakimowb** [comment]
After changing the widget type to "Spectral Profile" you need to add a new profile visualization (which could not be started before, since no Spectral Profile field was known)

![grafik](https://user-images.githubusercontent.com/1404870/228472022-751efa62-48af-4c82-ad55-b17a31cc739a.png)

**Comment by jakimowb** [comment]
If you like you can file a FR
