### ISSUE TITLE
[Spectral View] better support for GeoJSON format

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#423]
_Discussed with @jakimowb, follow-up issue for #422._

The EnMAP-Box speclib format is very powerful by supporting any vector provider known to QGIS and speclibs can be created programmatically using QGIS API, e.g.: https://github.com/EnMAP-Box/enmap-box/blob/main/examples/spectral_libraries.py

However, in case of the human-readable GeoJSON format, the user can simply define the library inside a text editor, or in another scripting language (e.g. R) outside of QGIS, without using the QGIS API.

Here is an example of such a GeoJSON speclib:
```
{
    "type": "FeatureCollection",
    "name": "Spectral Response Function",
    "description": "",
    "features": [
        {
			"type": "Feature", 
			"properties": {
				"fid": 1,
				"name": "profile 1", 
				"profiles": {
					"x": [1, 2, 3], 
					"xUnit": "Nanometers", 
					"y": [3, 2, 1]
				}
			}, 
			"geometry": null
		}
    ]
} 
```

For best user experience, this speclib should work inside the EnMAP-Box as is.
When opened inside the Spectral View, the EnMAP-Box should:
1. automatically use the **profiles** field as a **SpectralProfile** type.
2. setup a new profile visualization using the **profiles** field

**Comment by jakimowb** [comment]
As GeoJson does not support the provision of attribute-specfic metadata,  I would rather recommend to just generate a simple QML that describes the "profile" column. This is much more clear and avoids assumptions based on field names.

Think about a field "profile" whose widget editor type is always changed to "SpectralProfile" automatically, although this is not intended by a user.

**Comment by jakimowb** [comment]
Just realized that the qml can be even shorter:

```
<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis>
  <fieldConfiguration>
    <field name="profiles">
      <editWidget type="SpectralProfile"/>
    </field>
  </fieldConfiguration>
</qgis>
```

**Comment by janzandr** [comment]
Agreed, putting such a small QML beside the geojson is fine.

**Comment by jakimowb** [comment]
Can it write a json with multiple profile fields?

**Comment by janzandr** [comment]
For now, it only writes "simple" libraries.
