### ISSUE TITLE
several icons aren't available anymore

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#429]
Since the last pull, several icons aren't available anymore:
![image](https://user-images.githubusercontent.com/45030715/228550660-ac03c002-c1b0-4a52-b40e-3461734ed09c.png)

I already tried to run **compile_resourcefiles.py**, but that doesn't solve the problem.

**Comment by jakimowb** [comment]
How do you start the EnMAP-Box?
Does the qgisresoruce folder exists with *_rc.py files?

**Comment by janzandr** [comment]
> How do you start the EnMAP-Box?

I start with QGISPlugIns/enmap-box/examples/start_enmapbox.py

> Does the qgisresource folder exists with *_rc.py files?
Which other *_rc.py files exist below the enmapbbox/ folder?

![image](https://user-images.githubusercontent.com/45030715/228588121-7576f17b-de3c-4524-85de-305e6d069a1d.png)

**Comment by janzandr** [comment]
That works.
