### ISSUE TITLE
Errors Loading EnMap-Box in QGIS

### ISSUE THREAD

**Issue by jbell6** [EnMAP-Box/enmap-box#437]
[Enmapbox_error.txt](https://github.com/EnMAP-Box/enmap-box/files/11122063/Enmapbox_error.txt)

The attached file shows the error I'm having loading EnMapBox 3.11.1 in QGIS 3.30.0.

I have tried multiple versions of both and this is in a fresh user profile. Is there anything else I can do?

The main issues appear to be:
 1. Unable to load enmapboxprocessing.algorithm.algorithms
             required field "ctx" missing from Subscript
2. Python error : Couldn't load plugin 'enmapboxplugin' due to an error when calling its initGui() method 

Any assistance would be much appreciated.

**Comment by janzandr** [comment]
This is a known issue with typeguard 3.x package. In the next release typeguard is fixed to v2.13.3, which solves the problem.
For now you can manually downgrade typeguard in your OSGeo4W Shell using: 
`pip install --force-reinstall -v "typeguard==2.13.3"`
