### ISSUE TITLE
PytestCollectionWarning: cannot collect test class 'TestCase' because it has a __init__ constructor

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#438]
Several tests in enmap-box\tests\enmap-box\* cannot be started due to this error:

```
enmapboxprocessing\testcase.py:14
  D:\Repositories\qgisplugins\enmap-box\enmapboxprocessing\testcase.py:14: PytestCollectionWarning: cannot collect test class 'TestCase' because it has a __init__ constructor (from: tests/enmap-box/enmapboxprocessing/test_extentwalker.py)
    @typechecked
```
See [report.txt](https://github.com/EnMAP-Box/enmap-box/files/11128029/report.txt) for more details

How to reproduce?
run `pytest tests\enmap-box`

or use the PyCharm short cut. It has to be applied for each subfolder/test-file separately, e.g. on `tests/enmap-box/enmapboxprocessing/algorithm`:
![grafik](https://user-images.githubusercontent.com/1404870/229256643-a26a7c66-d8d0-469a-95ac-e334d8e7e94d.png)

![failing_tests](https://user-images.githubusercontent.com/1404870/229256990-1b6074da-ffa1-4042-90ac-4a37f58c6f75.gif)

**Comment by janzandr** [comment]
I tried to replicate this with /enmap-box/tests/enmap-box/enmapboxprocessing/test_extentwalker.py
Can't replicate the error, test passes.
Also not sure what the error message means:
```
tests\enmap-box\enmapboxprocessing\test_extentwalker.py:6
  D:\Repositories\qgisplugins\enmap-box\tests\enmap-box\enmapboxprocessing\test_extentwalker.py:6: PytestCollectionWarning: cannot collect test class 'TestExtentWalker' because it has a __init__ constructor (from: tests/enmap-box/enmapboxprocessing/test_extentwalker.py)
    class TestExtentWalker(TestCase):
```
The TestCase has no constructor:
![image](https://user-images.githubusercontent.com/45030715/229456078-406904ee-99c9-4905-b3b0-c8dda66624e1.png)

![image](https://user-images.githubusercontent.com/45030715/229456293-3b79b95d-ec9b-49fe-ad55-aa0e6cd8d1f3.png)

**Comment by jakimowb** [comment]
Here is the log for tests/enmap-box/enmapboxprocessing on Ubuntu 22.04.2 LTS and mamba-forge QGIS 3.28

[errors_enmapboxprocessing.log](https://github.com/EnMAP-Box/enmap-box/files/11136764/errors_enmapboxprocessing.log)

**Comment by janzandr** [comment]
Hard to read. Can you hide the tests that pass? E.g. those:
![image](https://user-images.githubusercontent.com/45030715/229472084-82934bdc-7b26-426c-b8b5-24e11b9f15eb.png)

**Comment by janzandr** [comment]
Ah sorry, just saw that those aren't passing :-)

**Comment by janzandr** [comment]
Ok, than back to my original Question:

@jakimowb, can't replicate this on my system and the error doesn't really make sense.
Can you replicate the error on your local Linux system in PyCharm? Or is this a problem with running it from the command line?

**Comment by jakimowb** [comment]
Please provide a log file with the outputs when running `scripts/runtests.bat` (or `scripts/runtests.sh`)

**Comment by jakimowb** [comment]
> @jakimowb, can't replicate this on my system and the error doesn't really make sense.
> Can you replicate the error on your Linux system?

I can replicated it on windows + Linux, QGIS 3.28 and QGIS 3.30

**Comment by jakimowb** [comment]
Seems that on windows it is required to remove `#` from pytest.ini lines

Replacing:
````bash
from enmapboxprocessing.algorithm.testcase import TestCase
from enmapboxprocessing.algorithm.testcase import TestCase
````
with 

`from enmapboxprocessing.testing import TestCase`
allows to run the tests in `tests/enmap-box/enmapboxprocessing` (of course with many many errors as functionality is missing)

**Comment by jakimowb** [comment]
What do you like to have pushed?

**Comment by janzandr** [comment]
Sorry, I thought you have changed something!?
Not sure what I should do now? 
In PyCharm everything works fine. Problems only arise when using **runtests.sh** from the terminal.

**Comment by janzandr** [comment]
Currently I didn't get an error, but it seams to not finding any tests:
![image](https://user-images.githubusercontent.com/45030715/229518828-dbbc01b0-b9ad-4dc1-9eec-4f61729facdb.png)
