### ISSUE TITLE
EnGeoMAP tutorial out of date

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box#44]
I have been trying to work my way through the tutorial for EnGeoMap but the description in the tutorial does not match what I see in the EnGeoMAP version (v3). I know updating documentation can be a pain but it would be really appreciated if you can find the time to update the tutorials to match the current versions of the software.
Great piece of software and really keen to try it out in real mineral exploration situations.
Regards Grant Boxer, Perth, Western Australia

**Comment by janzandr** [comment]
@thielfab , what is the status of the new EnGeoMap tutorial from GFZ, isn't that already online?

**Comment by grantboxer** [comment]
I am not aware of that one. Do you have a link?

**Comment by jakimowb** [comment]
@janzandr this is the status of the EnGeoMAP tutorial
1. Offical webpage: https://enmap-box.readthedocs.io/en/latest/usr_section/application_tutorials/engeomap/tutorial_engeomap.html#the-enmap-geological-mapper-for-mineral-classification-engeomap

2. Source code: https://github.com/EnMAP-Box/enmap-box-documentation/tree/main/source/usr_section/application_tutorials/engeomap

3. Source code on GFZ gitlab server (requires login): https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/engeomap/-/blob/master/docs/tutorial_engeomap.rst but requires access to the GFZ gitlab server.

**Comment by janzandr** [comment]
@grantboxer  please test again.

**Comment by jakimowb** [comment]
@janzandr have you compared the tutorial descriptions and screenshots with the current EnGeoMap GUI as provided in the EnMAP-Box?

**Comment by janzandr** [comment]
Nope, I'm not involved in this issue. If there are still problems, Helge needs to fix it.
