### ISSUE TITLE
TestClassFractionRenderer: sklearn.utils._param_validation.InvalidParameterError 

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#440]
Running TestClassFractionRenderer.test_enmap in:

tests/enmap-box/enmapbox/coreapps/decorrelationstretchapp/test_decorrelationstretchrenderer.py

on GH CI throws

` sklearn.utils._param_validation.InvalidParameterError: The 'feature_range' parameter of MinMaxScaler must be an instance of 'tuple'. Got [0, 255]
`
see https://github.com/EnMAP-Box/enmap-box/actions/runs/4581735368/jobs/8091475637 for details

**Comment by janzandr** [comment]
Can't reproduce this with sklearn 1.1.2

**Comment by janzandr** [comment]
Confirmed on sklearn 1.2.2
