### ISSUE TITLE
Replace or remove user specific / local file paths

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#45]
Several unit tests want to access files that exist on local installations only. These tests will fail on other platforms and on CI jobs related to #14 .

For example [test_RandomPointsInStratificationAlgorithm.py](https://github.com/EnMAP-Box/enmap-box/blob/main/enmapboxprocessing/test/algorithm/test_RandomPointsInStratificationAlgorithm.py) uses `C:\Users\Andreas\Downloads\all_features_Cnv.tif `, which is not part of the EnMAP-Box repository:

```python
def test_debug874(self):
    alg = RandomPointsFromCategorizedRasterAlgorithm()
    alg.initAlgorithm()
    parameters = {
        alg.P_STRATIFICATION: QgsRasterLayer(r'C:\Users\Andreas\Downloads\all_features_Cnv.tif'),
        alg.P_N: 1,
        alg.P_SEED: 42,
        alg.P_OUTPUT_POINTS: self.filename('points.gpkg')
    }
    result = self.runalg(alg, parameters)
```

To ensure that all unit tests can be run, it is required to:

- replace the local path with a dataset available in the EnMAP-Box repository, e.g.  [`enmapbox/exampledata`](https://github.com/EnMAP-Box/enmap-box/tree/main/enmapbox/exampledata), or  [`enmapbox/tests/testdata`](https://github.com/EnMAP-Box/enmap-box/tree/main/tests/testdata)

- use datasets that are created on-the-fly. This is usefull to cover special cases like testing against male-formated metadata header. `EnMAPBoxTestCase().tempDir()` helps to create a temp directory in `<enmap-box repo>/test-outputs`. This folder is listed in .gitignore to avoid that temporary files are commited accidentially. For example:

  ````python
  class MyTestCase(EnMAPBoxTestCase):
     ...
  
      def test_myTest():
          # this will evaluate to `<enmap-box repo>/test-outputs/MyTestCase`
          tmpDir:pathlib.Path = self.tempDir()
         
         # create a local temporary file within tmpDir and use it in your unit test
         ...
  ````
  
- if the previous options are not possible, it its required that the affected test is mskipped:
  ````python
  
  class MyTestCase(EnMAPBoxTestCase):
     ...
      @unittest.skipIf(not os.path.isfile('my/file.txt'))
      def test_myLocalTest():
          localPath = 'my/file.txt'
          ...
        
  ````

**Comment by janzandr** [comment]
Thanks @jakimowb , I'm aware of the problem. Will be fixed.

**Comment by jakimowb** [comment]
It's more like an ongoing task that addresses unit tests in general. 
Actually there are 23 test_*.py files that contain a string like `C:\...` , also in external applications.

**Comment by janzandr** [comment]
Yes yes, will be fixed, and new tests will be correct right away.
