### ISSUE TITLE
Import Spectral Profiles -> from Raster Layer dialog

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#454]
needs a fix, see  screenshot
![grafik](https://user-images.githubusercontent.com/1404870/232388988-a8dccb67-c7bc-4cc5-9b68-450a0620e0d3.png)

**Comment by wangzj321** [comment]
This is the same problem I'm having and would like to get a solution to this problem. Thanks!

**Comment by wangzj321** [comment]
![Import Spectral Profiles](https://user-images.githubusercontent.com/130965571/232960866-c02e5ea1-4508-48aa-9ff7-24a8af1c0035.jpg)
This is the program problem I encountered, and the area indicated by the red arrow shows blurred.
