### ISSUE TITLE
RasterReader: undefined name Qgis

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#46]
enmapboxprocessing/rasterreader.py

Qgis is not imported

$ flake8 enmapboxprocessing/rasterreader.py 
enmapboxprocessing/rasterreader.py:490:43: F821 undefined name 'Qgis'

**Comment by janzandr** [comment]
yes, thanks.

**Comment by janzandr** [comment]
https://github.com/EnMAP-Box/enmap-box/commit/39d19e2ec3d692654f66526c68d9d813e9379763
