### ISSUE TITLE
Remove "Trying to unpickle estimator ... from version ... when using ... 1.1.1." warnings

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#462]
The `classifierDumpPkl` from `\tests\testdata\ml\classifier.pkl` is used in many unit tests.
Created with scikit-learn 0.24.2 (April 2021), it is now very outdated, as the current version of scikit-learn is [1.2.2](https://scikit-learn.org/stable/whats_new/v1.2.html). 

The outdated version leads to many warning messages, and it seems only a matter of time until warnings become errors due to missing backward compatibility.

I therefore recommend to update the classifier.pkl to a more recent scikit-learn version, at least the last major release.

It would be even better if the classifier.pkl could be created "on-the-fly" from other test data sets.

**Comment by janzandr** [comment]
We have removed all PKL files from the repo.
