### ISSUE TITLE
Incorrect geocoding of PRISMA L2D data imported via Import dialog

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#473]
When I run Project>Add Product>PRISMA L2D and I only specify the input PRISMA file (PRS_L2D_STD_20200813103056_20200813103100_0001.he5), the dataset is imported without an error but the geocoding information is incorrect. Here with Google WMS data in the background:

![grafik](https://github.com/EnMAP-Box/enmap-box/assets/16669114/56e6e1ef-b1e9-4f09-81d3-ba0f3d32d68e)
![grafik](https://github.com/EnMAP-Box/enmap-box/assets/16669114/bc1e2a7d-0f3c-4a4b-aaa8-7cf9dac2820a)

The single-band image here in the background is how is should look like:
![grafik](https://github.com/EnMAP-Box/enmap-box/assets/16669114/c8616d0c-0641-4028-a4f9-fcdf509f1a7e)

Correct map info:
Origin = (352740.000000000000000,5987250.000000000000000)
Pixel Size = (30.000000000000000,-30.000000000000000)

EnMAP-Box map info:
Origin = (352512.530000000027940,5987272.500000000000000)
Pixel Size = (22.629992464204975,-23.406079501169135)

Looks like at least the pixel size is wrong.

- EnMAP-Box 3.13.0alpha0
- QGIS 3.30.0 (conda-forge)
- Ubuntu 22.04

**Comment by danschef** [comment]
With a quick look at the code, it seems like the `geoTransform` is properly derived [here](https://github.com/EnMAP-Box/enmap-box/blame/65f966d7bebda27d425d185eed75de2ab9de09f9/enmapboxprocessing/algorithm/importprismal2dalgorithm.py#L232) but there is no `ds.SetGeoTransform(geoTransform)`. `writer = driver.createFromArray(array, extent, crs)` only sets the extent.

**Comment by janzandr** [comment]
Hmm, I agree, that doesn't look correct.
On my test scene it looks fine, and pixel size is 30m, as expected.
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/490bd354-1d05-42dd-8ca5-c5c11d2f1632)

I would guess that they slightly changed the format.

**Comment by janzandr** [comment]
> With a quick look at the code, it seems like the geoTransform is properly derived [here](https://github.com/EnMAP-Box/enmap-box/blame/65f966d7bebda27d425d185eed75de2ab9de09f9/enmapboxprocessing/algorithm/importprismal2dalgorithm.py#L232) but there is no ds.SetGeoTransform(geoTransform). writer = driver.createFromArray(array, extent, crs) only sets the extent.

The geotransform is created and set in the background:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/68654f0e-a522-4432-9692-e8d5df32030e)

**Comment by janzandr** [comment]
In the early days, right after the archive opened.

**Comment by danschef** [comment]
Ok, the above one is from 08/2020 but I just tried one from 12/2022 and it is working.

**Comment by janzandr** [comment]
Ah ok, maybe you have an earlier version. So shall we ignore and close the issue?

**Comment by danschef** [comment]
Well, it works with your dataset from the very beginning (probably earlier than 08/2020?), it fails with the one from 08/2020 and then works again with 12/2022. That is a bit strange but it seems like the PRISMA L2D reader implemented in ENVI produces the same result like the EnMAP-Box.

**Comment by janzandr** [comment]
> Well, it works with your dataset from the very beginning (probably earlier than 08/2020?),

I double check and found: `<MDI key="Processing_Time">2021-07-28T06:41:16.000326</MDI>`

So, my product isn't that old. I guess we can close this for now.
