### ISSUE TITLE
Select spectrum in the SpectralLibrary window and define color

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#475]
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/gui.html#collect-profiles
instructs how to define a different color for different sources,
but how to actually define the color of a given spectrum regardless of the source?
The most natural would be having the option to define color and style for a given spectrum in the menu that opens after selecting and right-clicking that spectrum.
Not being able to define the color as you add spectra is very inconvenient, you get very easily confused.

**Comment by janzandr** [comment]
> but how to actually define the color of a given spectrum regardless of the source?

If I'm not mistaken, you can't really assign a color to an individual profile.
You could use **@symbol_color** and classify your profiles by name. Now you can specify individual colors:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/530adf71-a7ad-41f3-bed6-36a0c9bdd985)

@jakimowb, anything to add here?
