### ISSUE TITLE
Points at places where spectra have been defined

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#476]
Is there a way to leave a marker on those places where the spectra have been collected?
Could these markers get (by default) the same color as the one defined to its spectrum?
Can x,y  coordinates be added to the table?

**Comment by aloboa** [comment]
I probably did not explain myself with enough clarity:
What I am asking for is the actual geographic point on the image.

**Comment by janzandr** [comment]
You can use the field calculator to add a field showing the geometry, e.g.
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/8ba141d4-1647-44ae-8e76-85c1d93e714a)

**Comment by aloboa** [comment]
Yes, there are ways to get the points, but my request is that the points should be marked on the image by default. If the user is collecting spectral samples, it is essential to keep track of where on the image he/she is actually collecting. 
Please do not close it.

**Comment by janzandr** [comment]
Not sure, if you have many map views opened, would you want to see the points in all map views by default?

**Comment by aloboa** [comment]
In all those that you are using to decide where to collect. As soon as you have a few points where you have already collected spectra, you must see where those actually are, before deciding where to put the next one. This is an interactive task. Note that you normally have open only those images and maps that you need.
