### ISSUE TITLE
Lacking Auxilliary/Import Library

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#481]
According to the doc:
"Spectral libraries can be imported as single line raster using the processing algorithm Auxillary ‣ Import Library"
I only have "Create default palette raster rendered" under Auxilliary.

**Comment by janzandr** [comment]
Thanks @aloboa.
@thielfab, looks like the the whole section is quite outdated: 
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/processing_datatypes.html#processing-data-types

@aloboa, please refere to the Glossary instead:
https://enmap-box.readthedocs.io/en/latest/general/glossary.html#term-spectral-library

**Comment by thielfab** [comment]
Since it was outdated I removed it from the TOC a while ago, although it can still be reached via the direct link. Might delete it completely then!

**Comment by aloboa** [comment]
Do not understand. How do we actually import a library? As far as I can see, this is not explained in the Glossary (which makes sense).

**Comment by thielfab** [comment]
It is described here https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/gui.html#loading-saving-and-importing-exporting

**Comment by aloboa** [comment]
Thanks. Why do you say this is outdated and will be removed? Won't it be possible to import envi spectral 
files in the future? why?

**Comment by thielfab** [comment]
I was referring to Andreas comment on the page on readthedocs regarding being outdated and deletion. Input/Output of ENVI spectral library is and will be supported by the Spectral Library Viewer 👍. Depending on the algorithm or tool it might just be required to perform this import beforehand.

**Comment by janzandr** [comment]
@aloboa just send me an example file that you want to import and I show you the correct algo for that.
