### ISSUE TITLE
short of spectral separability tests

### ISSUE THREAD

**Issue by dpoursanidis** [EnMAP-Box/enmap-box#494]
Working with spectra, is important to be able to run spectral separability tests to explore the collected data. Any work on that for next releases? 

Mahalanobis, and other tests (https://opus.uleth.ca/server/api/core/bitstreams/8e76d869-e190-4d92-bbfc-1636518874f9/content and see pg 43 as example)?

**Comment by janzandr** [comment]
Duplicate of #469.

**Comment by janzandr** [comment]
Implemented in #469.
