### ISSUE TITLE
temporal pixel profile from FORCE TSI raster not correctly displayed in SpectralView

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#5]
How to reproduce:

- use this raster: 1984-2021_060-319_HL_TSA_LNDLG_NDV_TSI.tif
from \\141.20.140.91\san\_EnMAP\Rohdaten\EnMAP-Box external Software Formats\FORCE\
- use this setup
![image](https://user-images.githubusercontent.com/45030715/188113216-5b381c55-7404-4845-9564-374614c9aa2f.png)

**Comment by janzandr** [comment]
Note that a raster pixel profiles may contain no data values. Maybe thats the reason for the display problems.
![image](https://user-images.githubusercontent.com/45030715/188114069-34c67a1b-e7ee-4277-b5bc-3a1ba75babe7.png)

**Comment by jakimowb** [comment]
Can the profiles be displayed in Band Number / Band Index mode for x-axis values?

**Comment by jakimowb** [comment]
Mmmh. Referring to data sources that cannot be used by every developer is bad style.
We need to add images to our tests/testdata folder, as only this allows to check our algorithms against them in CI workflows.
Therefore I want to create a 10x5 pixel FORCE TSI example file and add it to tests/testdata/force.
(similar to what QGIS does in https://github.com/qgis/QGIS/tree/master/tests/testdata/raster)

However, the `enmapbox:TranslateRasterLayer` processing algorithm fails to create such a spatial subsets while maintaining its metadata. So I'll wait until #9 is fixed first.

**Comment by janzandr** [comment]
1. Creating a mini FORCE TSI is a good idea.
2. In **enmapbox:TranslateRasterLayer** you have to use the "**Copy metadata**" option (default is False, i.e. not copy metadata).

**Comment by janzandr** [comment]
> Can the profiles be displayed in Band Number / Band Index mode for x-axis values?
No. None of the options work.

**Comment by janzandr** [comment]
> Mmmh. Referring to data sources that cannot be used by every developer is bad style.

Data was provided by Katja Kowalski. I guess it would be to harsh to only accept minimalistic datasets from users.

**Comment by jakimowb** [comment]
The mini examples are for enmap-box\tests\testdata only, so that they can be used by CI and developers that don't have access to your local windows drives. For large-data-set / performance test we might use data from outside the repository files. But in this case unittests need to be skipped (@unittest.skipIf decorator) if required data sources are not available

**Comment by janzandr** [comment]
Hmm, still not working for me...
![image](https://user-images.githubusercontent.com/45030715/188302562-6475ef6a-8185-4f23-9da0-442b5e58f7e6.png)

**Comment by jakimowb** [comment]
What is printed if you run `git submodule` @janzandr ?

**Comment by janzandr** [comment]
```
>>>(base) D:\source\QGISPlugIns\enmap-box> git submodule
 444ed1b90004a3b65bc0d9069f7f42393279587c enmapbox/apps/lmuapps (heads/master)
 1b36334486b6a9dca0cd3e1720dcd755eb30b9f2 enmapbox/qgispluginsupport (heads/master)
```
