### ISSUE TITLE
Error mouse move?

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box#50]
I am working through the EnGeoMAP tutorial and downloaded the Gamsberg data. I have imported it into the EnMapBox QGIS plugin but keep getting the following message, any thoughts on what might be causing this?
"2022-09-14T09:34:27     WARNING    Traceback (most recent call last):
              File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph\pyqtgraph\dockarea\Dock.py", line 342, in mouseMoveEvent
              self.mouseMoved = (lpos - self.pressPos).manhattanLength() > QtWidgets.QApplication.startDragDistance()
             AttributeError: 'DockLabel' object has no attribute 'pressPos'

**Comment by grantboxer** [comment]
I get the above error whenever I move the mouse off the active map window in EnMapBox.

**Comment by jakimowb** [comment]
@grantboxer it's a bug in the underlying PyQtGraph library. Does it disappear if you click on the map or the map dock title banr at once?

**Comment by jakimowb** [comment]
@grantboxer I downloaded the gamsberg data, but I am not able to reproduce the error. In case the error still occurs on your system, please reopen this issue and try to provide a detailed description how to reproduce it, e.g. as animated gif.
