### ISSUE TITLE
Missing datasource in Raster math Model Builder

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#502]
The "Raster Math" algorithm does not allow to use the outputs of previous algorithms as input for code calculation.

In the following image, I like to choose the "EnMAP-Image" raster as input for the "Raster Math" algorithms.
This is possible in case of the "Grid" parameter, but there seems no way to use it as input for the "Code" parameter / it's  "Available data sources" list.

![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/3597b8c6-6fb3-423d-91f1-57d23a12c8f1)

**Comment by janzandr** [comment]
In the modeller you have to use R1...R10 input parameters:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/a7ff1ce4-6074-4bef-a008-7f610a0904b4)
