### ISSUE TITLE
Regression-based unmixing does not allow to select Endmember dataset

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#503]
The "Regression-based unmixing" algorithm does not allow to select the output of a "Create classification dataset ..." algorithm as Endmember dataset input. This makes the algorithm unusuable in the QGIS Model builder.

![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/43038502-8b74-4917-88d0-2023fb809b96)

**Comment by janzandr** [comment]
This is the same issue described in #504.
