### ISSUE TITLE
"Predict classification layer" can not use RFc model

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#504]
The "Predict classification layer" algorithm does not allow to use the classifier output of the "Fit RandomForestClassifier" output.
Instead, it should be selectable as simple as the output raster from the "Import EnMAP L2A product"

![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/988c201d-b5bd-461e-a145-1dccbb658f53)

**Comment by janzandr** [comment]
This is a general issue with custom widgets in processing algorithms: https://github.com/qgis/QGIS/issues/48816
QGIS DEVs decided to not fix it, because it uses deprecated API classes.
Unfortunately, QGIS DEVs didn't told me which API classes to use instead and/or to provide an example implementation.

**Comment by janzandr** [comment]
I agree, that this would be an important issue to be solved.

**Comment by janzandr** [comment]
@jakimowb I prepared a minimal example reproducing the problem:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/b156a8d1-9319-43ab-a26a-b1e9f1055ac7)

https://github.com/EnMAP-Box/enmap-box/blob/504-predict-classification-layer-can-not-use-rfc-model/enmapboxprocessing/algorithm/ISSUE_504_ALGO.py

**Comment by janzandr** [comment]
So far I have no idea how to replace the deprecated WidgetWrapper class:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/6bbe5430-62cf-4326-ace6-59938a50bd41)

**Comment by janzandr** [comment]
Note that even native QGIS algorithms still use the deprecated WidgetWrapper class.
E.g. in the QGIS Raster Calculator the EXPRESSION parameter:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/d3fe1f8c-7bae-453d-a952-91f6b3e08bed)

Implementation is here:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/c1ec6d87-a4a6-4173-8ea1-8dd49f07804c)

**Comment by jakimowb** [comment]
Have you checked the QGIS C++ code? This usually provides many example how the QGIS API can be used, in particular in case of those classes which were moved from pure python to C++ implementations

**Comment by janzandr** [comment]
My problem is, that there is no example implementation of a custom parameter widget, that isn't using the deprecated API.

**Comment by janzandr** [comment]
> Have you checked the QGIS C++ code? This usually provides many example how the QGIS API can be used, in particular in case of those classes which were moved from pure python to C++ implementations

I tried to find something last time without success.

**Comment by janzandr** [comment]
So far I haven't found any custom widgets that aren't implemented via the deprecated class.

**Comment by jakimowb** [comment]
In that specific case it just requires a standard input parameter for the classifier *.pkl file.
It is confusing that the custom widget can do all sorts of other things, but does not handle the basic case of accepting a previously created file.

**Comment by janzandr** [comment]
Ah, I just noticed that I already did that for the Fit RFC algo:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/fb4f44f9-56da-4553-b622-7639f8deffb9)

Implementation is rather easy:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/0eca3d58-0db6-4a33-bdf6-aa5afbd8dd5b)

**Comment by janzandr** [comment]
At the time I tried that, their was still a bug not hiding the other algo correctly in the modeller, but that issue seams to be solved in QGIS >3.28.

Now it looks very clean inside the GUI. The only detail a user might notice is the different algo ID, but that shouldn't really matter:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/4c057872-9145-4464-aaf1-9b391a4e5c34)

**Comment by janzandr** [comment]
@jakimowb I would suggest to work around the issue by having the above descriped solution.
Is that fine with you?

**Comment by janzandr** [comment]
The good thing is: we don't have to fix every algorithm individually, we just have to fix each custom input parameter.
We just check at runtime, if the algorithm is used inside the modeller, if so, don't use the custom widget wrapper.
E.g.
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/c1df8159-f572-4f81-9c30-1c2e0d259907)

**Comment by janzandr** [comment]
@jakimowb pointed out that there is an QGIS algo that isn't using the deprecated WidgetWrapper class for it's custom widget:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/989c1ddb-ba32-4f87-b2f6-379178d06e6e)

I will check that out.

**Comment by janzandr** [comment]
I wasn't able to figure this out.
But I have found an easy/hacky way to know if the algo is running inside the modeller, by just looking into the current tracestack.
I just check if the algo is called by anything from the **ModelerDialog.py**:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/9183f131-de21-491f-91b8-39d5615c5a4a)

Now I can just decide at runtime, whether to use the custom widgets:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/6b22fffc-f2fe-4ed3-84f4-4593ab045473)

This will fix the problems in any of our algorithms :-)
