### ISSUE TITLE
Bug in beta leaf angle distribution within IVVRM (EnMAP-box 3.12.1)

### ISSUE THREAD

**Issue by ClementAtzberger** [EnMAP-Box/enmap-box#507]
Dear all - please take note that the BETA (uniform, planophile, ...,and all other) leaf angle distribution creates some results that lead to INFORM (but also 4SAIL) to become insensitive to variations in cd (crown diameter), LAI, sd (stem density), h (height) ....
This is evident when running INFORM (or 4SAIL) with the alternative (ellipsoidal) leaf angle distribution, where everything works well.
Thanks - Clement

**Comment by janzandr** [comment]
Hi @ClementAtzberger, I will forward the issue to the LMU group ([m.wocher@iggf.geo.uni-muenchen.de](mailto:m.wocher@iggf.geo.uni-muenchen.de) and [tobias.hank@lmu.de](mailto:tobias.hank@lmu.de)).

**Comment by janzandr** [comment]
@ClementAtzberger , @Maesiu , not sure what's the status of this issue: is this a bug in EnMAP-Box or is this Matlab related?
Can we close it?

**Comment by ClementAtzberger** [comment]
Hi - i think we can close it because it seems to happen only on my computer
... other colleagues do not face the same problem
Thanks a lot for your help/assistance
Clement
