### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box#51]
I am trying to use the Reclassify Tool and I get the following error. Any thoughts?

AssertionError 
Traceback (most recent call last):
  File "C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\reclassifyapp\reclassify.py", line 552, in onAddRaster
    self.setSrcRasterLayer(file)
  File "C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\reclassifyapp\reclassify.py", line 646, in setSrcRasterLayer
    assert isinstance(src, QgsRasterLayer)
AssertionError

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdada 

Python Path:
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\ensomap
C:/OSGeo4W/apps/qgis/./python
C:/Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\Users\Grant\AppData\Roaming\Python\Python39\site-packages
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps
.
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\openlog\embedded_external_libs
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuapps

**Comment by janzandr** [comment]
Reclassify app had some issues that are fixed already.
