### ISSUE TITLE
"Über QGIS" opens "About EnMAP-Box.

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#517]
In the help menu, there should be an entry "About EnMAP-Box" instead of "Über QGIS".

![grafik](https://github.com/EnMAP-Box/enmap-box/assets/16669114/528b72b3-adab-4c10-b170-bc7d002242a6)

**Comment by janzandr** [comment]
Looks fine on my system:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/73f072ff-04d8-4dc6-a5a2-7558b8ddeb9a)

@jakimowb can you check this.

**Comment by janzandr** [comment]
Missing user feedback. @danschef, please re-open if necessary.
