### ISSUE TITLE
[Agricultural Application] why the "Agricultural Applications already loaded. Reload" info message at startup?

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#524]
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/a4b5dcf2-fbc0-4f8d-85aa-c44a4cb6da21)

@Maesiu , @jakimowb why the info message?

**Comment by Maesiu** [comment]
Reason might be that there is still the old lmuapps folder in the enmapbox repo:
![grafik](https://github.com/EnMAP-Box/enmap-box/assets/30070733/08da900a-67a0-4d94-a4f0-cf56cc14c6e7)
-> lmuapps should be deleted.
-> lmuvegetationapps is the one we will continue working on.

**Comment by janzandr** [comment]
Thanks, I'll delete the old "lmuapps" folder.

**Comment by jakimowb** [comment]
closed by 909ed1abe4d5478f3b56c0c066d7c9371052a856 (removal of submodule)
