### ISSUE TITLE
Sensor Product Import 

### ISSUE THREAD

**Issue by Danro77** [EnMAP-Box/enmap-box#527]
Hey, 

i am currently trying to import an EnMAP L2A product in the EnMAP Toolbox. I wanted to import the product via the "Sensor Product Import" tool. As I am trying to drag and drop the product it does not allow me to drop the product. Has anyone faced this problem and has a solution for this? 

Thanks in advance!

**Comment by janzandr** [comment]
What OS and QGIS version are you using?
Can you show a screencast (e.g. animated GIF) of the problem?

**Comment by Danro77** [comment]
I use the current 3.28.8 LTR version of QGIS. When i tried to drop the product it showed me the attached icon. 
![image](https://github.com/EnMAP-Box/enmap-box/assets/77552974/fc5f1734-524b-4cf6-a3d3-9a8aa2588acf)

Importing the image via "Import Product" --> "EnMAP L2A" first gave me an error message but i just found out how to fix my problem.
