### ISSUE TITLE
"An error occurred during inversion" 

### ISSUE THREAD

**Issue by Danro77** [EnMAP-Box/enmap-box#540]
Hey, 

i am currently doing the EO-College course "Beyond the Visible – Imaging Spectroscopy for Agricultural Applications". In chapter 5 it is explained how to create a synthetic training data set and an ANN. The Workflow is to create a look-up table and train the ANN with this table. Last I want to apply my ANN to my image with the ANN Vegetation processor and get the following error message: 

"An error occurred during inversion: X has 184 features, but StandardScaler is expecting 202 features as input."

I work with a downloaded EnMAP Dataset from the EnMAP Data Access Portal and also chose EnMAP as my Sensor while creating the look-up table. I have no idea where i can find the root of this message and hope that someone else also faced and maybe solved this problem.

**Comment by janzandr** [comment]
@Maesiu, can you help?

**Comment by Maesiu** [comment]
There might be an old spectral response function implemented. Can you tell me how many bands there are when you create the LUT and the number of bands of your EnMAP imagery?

**Comment by janzandr** [comment]
> ...the number of bands of your EnMAP imagery?

Ah, maybe I have an idea, where the problem arises. The EnMAP L2A product import has several options for handling bands inside the detector overlap region. The default is to only use SWIR bands.
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/76242b89-57b2-4f44-8fc9-315848f057a6)

**Comment by Danro77** [comment]
As overlap region I chose "order by detector". When I tried the other options the number of features changed but I still get the same error message. If i choose "moving average filter" my QGIS crashes..

My EnMAP image has 224 bands and when I create the LUT it says 242 bands.

**Comment by Maesiu** [comment]
You can create a spectral response function via "add new sensor" and extract it from your EnMAP images .hdr file

**Comment by Danro77** [comment]
Creating an own spectral response function worked!

Thank you very much! 👍
