### ISSUE TITLE
PRISMA L1 import failing to use h5py

### ISSUE THREAD

**Issue by LFlannigan** [EnMAP-Box/enmap-box#545]
I'm attempting to import L1 PRISMA data into EnMAP-Box, but every time I try I am met with the error "Reading data with h5py failed. Fall back to GDAL API, which is very slow in PRISMA BIP interleaved data." (Image attached)
<img width="1015" alt="PRISMA_error" src="https://github.com/EnMAP-Box/enmap-box/assets/35909786/c7025dd5-8f36-4c2d-aa81-5773af66138e">

Looking through previous issues, it looks like only one other user had this problem and it was related to typeguard. However, my version of typeguard appears to be correct. Is it potentially an issue with one of the other packages? List of all packages and their versions below
<img width="670" alt="enmap_pckgs" src="https://github.com/EnMAP-Box/enmap-box/assets/35909786/991e0d1d-fe80-470c-9193-8578ae9c813e">

Any help on this would be greatly appreciated, as I've waited over an hour and the L1 product still hasn't finished importing.

**Comment by janzandr** [comment]
The h5py package can't be installed via the PIP Package Installer.
You have to install it via the OSGeo4W Installer:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/af6413fd-aef3-49c8-957d-0a7f34bafe42)

Check the installation in the QGIS Python Console:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/e2154291-621b-43b6-901a-e252e25b32e6)

**Comment by janzandr** [comment]
Missing user feedback. Please re-open if necessary.
