### ISSUE TITLE
Vector Layer to spectral libary 

### ISSUE THREAD

**Issue by Danro77** [EnMAP-Box/enmap-box#547]
Hello there,

i have a Sentinel-2 and an EnMAP image of the same scene and day. I want to compare spectral profiles on different pixels. For this I collected my ROIs in a vector layers as dots. Now I want to visualize these dots in the spectral libary viewer for both images. Is there such a tool or do I have to collect my ROIs in the Toolbox? 

Thanks in advance
Daniel

**Comment by janzandr** [comment]
I'll close this for now, please re-open if necessary.
