### ISSUE TITLE
Warning on startup: "Agricultural Applications already loaded"

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#568]
![grafik](https://github.com/EnMAP-Box/enmap-box/assets/15610561/d1122dcc-bbfa-4985-957a-89ce6d1b7855)

EnMAP-Box Version 3.13.0alpha0.20230818T122709.main Code [7dd220072a9](https://github.com/EnMAP-Box/enmap-box/commit/7dd220072a99218b246702752e6604ef0c0cff6c)

**Comment by janzandr** [comment]
already solved
