### ISSUE TITLE
Spatial profile

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#58]
Is there a tool within EnMapBox to plot the profile of the values of a given a row, column or arbitrary line?

**Comment by janzandr** [comment]
No, not yet. Would be nice to have.

**Comment by aloboa** [comment]
It would be great. At least with 1 band, but actually, even a 2D plot for multiple bands (letting the user select which bands to display).

**Comment by janzandr** [comment]
Maybe as a first improvement, we could have a new option **Type** = _Z-Profile | X-Profile | Y-Profile_ here:
![image](https://user-images.githubusercontent.com/45030715/190633177-c060ec5d-85a1-4550-9987-923ca976761f.png)

@jakimowb , what do you think?

**Comment by jakimowb** [comment]
@aloboa how should the spectral setting for such a profile look like, in terms of wavelength and wavelength units? Maybe just skip it?

**Comment by janzandr** [comment]
Hi @aloboa, now that we have the _Profile Analytics_ app (see #81) for plotting, analysing and annotating (user-defined plot annotations), I'm much more flexible to implement new visualizations for profiles.

You can already select spectral profiles (i.e. Z-Profiles):
![image](https://user-images.githubusercontent.com/45030715/193025203-76191c26-76da-4ecd-9de8-f6e7bd4b4cfe.png)

I could imagine to introduce a mode for spatial profiles (one band, X- or Y-Profile for the current location).

**Comment by janzandr** [comment]
> @aloboa how should the spectral setting for such a profile look like, in terms of wavelength and wavelength units? Maybe just skip it?

@jakimowb , the current location comes from a specific map canvas. I will take the CRS of that map canvas and plot the profile against the distance to the selected location.
The x value at the selected location is 0, the x values to the left are negative, to the right are positve.
This way, multiple spatial profiles from different sources are comparable and can be plotted together.

**Comment by janzandr** [comment]
Just to be absolutely clear.
The blue line is not the X-Profile:
![image](https://user-images.githubusercontent.com/45030715/193033104-13dd0084-340e-49bc-aeea-fa8b65f866c0.png)

This is the X-Profile:
![image](https://user-images.githubusercontent.com/45030715/193033308-760990b6-4daf-4190-8af6-b0721084ed2e.png)

**Comment by aloboa** [comment]
> @aloboa how should the spectral setting for such a profile look like, in terms of wavelength and wavelength units? Maybe just skip it?

Not sure I understand the question. I assume this is a tool for spatial profiles of values at a given band, thus the user must select the band. In a later stage, having more complicated plots with values in all bands could be useful. I will try some options in R and show them to you.

Regarding the actual line being plotted, I think what you say is the simplest approach, but the user will often need the values along an specific line, which could be marked by clicking points and/or be imported from a line vector.

**Comment by janzandr** [comment]
We can now plot X and Y profiles for a given raster band:
![image](https://user-images.githubusercontent.com/45030715/193148087-dd7271bc-336e-42b6-af4d-d829de8cff91.png)

**Comment by janzandr** [comment]
Hi @aloboa, I think I have a good approach for the spatial profile along a vector line.

Given a line feature:
![image](https://user-images.githubusercontent.com/45030715/193156211-f1f8f619-95ff-4fa6-a5da-c2da99c7fb2c.png)

We can use the _Generate points (pixel centroids) along line_ algforithm:
![image](https://user-images.githubusercontent.com/45030715/193156337-88fe4868-57e9-4e27-8e5a-8070e2dccf64.png)

Which gives us nicely ordered pixel locations along the line:
![image](https://user-images.githubusercontent.com/45030715/193156756-f0e4fe5a-23b8-4434-9b1c-c2efacd0980c.png)

Now we can read all pixel values of a given band and plot against the **point_id**.

**Comment by janzandr** [comment]
Alternatively, we could use this algorithm:
![image](https://user-images.githubusercontent.com/45030715/193157765-6bf66f76-8f03-4fd8-ac6a-18e38c5e2eb7.png)

Which gives us geo locations on the line and the cumulative distances:
![image](https://user-images.githubusercontent.com/45030715/193158035-a44d431d-7a0f-404a-8492-54e34722ff7f.png)

Now we can plot against the **distances**, which would allow to compare spatial profiles from different raster sources (e.g. profiles from Landsat, Sentinel-2 or EnMAP in one plot).

**Comment by aloboa** [comment]
This looks very nice! I understand the line feature must pre-exist (eg, drawn in main QGIS).
Are you going to produce the weekly zip for testing all these improvements (as mentioned by email with Benjamin Jakimow)?

**Comment by janzandr** [comment]
> I understand the line feature must pre-exist (eg, drawn in main QGIS).

Yes, the line feature must be part of an vector layer. But you don't have to switch to QGIS to draw a new line, you can do this inside the EnMAP-Box:
![image](https://user-images.githubusercontent.com/45030715/193208259-0b5807ad-ef06-41dc-90be-9d077b345920.png)

Unfortunately, we don't have the Vertex Tool for editing a line afterwards:
![image](https://user-images.githubusercontent.com/45030715/193208706-b5552978-5048-434a-a589-46aa303ee700.png)

@jakimowb, are you interested in implementing that?

**Comment by jakimowb** [comment]
> > I understand the line feature must pre-exist (eg, drawn in main QGIS).
> 
> Yes, the line feature must be part of an vector layer. 

To my feeling there are far too many steps users are confronted with, just to get the spatial profile.
The tool should be usabla as simple as, for example, the cursor location value tool. 

I recommend to create a simple map tool that captures the spatial line of interest. 
After that, everything else should be done in background, i.e. (i) mapping the line geometry to pixel coordinates, (ii) deriving band values, (iii) plot the profile.

**Comment by janzandr** [comment]
> To my feeling there are far too many steps users are confronted with, just to get the spatial profile.
The tool should be usabla as simple as, for example, the cursor location value tool.
I recommend to create a simple map tool that captures the spatial line of interest.
After that, everything else should be done in background, i.e.

I'm still undecided. It depends on the usecase. 
1. If I want to do a real analysis, I will store all my lines of interest inside a vector layer for reproducibility. Now I can select the lines I want to display in the plot. 
2. Having a seperate _"Identify Cursor Line"_ Map Tool is also a good idea. Is such a map tool available via QGIS API already?

**Comment by janzandr** [comment]
> After that, everything else should be done in background, i.e.

> map the line geometry to pixel coordinates,
deriving band values,
plot the profile.

Yes, that is the plan.

**Comment by janzandr** [comment]
> I recommend to create a simple map tool that captures the spatial line of interest.

Something that behaves similar to the Measure tool would do the job:
![image](https://user-images.githubusercontent.com/45030715/193226069-6f417d12-513b-4e5f-8e7d-1ede51866de0.png)

**Comment by janzandr** [comment]
Hallelujah, we have Spatial Profiles :-)

Given a vector layer with lines, the user can simply select one of the lines to plot the spatial profiles of the selected raster bands.
![image](https://user-images.githubusercontent.com/45030715/193255058-bcfbf705-b91a-43f0-a504-3109b9a2df22.png)

**Comment by janzandr** [comment]
>  In a later stage, having more complicated plots with values in all bands could be useful.

@aloboa, technically it's easy to read the values of all bands. Let me know, if you have an idea for plotting.

**Comment by janzandr** [comment]
@jakimowb, as soon as we have that _"Identify Line"_ map tool (see #91), I will implement a version, where the lines can be drawn interactively.

**Comment by jakimowb** [comment]
You can use the QgsMapToolCapture to draw lines interactively.

**Comment by aloboa** [comment]
> Hallelujah, we have Spatial Profiles :-)
> 
> Given a vector layer with lines, the user can simply select one of the lines to plot the spatial profiles of the selected raster bands. 

Looking forward to trying it out.

**Comment by aloboa** [comment]
Cannot find the drawing tool in
Version 3.11.20221001T022425.main Code [3ddc7f39f87](https://github.com/EnMAP-Box/enmap-box/commit/3ddc7f39f87ec1c62310653db617d2ecff3a2095)
![nodrawingtool](https://user-images.githubusercontent.com/6074054/194047443-0b770573-8666-4625-9e87-332a3d97e6cb.jpeg)

**Comment by janzandr** [comment]
Here is the map tool for selecting a location, and don't forget to select a raster layer:
![image](https://user-images.githubusercontent.com/45030715/194047795-d37457a9-58dd-43ab-8e50-8f399887c75a.png)

**Comment by janzandr** [comment]
> "Type" should be "Plot type".

PlotType or better ProfileType?

**Comment by janzandr** [comment]
> Could the displayed raster be selected by default instead of nothing?

Yes, that would be better. See #122.

**Comment by janzandr** [comment]
> I would add the Wavelength and not just the band name (including the wavelength in the name is not guaranteed).

This is the standard QGIS band selection widget. The shaown band names are prepared by QGIS.
@jakimowb have you ever thought about overwriting the default behaviour? I'm not sure if that would be a good idea in terms of consistency.

**Comment by janzandr** [comment]
> I do not get to transfer a New Temporary scratch layer from QGIS into EnMapBox, it actually disappears when I drag and drop
(as do those saved to disk, but those can be read back from within EnMapBox).

@aloboa we had some drag&drop issues, not sure if that problem is already covered by an issue. Please create a new issue for that.

**Comment by janzandr** [comment]
> I do not get the select tool and thus cannot select the line once displayed in EnMapBox:

Try this:
![animation7](https://user-images.githubusercontent.com/45030715/194118078-3ef81b2d-577a-4ff3-9874-0cfd665c07cf.gif)

**Comment by aloboa** [comment]
> Should be possible:
How do I get that New scratch layer in the Data View?
Do you drop it from QGIS? Then I'll find the relevant ticket. No way
to actually be able to create it in EnMapBox itself? 

> PlotType or better ProfileType?
Profile Type is better, you're right. Also, if you plan to support other sources, I suggest changing Source to Source type.

> Try this:
Works! Actually having to select in the Data Views first is consistent with the general behavior of QGIS in the Layers tab.

**Comment by janzandr** [comment]
> How do I get that New scratch layer in the Data View?
Do you drop it from QGIS? Then I'll find the relevant ticket. No way
to actually be able to create it in EnMapBox itself?

![image](https://user-images.githubusercontent.com/45030715/194122941-cf942fa5-efd0-4c1f-9e84-7018770c9bc3.png)

**Comment by janzandr** [comment]
> Profile Type is better, you're right. Also, if you plan to support other sources, I suggest changing Source to Source type.

Alright, _Source Type_ and _Profile Type_!

**Comment by aloboa** [comment]
Succeed with the New Temporary scratch layer in EnMapBox. Perhaps too many clicks until
the user gets the plot, but this is consistent with the QGIS way of doing things.
