### ISSUE TITLE
import L2A EnMAP data - error

### ISSUE THREAD

**Issue by rchirico** [EnMAP-Box/enmap-box#595]
I am attempting to import EnMAP data using the Import Data algorithm in the EnMAP Box using the metadata XML file associated with the product, but I am encountering errors and not getting any results. Additionally, dragging and dropping the metadata XML file directly from the system file browser onto the EnMAP Box map view area does not seem to work either.

Is it possible that I have missed some installation steps?

Log error message:
Traceback (most recent call last):
File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importenmapl2aalgorithm.py", line 91, in processAlgorithm
root = ElementTree.parse(xmlFilename).getroot()
File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\xml\etree\ElementTree.py", line 1229, in parse
tree.parse(source, parser)
File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\xml\etree\ElementTree.py", line 569, in parse
source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Processing EnMAP\\dims_op_oc_oc-en_700892716_1\\ENMAP.HSI.L2A\\ENMAP-HSI-L2ADT0000036466_01-2023-08-19T11_17_07.010_ritachirico-cat1-A00001-P00302_700892714_722282994_2023-08-25T17_22_07\\ENMAP01-____L2A-DT0000036466_20230819T111707Z_001_V010303_20230825T114211Z\\ENMAP01-____L2A-DT0000036466_20230819T111707Z_001_V010303_20230825T114211Z-METADATA.XML'

Execution failed after 0.02 seconds
----------------------------------------------------------------------------------------------------------------------------------------------

**Comment by janzandr** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'E:\Processing EnMAP\dims_op_oc_oc-en_700892716_1\ENMAP.HSI.L2A\ENMAP-HSI-L2ADT0000036466_01-2023-08-19T11_17_07.010_ritachirico-cat1-A00001-P00302_700892714_722282994_2023-08-25T17_22_07\ENMAP01-____L2A-DT0000036466_20230819T111707Z_001_V010303_20230825T114211Z\ENMAP01-____L2A-DT0000036466_20230819T111707Z_001_V010303_20230825T114211Z-METADATA.XML'

The problem looks familiar and is most likely related to the long path, which seam to cause problems on Windows OS.
Please place the product at a location with shorter path, e.g. 
_E:\Processing EnMAP\ENMAP01-____L2A-DT0000036466_20230819T111707Z_001_V010303_20230825T114211Z_
