### ISSUE TITLE
Drag&drop EnMAP-Box source to QGIS will open the source twice

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#60]
In QGIS 3.26 and Box v3.11

![animation2](https://user-images.githubusercontent.com/45030715/190669062-2f3926c4-1910-48ee-8313-9ff4ffa79a1d.gif)

**Comment by jakimowb** [comment]
related branch: https://github.com/EnMAP-Box/enmap-box/tree/issue_60

**Comment by jakimowb** [comment]
@thielfab note that dragging a layer from the QGIS layer tree awai without ALT means to moving it to somewhere else. On thie QGIS side this is therefore the intended behaviour.
