### ISSUE TITLE
2 Spectral Library windows but only one in the Spectral Libraries Sources menu

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#61]
I have opened 2 Spectral Library windows but only one appears in the Spectral Libraries Sources menu. How
can I define the source for the 2nd spectral library window? or is this so unusual that has not been considered?
![image](https://user-images.githubusercontent.com/6074054/190692735-16e12731-db8a-487c-8a81-d99a40344a34.png)

**Comment by janzandr** [comment]
Use this button:
![image](https://user-images.githubusercontent.com/45030715/190714187-fa65e787-b8f9-4ac1-a25f-9bba3b1c99fd.png)

Select the second library here:
![image](https://user-images.githubusercontent.com/45030715/190714313-32539de9-22b5-4865-ab35-2586232d7d20.png)
