### ISSUE TITLE
ValueError: node array from the pickle has an incompatible dtype

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#614]
Using Python 3.10+ and numpy 1.24.4+, several unit tests fail due to `ValueError: node array from the pickle has an incompatible dtype`

In case the mentioned pickle files have been created with older numpy versions, this might be related to now deprecated type descriptions (#604).

For example:

```
FAILED tests/enmap-box/enmapboxprocessing/algorithm/test_ClassificationWorkflowAlgorithm.py::TestClassificationAlgorithm::test - _core.QgsProcessingException: Traceback (most recent call last):
  File "/home/jakimowb/.local/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/jakimowb/repositories/enmap-box/enmapboxprocessing/algorithm/fitclassifieralgorithmbase.py", line 94, in processAlgorithm
    dump = ClassifierDump(**Utils.pickleLoad(filenameDataset))
  File "/home/jakimowb/.local/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/jakimowb/repositories/enmap-box/enmapboxprocessing/utils.py", line 651, in pickleLoad
    return pickle.load(file)
  File "sklearn/tree/_tree.pyx", line 714, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1418, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]

```

**Comment by janzandr** [comment]
Shall we have multiple PKL files and a version check in the unittests?
Any other suggestions?

**Comment by jakimowb** [comment]
Explicit version checks would required that we always know which python - numpy - sklearn combination works with which pkl. This causes a lot of work that has to be repeated to account for future changes in numpy / sklearn data structures.

Therefore I'd prefere a generic approach that in principle runs in different environments. During the repository setup (`enmap-box\scripts\setup_repository.py`), PKLs could be generated from the (static/package-independent) training data. I remember that we had a processing algorithm that generated testdata based on the example data. Similar, PKLs (and checksum) could be generated in such an initial setup step well.

**Comment by janzandr** [comment]
Or we haven't any PKL files prepared upfront. Each PKL is created by the test itself. Pretty mach as you suggested by using the setup_repository.py, but now the test is responsible. Of course, we will have a auxCreatePklXYZ helper routine for that. This way I can have a single repo on my system, that works with different QGIS environments, without the need to always call setup_repository.py before switching environments.

**Comment by DevMahmoud10** [comment]
I got the same issue recently sense I had .pkl file loaded by sklearn==0.24 and can't be loaded using sklearn==1.42.1.

I came up with two solutions:

1- re-train the ML model and produce new one with newer sklearn. (which wasn't a convenient solution currently, sense it's require going through the full ML cycle)

2- Write a script to deserialize the old .pkl file and handle the mismatches, load it, then produce it again using newer sklearn. (which is preferred short, and one-time solution, but may not be a long term sense ML models usually require re-training to fix model performance decay).



here is my running script I used you may be need build something similar: 
```
NEW_NODE_DTYPE = np.dtype({
    'names': [
        'left_child', 'right_child', 'feature', 'threshold', 'impurity',
        'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left',
    ],
    'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'],
    'offsets': [0, 8, 16, 24, 32, 40, 48, 56],
    'itemsize': 64,
})


class _CompatUnpickler(pickle._Unpickler):
    """Fixes sklearn Decision Tree pickles saved before sklearn 1.3.

    sklearn 1.3 added `missing_go_to_left` to the tree node dtype.
    Old pickles lack this field and fail to load on sklearn >= 1.3.
    """

    def load_build(self):
        stack = self.stack
        state = stack[-1]
        inst = stack[-2]
        try:
            from sklearn.tree._tree import Tree
            if (
                isinstance(inst, Tree)
                and isinstance(state, dict)
                and 'nodes' in state
                and 'missing_go_to_left' not in state['nodes'].dtype.names
            ):
                old = state['nodes']
                new_nodes = np.zeros(len(old), dtype=_NEW_NODE_DTYPE)
                for name in old.dtype.names:
                    new_nodes[name] = old[name]
                stack[-1] = {**state, 'nodes': new_nodes}
        except Exception:
            pass
        super().load_build()


def _compat_pickle_load(f):
    return _CompatUnpickler(f).load()

```
