### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'showProcessingAlgorithmDialog' 

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#62]
# Error

The following error occurs when using EnMAP-Box processing algorithms without having startet the EnMAP-Box GUI.

````python
AttributeError: 'NoneType' object has no attribute 'showProcessingAlgorithmDialog' 
Traceback (most recent call last):
  File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\parameter\processingparameterpicklefileclassificationdatasetwidget.py", line 127, in onCreateClicked
    enmapBox.showProcessingAlgorithmDialog(alg, modal=True, wrapper=AlgorithmDialogWrapper, parent=self)
AttributeError: 'NoneType' object has no attribute 'showProcessingAlgorithmDialog'
````

# How to replicate

1. Do _not_ start the EnMAP-Box GUI
2. Open Processing Toolbox
3. Open EnMAP-Box > Classification > Classification Workflow algorithm
4. Select any of the customized input options: 
   ![image](https://user-images.githubusercontent.com/1404870/190841374-8092beae-a645-48fd-ab00-68f1b8b47b1f.png)

# Version

EnMAP-Box 3.10.3

**Comment by janzandr** [comment]
https://bitbucket.org/hu-geomatics/enmap-box/issues/1314/create-dataset-shortcut-from-within-fit

**Comment by jakimowb** [comment]
The bitbucket issues mentions:

> We decided to just show a message to the user, that the EnMAP-Box needs to be opened manually.

As this message is still not shown we need to consider this issue still as not resolved.

**Comment by janzandr** [comment]
The was reported on 3.10.3. Should be fixed already on dev.
Have you tested on dev?

**Comment by janzandr** [comment]
Already fixed. Reopen if required.

**Comment by jakimowb** [comment]
good work
