### ISSUE TITLE
[QPS readENVIHeader] reading header file fails if binary file isn't available

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#622]
Reading a header file fails, if the binary file is missing or if the binary file is not a speclib.

```
from enmapboxtestdata import enmap_berlin
print(readENVIHeader(enmap_berlin.replace('.bsq', '.hdr')))
```
Prints:
`None`

Would be much better, if the binary file would be just ignored.
Reading an ENVI header shouldn't be dependent on the binary file.

**Comment by jakimowb** [comment]
Basically that is what I expect from a function below the namespace "speclib.io", but I understand what you mean and created

https://github.com/EnMAP-Box/qgispluginsupport/issues/19
