### ISSUE TITLE
remove DEBUG messages

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#63]
![image](https://user-images.githubusercontent.com/45030715/190964913-dcd40825-5a6d-4a0a-842a-b9b77b9b45a6.png)

**Comment by jakimowb** [comment]
Do these messages still appear even with disabled "DEBUG" variable (e.g. "DEBUG=False")? If not, you might close this issue.

**Comment by janzandr** [comment]
Not sure what you mean with: **_disabled "DEBUG" variable (e.g. "DEBUG=False")_**
Those debug messages appear inside QGIS.
Where would the user set DEBUG=False?

**Comment by janzandr** [comment]
For example, if you open the Layer Properties:
![image](https://user-images.githubusercontent.com/45030715/193153653-63f8e8d7-aea2-4ca2-bbf3-3f5a2800167a.png)

**Comment by jakimowb** [comment]
> Where would the user set DEBUG=False?

Everywhere where it is possible to modify environmental variables, e.g. the python shell, startup scripts, or Settings > System.
