### ISSUE TITLE
[Spectral Processing] Python crashes when selecting "Translate raster layer"

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#645]
Reproduce with the following setup:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/00a70438-8a92-45e1-910e-250677161f40)

Gives Python crash:
`Process finished with exit code -1073741819 (0xC0000005)`

**Comment by jakimowb** [comment]
Cannot reproduce. Please report your QGIS version.

**Comment by janzandr** [comment]
![animation29](https://github.com/EnMAP-Box/enmap-box/assets/45030715/1e7d0502-40e0-4919-a91f-3cf5f63a8505)

**Comment by janzandr** [comment]
@jakimowb not sure why you changed assignments. I'll change back, ok?

**Comment by jakimowb** [comment]
ok, I can reproduce it now
