### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by xiaokaichen1111** [EnMAP-Box/enmap-box#654]
ModuleNotFoundError: No module named 'lmuvegetationapps.Processor.modAL'

**Comment by xiaokaichen1111** [comment]
How to installl lmuvegetationapps.Processor.modAL

**Comment by xiaokaichen1111** [comment]
<img width="960" alt="image" src="https://github.com/EnMAP-Box/enmap-box/assets/84078930/30f08266-fe18-481e-9183-baf853d785a3">

**Comment by janzandr** [comment]
Have you restarted QGIS after installation/updating of the EnMAP-Box?

**Comment by xiaokaichen1111** [comment]
yes,but when I try to use ANN to train,the error start like that.

**Comment by janzandr** [comment]
What are the steps to reproduce the error?

**Comment by xiaokaichen1111** [comment]
I followed the video tutorial to import the EnMAP image, created the lookup table, and then clicked on the ANN training data. The problem occurred, as shown on the above page

**Comment by xiaokaichen1111** [comment]
<img width="963" alt="image" src="https://github.com/EnMAP-Box/enmap-box/assets/84078930/f34b6654-4e07-4548-8605-7505c2f95ed2">

**Comment by janzandr** [comment]
Thanks @xiaokaichen1111, I think I found the problem.

@Maesiu, in the current dev version, you have incorrect import statements:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/418a26d0-c39b-465c-aa86-3e92337d97cf)

**Comment by janzandr** [comment]
You could, as a workaround, install the stable version v3.12 of the EnMAP-Box, where the app should wor.k

**Comment by xiaokaichen1111** [comment]
thank you very much.

**Comment by xiaokaichen1111** [comment]
<img width="867" alt="image" src="https://github.com/EnMAP-Box/enmap-box/assets/84078930/2346467c-b02c-4511-a1c0-c64e74941a6a">
Also a problem, the selection band is gray,I cant't choose the band conbination I want when input EnMAP.  but when it is Sentinel-2A,it's OK.Thanks for your reply.

**Comment by Maesiu** [comment]
The wrong import is already fixed in my fork branch 'develop_matthias'. If present, delete all imports of any modAL package.

**Comment by janzandr** [comment]
@Maesiu, I deleted both imports. Hope that solves the problem.
