### ISSUE TITLE
display something

### ISSUE THREAD

**Issue by xiaokaichen1111** [EnMAP-Box/enmap-box#655]
![image](https://github.com/EnMAP-Box/enmap-box/assets/84078930/f98c4d72-2e8c-4f14-a9d8-8502388318b4)
Also a problem, the selection band is gray,I cant't choose the band conbination I want when input EnMAP. but when it is Sentinel-2A,it's OK.Thanks for your reply.

**Comment by janzandr** [comment]
Have you used the EnMAP L2A Import algorithm? Or have you opened the original spectral image?

**Comment by xiaokaichen1111** [comment]
<img width="755" alt="image" src="https://github.com/EnMAP-Box/enmap-box/assets/84078930/95bd53c9-012d-433d-b7e5-1ef78223a6c6">
Yes，I input like this.Then  algorithm start.

**Comment by janzandr** [comment]
This is the correct algorithm:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/72216acd-2f0f-4143-941d-c69aa81d1527)

**Comment by xiaokaichen1111** [comment]
Thank you so much.

---- Replied Message ----
From Andreas Janz ***@***.***> Date 09/28/2023 14:58 To EnMAP-Box/enmap-box ***@***.***> Cc xiaokaichen1111 ***@***.***>,
Author ***@***.***> Subject Re: [EnMAP-Box/enmap-box] display something (Issue #655)  

This is the correct algorithm:
