### ISSUE TITLE
Plot variance vs. components in PCA

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#668]
How can I inspect (and plot) the % variance of each component in PCA?
I suspect this information is within the pkl file, but do not know how to extract it.

**Comment by janzandr** [comment]
I would suggest to convert the PKL into JSON:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/a0aed2ab-3501-4442-845d-218d2b18b208)

Now you can search for "explained_variance" inside your text editor:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/c02f60c1-e2b6-48cf-91e3-d42e18d3d61a)

Plotting the data is currently not possible.

**Comment by janzandr** [comment]
@aloboa how about a "Plot values" button, that lets you plot any list of values inside a model?

**Comment by janzandr** [comment]
Alright, I added the "Plot values" option, which will produce a plot like this:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/fd768779-6c8f-4f5b-9c65-454fa38e3f04)

**Comment by aloboa** [comment]
The usual plot is the % cumulative variance, eg.
https://www.researchgate.net/profile/Gianluca-Stringhini/publication/317578518/figure/fig2/AS:505452963090432@1497520785536/The-cumulative-sum-of-PCA-components-variance-quantity-The-first-component-already_W640.jpg

perhaps using the explained_variance_ratio from the pkl.

At some point, someone (you?) mentioned a tool to explore pkl files, but I understand there are too many different pkl types.

**Comment by janzandr** [comment]
> perhaps using the explained_variance_ratio from the pkl.

I guess that is the item you want to plot.

The feature_importance_ plot from above was just an example. The "Plot values" option will work for every list of values.

**Comment by janzandr** [comment]
> At some point, someone (you?) mentioned a tool to explore pkl files, but I understand there are too many different pkl types.

The tool to explore PKL file content is the Data Sources panel. Do you miss something in the panel?

**Comment by aloboa** [comment]
> Do you miss something in the panel?

Hold on. I have a problem with my system => cannot install last QGIS version => cannot install last EnMapBox

**Comment by janzandr** [comment]
I don't see a general solution for better showing/highlighting the important items like e.g. _explained_variance_.
An individual solution could be, that each learner can report it's most important information. Here we would need to hard code, which information should be presented.
I would propose to have a "summary" item inside the PKL, summarising such information, e.g. here:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/e524a43a-e8d5-45e1-9082-75474028583a)

**Comment by janzandr** [comment]
@aloboa could you make a list of items that you want to see for the PCA tranbsformer?

- explained_variance
- ...

**Comment by janzandr** [comment]
Looks like this:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/b3fb57d5-641a-4b5f-ac68-e012166ff142)

**Comment by aloboa** [comment]
> I don't see a general solution for better showing/highlighting the important items like e.g. _explained_variance_. An individual solution could be, that each learner can report it's most important information. Here we would need to hard code, which information should be presented. I would propose to have a "summary" item inside the PKL, summarising such information, e.g. here: ![image](https://user-images.githubusercontent.com/45030715/274498836-e524a43ae8d5-45e1-9082-75474028583a.png)

I think that the main problem to inspect a pkl is that they are presented totally collapsed and in the by default very narrow window:

![image](https://github.com/EnMAP-Box/enmap-box/assets/6074054/ef1b1c28-0072-431d-b1cc-9d4addea7fbc)

If the user could just right-click on the pkl and open on a similar window but with only that pkl, an appropriate (much wider) size, and some unfolding, inspecting the pkl would be much more intuitive:

![image](https://github.com/EnMAP-Box/enmap-box/assets/6074054/44d90511-cd86-4570-a54c-4f9de2e8dc5f)

**Comment by aloboa** [comment]
> @aloboa could you make a list of items that you want to see for the PCA tranbsformer?
> 
>     * explained_variance
> 
>     * ...

That would be it, but the plot of the cummulative % of variance is more useful (you normally want to select the number PCs required for a given % of variance).

**Comment by janzandr** [comment]
> I think that the main problem to inspect a pkl is that they are presented totally collapsed and in the by default very narrow window
...
If the user could just right-click on the pkl and open on a similar window but with only that pkl, an appropriate (much wider) size, and some unfolding, inspecting the pkl would be much more intuitive:

@jakimowb, sounds not too complicated. Could you show the PKL node in a new window with the same functionality? Or is that more complicated?

**Comment by janzandr** [comment]
> > @aloboa could you make a list of items that you want to see for the PCA tranbsformer?
> > ```
> > * explained_variance
> > 
> > * ...
> > ```
> 
> That would be it, but the plot of the cummulative % of variance is more useful (you normally want to select the number PCs required for a given % of variance).

Alright, **explained_variance_ratio_** is now exposed inside the summary node.
