### ISSUE TITLE
[PIP Package Installer] is broken

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#671]
_Reported by Martin Trauth via email._

The dialog isn't started. Instead, a new QGIS instance is started.

![animation31](https://github.com/EnMAP-Box/enmap-box/assets/45030715/9dcb6e72-965f-4d16-896c-7f0d5547ffdb)

The second QGIS instance shows an errors:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/695049d6-f1c4-4f42-aa58-fa85aca12700)

**Comment by jakimowb** [comment]
OS + installation | QGIS | EnMAP-Box | Error? | Notes
-- | -- | -- | -- | --
Ubuntu 22.04.3 LTS + conda-forge | 3.32.2 | 3.13.0 | no | [enmapbox_light_latest.yml](https://github.com/EnMAP-Box/enmap-box/blob/main/.env/conda/enmapbox_light_latest.yml) [1] 
Ubuntu 22.04.3 LTS + conda-forge | 3.28.11 | 3.13.0 | no | [enmapbox_light_latest.yml](https://github.com/EnMAP-Box/enmap-box/blob/main/.env/conda/enmapbox_light_longterm.yml) [1] 
Win11 + OSGeo4W | 3.34 | 3.13.0 | -- | other error
Win11 + OSGeo4W | 3.28 | 3.13.0 | yes | starts a new QGIS instance


[1] as now QGIS 3.32 is the latest [conda version ](https://github.com/conda-forge/qgis-feedstock)

**Comment by jakimowb** [comment]
Reason found: 
`return pathlib.Path(sys.executable).resolve()` returns path to windows qgis.exe instead python.exe
