### ISSUE TITLE
Classification toolbox parameters broken

### ISSUE THREAD

**Issue by jmrallen** [EnMAP-Box/enmap-box#680]
It appears that the classification parameters window is no longer working. It appears as: 
![image](https://github.com/EnMAP-Box/enmap-box/assets/84196838/f2636fa5-f2fd-4754-964c-ad17fece5ef5)

The documentation shows it should appear as:
![image](https://github.com/EnMAP-Box/enmap-box/assets/84196838/c28764e1-44e3-427c-aaf2-70aa1a99c7cf)

**Comment by janzandr** [comment]
Yes, the docs are slightly outdated. We now support various ways for preparing the training data:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/25b3b76f-c3b7-4b25-a944-84084041f623)
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/9bf30277-0a4a-4634-aa58-cb42740505c1)

Here is a video with an example classification workflow:
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/applications.html#classification-workflow

**Comment by janzandr** [comment]
@thielfab would be good, if you could update the screenshot in RTD.
