### ISSUE TITLE
add dual-band pseudocolor renderer

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#70]
In analogy to the **Singleband-Pseudocolor-Renderer**, which is using a 1d color ramp, implement a new **Dualband-Pseudocolor-Renderer**, that visualizes two raster bands using a 2d color plane.

In a first version of the GUI, allow to define the 2d color plane, by defining the 4 corner colors, e.g.
![image](https://user-images.githubusercontent.com/45030715/191892438-30e7d70f-8c09-448d-9425-f928ae4ccb42.png)

Use this code snippet to generate the color plane from the 4 colors:
```
import numpy as np

im=(np.random.rand(2,2,3)*255).astype(np.uint8)

from scipy.ndimage.interpolation import zoom
zoomed=zoom(im,(128,128,1),order=1)
```

**Comment by janzandr** [comment]
First GUI version looks like this:
![image](https://user-images.githubusercontent.com/45030715/192080466-7fa1f33a-23d6-42b2-9960-d40beea87352.png)

**Comment by janzandr** [comment]
I think we need a better name like: _Bivariate-band pseudocolor renderer_
@jakimowb , @thielfab , @aloboa any suggestions?

**Comment by jakimowb** [comment]
DoubleBandPseudoColorRenderer

**Comment by thielfab** [comment]
In vector land I think bivariate [...] (as Andreas suggested) is the right term for this https://pro.arcgis.com/en/pro-app/latest/help/mapping/layer-properties/bivariate-colors.htm

**Comment by aloboa** [comment]
I think Bivariate pseudocolor (or just Bivariate color) renderer is sufficient, Bivariate-band is redundant.
