### ISSUE TITLE
split and restructure the requirement.txt file by operating system and Python environment

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#701]
_Discussed with @jakimowb._

Currently we have a single _requirements.txt_ file for all OS and Python environments. This is kind of risky and created problems in the past, e.g. a Windows user PIP-installed numpy inside his user directory, which shadowed the OSGeo4W version of numpy.

It is proposed to have a custom _requirements.txt_ file for each OS/Python-Env combination, that we want to support:

- [x] Windows / OSGeo4W
- [x] Windows / Mambaforge|Conda
- [x] Linux...
- [x] MacOS...

@jakimowb I would suggest, that I kick-off with Windows, we discuss and reiterate until we like it, and afterwards you can take over and follow-up with Linux and MacOS.

This issue is related to https://github.com/EnMAP-Box/enmap-box-documentation/issues/48.

**Comment by janzandr** [comment]
Windows / OSGeo4W requirements.txt is placed here:
https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/requirements_osgeo4w.txt

**Comment by janzandr** [comment]
Windows / Mambaforge doesn't require extra PIP packages

**Comment by janzandr** [comment]
@jakimowb you can take over and follow-up with Linux and MacOS.

**Comment by jakimowb** [comment]
closes by https://github.com/EnMAP-Box/enmap-box-documentation/pull/70
