### ISSUE TITLE
EnmapBox cannot be installed through flatpack

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#707]
Please see
https://github.com/flathub/org.qgis.qgis/issues/370

This issue is not being taken care of and I understand if you cannot fix it. In that case, please remove the mention of flatpack in your Installation directions for linux:
"This also applies if you installed QGIS using flatpak, in that case install python modules as described [here](https://qgis.org/de/site/forusers/alldownloads.html#flatpak)

Also, note that your current QGIS installation instructions do not mention flatpack.

**Comment by janzandr** [comment]
Thanks @aloboa, @jakimowb is currently rewriting the Linux installation instructions and will take care of it.

**Comment by aloboa** [comment]
Is this going to be fixed?

**Comment by janzandr** [comment]
Installation guide is now revised:
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation.html#qgis-installation-on-linux-ubuntu
