### ISSUE TITLE
EnMAP Box on QGIS, stalling on opening at "ensomap"

### ISSUE THREAD

**Issue by jgrn307** [EnMAP-Box/enmap-box#708]
I've done an installation of EnMAP Box on QGIS, with the python packages pre-installed, but after clicking the button it appears to have stalled on "Load EnMAPBoxApplication(s) from "ensomap".  It's been sitting there for about 5+ minutes, and one of the CPU is pegged at 100%.

**Comment by jgrn307** [comment]
Note: by disabling the Google Earth Engine plugin and restarting QGIS, I was able to get EnMAP Box opened.

**Comment by janzandr** [comment]
What happens if you now enable the Google Earth Engine plugin again?

**Comment by jgrn307** [comment]
It worked with both plugins enabled!

**Comment by janzandr** [comment]
Nice
