### ISSUE TITLE
EnMAP-Box on QGIS and loading AVIRIS data

### ISSUE THREAD

**Issue by mohavensis** [EnMAP-Box/enmap-box#710]
I am attempting to use EnMAP-Box on QGIS to load AVIRIS data for an area in Southern California. When I load the data into EnMAP, it does not load properly, merely creates a black or grey screen. I believe that the issue is related to bands and the way that EnMAP reads in the bands for the file, but I am fairly new to remote sensing and EnMAP and am not sure. 

This is the download link for the file that I am attempting to load: https://popo.jpl.nasa.gov/avcl/y17_data/f171204t01p00r18.tar.gz

I appreciate any and all help!

**Comment by janzandr** [comment]
QGIS seams to have performance issues rendering the image because of the rotation.
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/c77f3165-8089-4173-b157-d9681068a2f1)

If you delete the rotation in the header, it works:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/a692e9d5-0f7d-4561-82bc-c9c859e012b1)

**Comment by janzandr** [comment]
Also note the syntax error in the header:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/8e7631e6-81d9-458c-9d8d-582180ee1917)

Should rather look like this:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/9eb8714a-d35b-4474-94d4-f506e6f2563a)

**Comment by janzandr** [comment]
Hmm, I can open the image in ENVI, but the 90° rotation also isn't applied:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/6ed18c16-f669-4ba1-a755-0959d3d5374c)

**Comment by janzandr** [comment]
So basically, if you delete the rotation in the header you can use the image in QGIS like you would in ENVI.

**Comment by jakimowb** [comment]
@janzandr deleting the rotation in the header may made the image loaded fast, but corrupts the georeferencation of the image.

**Comment by janzandr** [comment]
Deleting the rotation item in the header is only a workround.

**Comment by jakimowb** [comment]
Could be use a VRT to handle such images? The warping by GDAL should be much faster.

**Comment by janzandr** [comment]
Just for my understanding: is this an official Sensor Product provided by NASA?
As mentioned the header has syntax errors.

**Comment by janzandr** [comment]
Workaround: just use gdalwarp on the shell:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/cce75741-1c9a-4ae4-87ca-da1a02d65c9a)

```
D:\QGIS>gdalwarp f171204t01p00r18rdn_e_sc01_ort_img f171204t01p00r18rdn_e_sc01_ort_img_2.bsq -of ENVI -co INTERLEAVE=BSQ
Creating output file that is 4912P x 924L.
Processing D:\data\_test\f171204t01p00r18rdn_e\f171204t01p00r18rdn_e_sc01_ort_img [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
```

**Comment by mohavensis** [comment]
Thank you for your help, I so appreciate it and will implement these solutions.

**Comment by janzandr** [comment]
You are welcome. Also note that we will implement an algorithm, which will make it easier to import rotated images: #711.

**Comment by jgrn307** [comment]
@janzandr can you confirm the AVIRIS wavelength/fwhm info from the header was preserved for use with EnMAP in the warp you ran?

**Comment by janzandr** [comment]
No, GDAL warp won't preserve the metadata. The algo we want to implement (see #711) will take care of the metadata.
