### ISSUE TITLE
[Spectral View] collected pixel profiles aren't showing up inside a map view

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#720]
_Reported by @thielfab via Slack._
How to reproduce:
![animation32](https://github.com/EnMAP-Box/enmap-box/assets/45030715/4d9594da-d973-4685-8bb9-9ffea7dece65)

**Comment by thielfab** [comment]
It seems that the CRS of the speclib layer defaults to epsg:4326, whereas the coordinates are recorded based on the raster layer CRS. Hence, the CRS of the speclib layer has to be changed manually (in the above case to epsg:32633).

**Comment by janzandr** [comment]
> Hence, the CRS of the speclib layer has to be changed manually (in the above case to epsg:32633).

I don't think that the user should manually change the speclib CRS.
Imagine the usecase, where a user collects profiles from to different raster layers with two different CRS.
The solution is to translate the raster CRS coordinates into speclib CRS coordinates.

**Comment by jakimowb** [comment]
Coordinate should generally translated into the speclib crs. I just wonder why this is not already the case?
