### ISSUE TITLE
Issues with applying unmixing algorithms to Level-2A product

### ISSUE THREAD

**Issue by unanduwa** [EnMAP-Box/enmap-box#723]
The problem I'm facing is not related to the EnMAP Box but rather pertains to hyperspectral unmixing. I obtained a Level-2A product from https://eoweb.dlr.de/egp/main, but it doesn't contain bottom-of-atmosphere (BOA) reflectance values ranging from 0 to 1. Instead, it has very large values in both positive and negative directions, causing issues when applying hyperspectral unmixing algorithms like VCA. Are there additional preprocessing steps that should be undertaken? I apologize if this is not the appropriate forum for such queries, and I would appreciate any guidance on where to address this issue.

**Comment by janzandr** [comment]
For L2A products, you have to apply the data gain factor (0.0001) to the data.

**Comment by unanduwa** [comment]
I am not talking about how to properly convert a Level-1B product to a Level-2A. I am inquiring about what to do to an already existing Level-2A product that I downloaded from https://eoweb.dlr.de/egp/main . So how should I apply the data gain factor (0.0001) to an already existing Level-2A product?

**Comment by unanduwa** [comment]
> For L2A products, you have to apply the data gain factor (0.0001) to the data.

I am not talking about how to properly convert a Level-1B product to a Level-2A. I am inquiring about what to do to an already existing Level-2A product that I downloaded from https://eoweb.dlr.de/egp/main . So how should I apply the data gain factor (0.0001) to an already existing Level-2A product?

**Comment by janzandr** [comment]
In the EnMAP-Box, you can use the **Import EnMAP L2A product** algorithm.
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/processing_algorithms/import_data/import_enmap_l2a_product.html
