### ISSUE TITLE
[Regression layer accuracy report] scatter plot figures not shown in report

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#727]
_Reported by Kathrin Wart via Email._

![hGmSNHD97t0J1Mj0](https://github.com/EnMAP-Box/enmap-box/assets/45030715/33e61c69-276a-4c95-84ba-d827b1564226)

**Comment by jakimowb** [comment]
This issue could be used to give these reports a post-1990 style using a sans-serif fonts (arial/calibri)

**Comment by janzandr** [comment]
> This issue could be used to give these reports a post-1990 style using a sans-serif fonts (arial/calibri)

@jakimowb, I'm not sure what you mean... sounds like a seperate feature request to me (???)

**Comment by janzandr** [comment]
The problem seams to only occure in Firefox webbrowser.

**Comment by janzandr** [comment]
When using relative filenames for the images it works.
