### ISSUE TITLE
[Spectral View] GeoJSON library not correctly visualized

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#731]
Here is the new example library prepared by @carlstadie:
[library.zip](https://github.com/EnMAP-Box/enmap-box/files/13476273/library.zip)

JSON file looks good...
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/550862b5-18c7-4dc6-9d0c-4b368596bf8f)

... but profiles aren't plotted:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/1f39614f-bcdc-4efb-8cec-ef57396228c2)

**Comment by jakimowb** [comment]
Seems to be QGIS issue. QgsVectorLayer / QgsFeatures do not return JSON field values, while ogr Layers do.

**Comment by janzandr** [comment]
Not sure if that helps, but if you use one of the SpectralResponseFunction libraries, it works fine:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/04d8fb88-126d-4884-917d-5e77ce46bf62)
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/105a7468-c9df-42d7-a30c-1b46ae1918a0)

**Comment by jakimowb** [comment]
Are these ".geojson" valid according to [RFC7946](https://datatracker.ietf.org/doc/html/rfc7946)?

**Comment by jakimowb** [comment]
GeoJSON does not accept NaN values:
https://stackoverflow.com/questions/66683007/how-to-handling-nan-values-while-creating-a-geojson

**Comment by jakimowb** [comment]
@carlstadie how did you create these libraries? The `NaN` values need to be replaced with `null`.

**Comment by carlstadie** [comment]
They were created using the latest version of the EnMAP Box unsing the Identify pixels and add tem to the library. I then exported everything using the export option. GeoJSON was the default. I am not quite shure how NaN values got mixed in there. I can do everything again and export it as a Geopackage if that might help.

**Comment by janzandr** [comment]
@jakimowb I would suggest to keep the issue open until it is fixed in QPS.
