### ISSUE TITLE
[Data Views] spectral view layer legend not correctly updated

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#737]
_Reported by Sebastian van der Linden via email._

Given a speclib, which is also added to a map view: after styling the speclib layer, the layer legend of the map view is correct, but the layer legend of the spectral view is not updated:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/43567c8b-bafd-4854-9e28-6c1750ab640c)

**Comment by jakimowb** [comment]
Won't change. The Spectral View and thus it's legend is to show profiles, not geometries. Therefore it does not make sense to show a detailed geometry legend here. Instead it would be good to summarize the legend from the plot settings here or add checkboxs that trigger Spectral View subwidgets, like
* [ ] Plot Window
* [ ] Plot Settings
* [ ] Attribute Table
* [ ] Attribute Form

**Comment by janzandr** [comment]
I don't know, for me it still looks like a bug.
If I open **/enmap-box/tests/testdata/library/library.gpkg as Spectral Library**, I get a very detailed legend:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/4b6534bf-9b68-49fb-bc4a-db2225bcf189)

I can also change the styling and the legend is updating correctly:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/c4ba72b8-c796-45a7-9c67-4064827812f4)

BUT, if I now add the library to a map view and change the styling, the legend isn't updated correctly anymore:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/b20d6271-e9b1-425c-8d43-5050693878fb)

**Comment by jakimowb** [comment]
The described behavior  is caused by the implementation of

```cpp
void QgsLayerTreeModel::refreshLayerLegend( QgsLayerTreeLayer *nodeLayer )
{
  // update title
  QModelIndex idx = node2index( nodeLayer );
  emit dataChanged( idx, idx );

  // update children
  int oldNodeCount = rowCount( idx );
  if ( oldNodeCount > 0 )
  {
    beginRemoveRows( idx, 0, oldNodeCount - 1 );
    removeLegendFromLayer( nodeLayer );
    endRemoveRows();
  }

  addLegendToLayer( nodeLayer );
  int newNodeCount = rowCount( idx );

  // automatic collapse of legend nodes - useful if a layer has many legend nodes
  if ( mAutoCollapseLegendNodesCount != -1 && oldNodeCount != newNodeCount && newNodeCount >= mAutoCollapseLegendNodesCount )
    nodeLayer->setExpanded( false );
}

```
A change of the layer style becomes visible in top-most legend node related to only.
Opening a Spectral Library View first and the Map view aftwerwards will lead to legend updates in the Spectral Library View legend.

![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/0f4c7bb6-00b6-48f9-8701-3767e2200f2e)

**Comment by janzandr** [comment]
Alright

**Comment by jakimowb** [comment]
@janzandr @thielfab this is an example how the different subviews in the Spectral Library View could become triggered from the Data view panel using checkboxes. 

![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/f4f038c9-3fad-4d59-a264-993a84d29808)

However, probably theses just occupy too many space. What do you think?

https://github.com/EnMAP-Box/enmap-box/assets/1404870/6cd43d4e-1180-4c4a-be8d-949fa4f49900

**Comment by janzandr** [comment]
> However, probably theses just occupy too many space. What do you think?

I'm undecided. Probably a good idea. But yes, if occupies some space.
