### ISSUE TITLE
Notes on EnGeoMAP

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#746]
* Update doc to 3.2 version.

* (optionally) output continuum removed spectra. Actually, an independent tool for this purpose (or just the option to stop the processing here) would be greattly appreciated.

* (optionally) output spectral features. Actually, an independent tool for this purpose (or just the option to stop the processing here) would be greattly appreciated.

* Are the output fitting correlation scores the ¨fit values¨ mentioned in the 1st paragraph of section 4? 

* Explain the conceptual differences among
cubus_gamsberg_bvls_unmixing_scores
and
cubus_gamsberg_feature_fitting_correlation_scores
and
cubus_gamsberg_bvls_unmixing_highest_abundance_result

* cubus_gamsberg.hdr has 
wavelength units = Unknown
which conflicts with what is stated in Data Preparation and Requirements, and precludes the display of enmapbox spectra along wavelength.

**Comment by hdaemp** [comment]
Just updated the docs to Version 3.2. The renamed data products and scores  are now explained and new test data was linked.
Pull requests are open.
