### ISSUE TITLE
 "Regression-based unmixing (synthMix)" gone?

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#748]
Section "Exercise D: Regression-based unmixing" under Application Tutorials
refers to  "Regression-based unmixing (synthMix)" which is not present in the current
version 3.12.1 . The current  "Regression-based unmixing" looks pretty different
from what is seen in the figure under ¨2. Start the application¨

**Comment by janzandr** [comment]
Yes, the old (hand made) GUI was transfered into a processing algorithm. New and old functionality should roughly match.

**Comment by janzandr** [comment]
FYI: the tutorial was updated recently: 
https://enmap-box.readthedocs.io/en/latest/usr_section/application_tutorials/urban_unmixing/tutorial.html
