### ISSUE TITLE
[Spectral View] "Automatically pan to current feature" in isn't working in Form View

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#750]
_Reported by @thielfab via email._

The "Pan map to selected rows" in the Spectral View toolbar is working as expected.
But the "Automatically pan to current feature" in the Form View isn't working.
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/3f89ada4-2117-45cb-8a47-7fcb9623608b)

**Comment by jakimowb** [comment]
wont fix this, as the button / action is not exposed to PyQGIS.
