### ISSUE TITLE
[Spectral View] better support for vector-layers without proper QML sidecar file

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#755]
In cases where the speclib is crafted outside of QGIS/EnMAP-Box, e.g. by using simple scripting in R/Python or by editing inside a text editor, the QML file is missing.
When openening such files inside the EnMAP-Box, the Speclib View isn't recognising the existing profile fields.
E.g. in this GeoJSON speclib we have a field "response", which can be easily recognized as a properly formatted profile field:

[speclib.zip](https://github.com/EnMAP-Box/enmap-box/files/13702445/speclib.zip)

![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/d408f7bf-f0af-4de7-915d-6e41e6514777)

![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/0ba1fed2-af48-425c-8d7d-3e03763d0723)

It is proposed to automatically find proper profile fields.

**Comment by jakimowb** [comment]
closed by #794
