### ISSUE TITLE
[GDAL Metadata] rename "Range" band property to "Wavelength Range"

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#757]
Hi @jakimowb, I would like to propose to change the "Range" to "Wavelength Range", to make it clearer, what this is about.
One could also think that we are talking about "Data Range".
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/62a44a98-724e-48d5-b37a-13f7863daf64)

Currently it is not very critical, but after we added temporal properties like "datetime" and "datetime **range**", it would be good to explicitely name the different types of ranges.

**Comment by jakimowb** [comment]
Agreed
