### ISSUE TITLE
add algorithm for scaling/converting raster data

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#765]
_Discussed with Akpona._

It is proposed to implement an algorithm for basic data preparation:

- scale data
- convert data type
- recode noDataValue
- truncate data to a min-max range

**Comment by jakimowb** [comment]
Isn't it all already covered by `native:rescaleraster` and `gdal:translate`?

**Comment by janzandr** [comment]
Yes, all the basic functionality is already covered somewhere else, but all those tools/algos didn't value the metadata. 
For example, when your wavelength information is missing after scaling a hyperspectral raster, you have another problem.
