### ISSUE TITLE
[Cursor location values panel] category color and name isn't shown for last category

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#775]
_Reported by Sebastian van der Linden._

When selecting a pixel in a classified image, the class color and name is reported, e.g.:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/4f6f992f-bf5a-4eaf-a66e-6c989db10a1d)

However, for the last category, this seems to not work properly:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/fde7449d-a339-4199-9b47-4d7e9f9324b0)

**Comment by jakimowb** [comment]
@janzandr can you share an example image or some code that generate the classification layer (raster + *.qml) to reproduce this?

**Comment by janzandr** [comment]
I observed this with every classification raster I tested. E.g. one of our testdata:
tests/testdata/raster/landcover_map_l3.tif

**Comment by jakimowb** [comment]
arg. I have mixed up #755 and #775. Nevertheless, both are closed now
