### ISSUE TITLE
[Spectral View] find SpectralProfile attributes automatically

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#778]
_Discussed with Sebastian van der Linden and @jakimowb._

It is proposed to automatically find all attributes with profile data, when opening a vector layer that hasn't explicitly defined SpectralProfile attributes. Just check the first feature.

This issue is related to #758.

**Comment by janzandr** [comment]
Additional suggestions/notes by @jakimowb via Email: 
> - ein Schreiben des qml immer wenn"Save Edits" getriggert wird. Alternativ ein extra "Save" Button
> - einen "Set Profile Fields" Dialog der zeigt, welche Felder SpektralProfile enthalten können oder nicht. Der aktiviert/deaktiviert dann das jeweilige Attribute Widget und könnte auch eine "detect profile fields" Funktion haben."

**Comment by jakimowb** [comment]
https://github.com/EnMAP-Box/qgispluginsupport/issues/31
