### ISSUE TITLE
typeguard.TypeCheckError: argument "maxValue" (None) is not an instance of int

### ISSUE THREAD

**Issue by Danro77** [EnMAP-Box/enmap-box#789]
Hello, 

I am trying to cluster a raster image with the FitKMeans Tool. When the mask is opened and i choose the option "Create Unsipervised Dataset (From Raster Feature)" it gives me the following Python Error:

typeguard.TypeCheckError: argument "maxValue" (None) is not an instance of int 
Traceback (most recent call last):
  File "C:\Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\prepareunsuperviseddatasetfromrasteralgorithm.py", line 52, in initAlgorithm
    self.addParameterInt(self.P_SAMPLE_SIZE, self._SAMPLE_SIZE, 0, True, 0)
  File "C:\Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\enmapalgorithm.py", line 875, in addParameterInt
    def addParameterInt(
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\typeguard\_functions.py", line 138, in check_argument_types
    check_type_internal(value, annotation, memo)
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\typeguard\_checkers.py", line 764, in check_type_internal
    raise TypeCheckError(f"is not an instance of {qualified_name(origin_type)}")
typeguard.TypeCheckError: argument "maxValue" (None) is not an instance of int

This error shows up even though i have not chosen my raster yet. 

Thanks in advance!

**Comment by janzandr** [comment]
Can't reproduce this with my testdata. Could be an issue with your data. Please share your files.

**Comment by Danro77** [comment]
I don't think that this error is related to my data. The error shows up in the moment when I clicked "Create Unsupervised Dataset (From Raster Feature)" but have not chosen any data. I assume it could be due to an incorrectly installed python package as it worked before I set up my new computer. I'll try another installation and let you know if that worked out

**Comment by janzandr** [comment]
Which QGIS and EnMAP-Box versions are you using?

**Comment by Danro77** [comment]
I use QGIS 3.30.2 s'Herthogenbosh and (I think) the current Version of the EnMAP-Toolbox (3.13.2). 
But now I am pretty sure it is something with my installation. I simply wanted to change the Band Combination of my Image with the "Raster Layer Styling" and got another Error according to typeguard.

**Comment by janzandr** [comment]
What typeguard version is installed?
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/0fd57361-e234-462d-9c6b-4f4d7f286a43)

**Comment by Danro77** [comment]
So, I was on the current typeguard version (4.1.5). I uninstalled and installed the version you showed in the screenshot. Now it seems to work. Thank you very much!
