### ISSUE TITLE
[Spectral Processing] outputs aren't properly opened inside Data Sources panel and file locations aren't reported in the Log tab

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#798]
For example, when executing "Fit PCA" algo in standard Processing, the output model (PKL file) is opened inside the Data Sources panel: 

![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/9c4d513e-ec39-4146-adca-929fb4d35002)

![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/0bfdd310-3d92-49a8-840d-407b5281c964)

And the actual output location on disk, and all the input parameters, are also reported:

![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/5e1431cc-41cc-40c5-8cdd-8ceeb0d75348)

When running "Fit PCA" via the Spectral Processing...

1. The PKL file isn't shown inside the Data Source panel
2. All the useful information isn't logged:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/944b0202-aacc-46bd-958d-27b0cf806477)

**Comment by jakimowb** [comment]
> The PKL file isn't shown inside the Data Source panel
This ~is~ was caused by #764 (processing algo needs to consider the QgsProject of the active QgsProcessingContext)
