### ISSUE TITLE
outdated version number in splash screen

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#799]
When starting EnMAP-Box 3.14 alpha (current experimental version) ...
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/a74e9a96-a819-4dfb-88a8-2c343ab44939)

... the splash screen shows old 3.13 version number:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/84d92039-6ed3-4d79-95af-c6023fcb4023)

**Comment by jakimowb** [comment]
Please writea unit test to avoid this "bug" in future versions ;-)

**Comment by janzandr** [comment]
Is the version number inside the splash screen manually created? Or do we have a script for that?

**Comment by jakimowb** [comment]
You need to update the *.svg file and export it as *.png
