### ISSUE TITLE
bad behaviour when dropping a raster layer on a map view that has no default style 

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#80]
I would guess, that you try to display band 0, 1, 2, but it should be 1, 2, 3:

![image](https://user-images.githubusercontent.com/45030715/192539424-24d3f971-d387-4c16-af9a-b287972bd076.png)

**Comment by jakimowb** [comment]
relates to #60

**Comment by jakimowb** [comment]
@janzandr can you provide a raster file to reproduce this error? The standard example images seem to work fine.

**Comment by janzandr** [comment]
Still not fixed, at least for this file:
https://nextcloud.uni-greifswald.de/index.php/s/rxP24ajGYgmERC9/download

![image](https://user-images.githubusercontent.com/45030715/194342201-f155a74c-7f47-49a0-96c5-447eec511bb6.png)

**Comment by thielfab** [comment]
RGB visualization works now, but the transparency band is still not set. QGIS does this automatically. Can we reuse this functionality?

**Comment by janzandr** [comment]
Opening a RGBA raster in EnMAP-Box should behave like in QGIS.

**Comment by jakimowb** [comment]
Does anything speaks against using
```
raster_path: str
lyr = QgsRasterLayer(raster_path)
lyr.loadDefaultStyle()
```

as the default way to style raster layers? In the very past there were requests for special handling of contrast enhancement. In case we need something more than what is done by the PyQGIS anyway, I'd like to do it like in the QGIS User Settings:

![grafik](https://user-images.githubusercontent.com/1404870/205104247-960a7e24-5b69-4787-b130-81c41e08875e.png)
