### ISSUE TITLE
Spectral resampling (to Sentinel-2A and B) fails with "failed to open spectral library: 'NoneType' object has no attribute 'source'"

### ISSUE THREAD

**Issue by leleist** [EnMAP-Box/enmap-box#803]
When trying to apply the"Spectral resampling (to Sentinel-2A)" tool on a freshly imported EnMAP L2A tile, I get error: failed to open spectral library: 'NoneType' object has no attribute 'source'. 

The File was successfully imported as an EnMAP L2A product and I can manipulate it freely without any issues in the EnMap Box UI. 
I can recreate it with different tiles and after restarting QGIS and EnMAP Box.

Do you have any idea what exactly causes this issue?
Thanks in advance

**Comment by janzandr** [comment]
Can't replicate this on my system.
1. Please show the full error traceback.
2. Which OS, which QGIS version and which EnMAP version are you using?

**Comment by leleist** [comment]
EnMAP Box: 3.13.2
QGIS: 3.32.1-Lima
Windows 10 22H2

**Comment by janzandr** [comment]
Alright, the bug was already fixed, but not released yet. I uploaded v3.13.3 just now.
https://plugins.qgis.org/plugins/enmapboxplugin/version/3.13.3/
