### ISSUE TITLE
OSGeo4W installation: pip --upgrade installs conflicting numpy / other package versions

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#806]
[reported by nangula]
The installation guide for windows / OSGeo4W in https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation.html 
recommends to run:

`pip install --upgrade --user -r https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt`

This is potentially fatal. An upgrade of a package / package-dependencies may cause an upgrade of numpy, which is added to the users's site-package folder. In that case the new numpy does not match anymore with the binaries installed by OSGeo4W and expected by QGIS, leading to QGIS startup errors, e.g. missing GDAL python libraries.

Solution:
* each package that is maintained by OSGeo4W should be installed and updated by OSGeo4W
* pip should be used for exceptions only, e.g. packages that cannot be installed with OSGeo4W. The update strategy needs to be choosen wisely, e.g. to create conflicts with OSGeo4W packages (See https://pip.pypa.io/en/stable/cli/pip_install/ )
* an additon FAQ descriptions should explains how conflicting packages in the user's site-package folder can be removed.

**Comment by janzandr** [comment]
I can't reproduce the problem.
1. My numpy version is 1.24.1 and the latest version is 1.26.4:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/2980656b-28ea-4c62-9881-aea7c0433e25)
2. I deleted all Python packages from the user folder.
3. I executed the installation command as described in RTD.
4. Everything worked fine. Numpy wasn't upgraded. User folder looks good:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/11d7dc73-5370-4320-a14c-2831a3f1c769)

Everything works as expected.

Please explain step by step how to produce the problem.

**Comment by janzandr** [comment]
FYI @jakimowb, an explicite `pip install --upgrade --user numpy` will install numpy 1.26.4 into the user folder.
Are you really sure, that the user hasn't executed a wrong pip install, where numpy was listed explicitely?
Currently, I'm not convinced, that the install instructions are causing the problem.

**Comment by jakimowb** [comment]
The install instructions already fail if - for what reasons ever - a different numpy is installed to the user folder.
The install instructions need to make sure that user know how in that case to uninstall the wrong numpy.

In general the instructions should make clear - as for other OS: 
1. install packages using the plattform native packager installer first - in this case OSGeo4W
2. use pip only if (1) is not possible.

**Comment by jakimowb** [comment]
relates to #701

**Comment by janzandr** [comment]
Done
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/9c902897-aa12-48b0-999b-c28984b1a617)
