### ISSUE TITLE
Very Slow Opening PRISMA scene

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box#812]
I am running QGIS 3.34 and EnMap 3.103 on a Win10 PC. Loading a scene using the project > add product > L2D is very slow, 5 - 10 minutes. Any suggestions on how to speed this up? This seems to be a recent development and was faster previously. I have done a complete re-install of QGIS recently to clear other python conflict issues so not sure if this has caused problems.

**Comment by thielfab** [comment]
@janzandr correct me if I'm wrong, but I think the import algorithm tries to use the `h5py` package if available. If the package is not available/installed, the algorithm uses GDAL, which can be very slow reading the he5 file. 
Maybe this is related to your other issue #810 and h5py is not installed (correctly)?

**Comment by grantboxer** [comment]
I have h5py installed via the QGIS python console. Is this the correct place?

I get this message when importing a PRISMA file,

Reading data with h5py API failed. Fall back to GDAL API, which is very slow on PRISMA BIP interleaved data: HDF5:"""E:\Dropbox\PRISMA\Panorama_WA\PRS_Panorama_22951\PRS_L2D_STD_20230622022947_20230622022951_0001.he5"""://HDFEOS/SWATHS/PRS_L2D_HCO/Data_Fields/VNIR_Cube

Any thoughts?

**Comment by thielfab** [comment]
In the QGIS Python console, if you enter
`!python3 -m pip list -v`
What does it say for h5py? 
I think sometimes the pip installed version creates problems or will not work, hence it is [advised to install `h5py` using the OSGeo4W installer](https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation.html#install-python-dependencies).

**Comment by grantboxer** [comment]
h5py was not installed, but when I did pip install it, it then causes EnMap-Box to crash and QGIS. There seems to be a python conflict here somewhere.

**Comment by thielfab** [comment]
In that case, try uninstalling it again (using pip). And then install it using the OSGeo4W installer.
This command in the OSGeo4WShell should also do the trick (but first uninstall the pip version):
`setup -qgP python3-h5py`

**Comment by grantboxer** [comment]
How do I uninstall? Is it pip uninstall h5py?

**Comment by grantboxer** [comment]
I deleted the h5py libs from the Python 3.9 installation in the OSGeo4W folder and that seemed to work.

**Comment by grantboxer** [comment]
OK, I have used the "setup -qgP python3-h5py" in the setup and that seems to have installed OK. It now uses the h5py to load the file - much quicker!! Many thanks.

**Comment by thielfab** [comment]
👍 Great!
Yes, `pip uninstall h5py` would have been the right command.

**Comment by thielfab** [comment]
Did that also solve the issue #810 ?
If so, I would close them both. If problems continue to occur you can reopen them any time.

**Comment by grantboxer** [comment]
Yes, seems to be OK now. Not sure why the pip install in the QGIS python window did not work. Anyway, all good now, hopefully!
