### ISSUE TITLE
[Classification layer accuracy and area report] add support for non-matching category names

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#845]
Currently, observed and predicted category names must match. 
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/c02cf189-b42a-4741-8697-aba1f5ebcde4)

E.g. use this setup to reproduce the problem:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/2dbecbd8-de73-4043-884a-bfc95d0a8da1)

It is proposed to soften this restriction a bit, and to also allow category matching by order, if the number of categies is equal.

**Comment by janzandr** [comment]
@jakimowb any remarks from your side?

**Comment by jakimowb** [comment]
It need to be cristal clear which class matching. By now it seems to be on class names only.

![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/871b30df-4ff5-4c73-98b9-d03dcf1116d4)

Optimally the processing algorithm should support the following options:
1. match on class names, e.g. if there is a raster and a reference shapefile with class names
2. match on class numbers
3. match on class order

The final report needs to show this as well, i.e. which used class names + numbers were compared.

**Comment by janzandr** [comment]
Thanks @jakimowb, I will add a description to the docs and add the matching to the report.

**Comment by janzandr** [comment]
FYI @jakimowb, done:
1. Class matching is shown in a table:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/f50e6b76-9443-4a8e-a3cd-b01d1839ce20)

2. For classes that can't be matched by name, a warning is logged:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/1762f848-987e-4440-abfd-a28a3c3d32e3)

3. Improved algo doc:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/a5fea29e-884c-47c5-82e4-9f85a8884776)
