### ISSUE TITLE
SpectralProfile widget type is shown twice

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#86]
Is that a bug?
![image](https://user-images.githubusercontent.com/45030715/192776061-4426bfed-cebd-464b-9328-bb8b0b17b33d.png)

**Comment by jakimowb** [comment]
Can't reproduce. Have you deactivated all other QGIS plugins?

**Comment by janzandr** [comment]
@thielfab can you please have a look.

**Comment by thielfab** [comment]
I just see one `SpectralProfile` in the dropdown list
