### ISSUE TITLE
[SpectralView] GeoJSON library with NaN values not correctly plotted

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#887]
When using this library, which contains a NaN value, the profile is not correctly plotted: 
```
{
    "type": "FeatureCollection",
    "name": "My Library",
    "description": "",
    "features": [
        {
            "type": "Feature", 
            "properties": {
                "name": "profile 1", 
                "profiles": {
                    "x": [1, 2, 3], 
                    "xUnit": "Nanometers", 
                    "y": [10, NaN, 30], 
                    "bbl": [1, 1, 1]}
                    }, 
            "geometry": null}
    ]
}
```

![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/b67b3a6a-2179-4ac5-8a5e-be4b963813db)

**Comment by janzandr** [comment]
Note that the library was written with json.dump, which will write Python nan values as "NaN".

**Comment by jakimowb** [comment]
It's not valid JSON (see #731) 
In general, QGIS expects valid JSON files according to https://datatracker.ietf.org/doc/html/rfc7946

**Comment by janzandr** [comment]
Solution: "NaN" needs to be replaced by "null"

**Comment by jakimowb** [comment]
from https://docs.python.org/3/library/json.html

> 
If allow_nan is false (default: True), then it will be a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) to serialize out of range [float](https://docs.python.org/3/library/functions.html#float) values (nan, inf, -inf) in strict compliance of the JSON specification. If allow_nan is true, their JavaScript equivalents (NaN, Infinity, -Infinity) will be used.

Of course we could somehow handle such kind of JSON, but GDAL or QGIS widgets may still make problems, e.g. if "JSON" is used as field type.

**Comment by janzandr** [comment]
Not sure what you want to say?
Can/Shall we support NaN values inside the SpectralView?

**Comment by janzandr** [comment]
Currently, using "null" is the correct way of doing it, right?
