### ISSUE TITLE
[PyPi Package Info] Latest version not displayed

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#890]
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/cbd4051c-ac2b-4db6-ae90-8cdf25ab0a7b)

**Comment by jakimowb** [comment]
As the screenshot shows, the progress bar is still at 0%. You need to wait until the requested information is collected.

**Comment by jakimowb** [comment]
`pip search` is not available anymore (see https://github.com/pypa/pip/issues/5216)
Using pip, it is possible to get version numbers for installed packages only.
Alternatives to the former `pip search` would be, for example, https://pypi.org/project/pip-search/. But this is not very efficient if you like to crawl the latest version for a larger number of packages.

**Comment by janzandr** [comment]
Ok.
Another question: what is the column "Requires" good for?

**Comment by jakimowb** [comment]
The tooltip will tell you ;-)
![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/5b0d9cd8-087e-4166-8a74-76eb32253a1a)

**Comment by dpoursanidis** [comment]
We face an issue with Pypi window.
We check the packages we wanna install but no button appears for that.
We have the version 3.14.3 in QGIS 3.34.10.

**Comment by janzandr** [comment]
Package installation via the GUI was deactivated due to several issues. Please follow instructions here:
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation.html#install-python-dependencies
