### ISSUE TITLE
RasterReader wavelength fails with FORCE TSI images

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#9]
The RasterReader class fails to return the wavelength units used in FORCE TSI images.

How to reproduce:
```
path_tsi = r'<force TSI image>'
reader = RasterReader(path_tsi)
reader.wavelength(1)
```

Error Traceback:
```
  File "D:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "D:\Repositories\enmap-box\enmapboxprocessing\rasterreader.py", line 483, in wavelength
    wavelength_units = self.wavelengthUnits(bandNo)
  File "D:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "D:\Repositories\enmap-box\enmapboxprocessing\rasterreader.py", line 467, in wavelengthUnits
    return Utils.wavelengthUnitsLongName(units)
  File "D:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "D:\Repositories\enmap-box\enmapboxprocessing\utils.py", line 637, in wavelengthUnitsLongName
    raise ValueError(f'unknown wavelength unit: {units}')
ValueError: unknown wavelength unit: decimal year

```

**Comment by janzandr** [comment]
Hi @jakimowb, 
the RasterReader is not using the hacky approach of storing aquisition time into the wavelength metadata item.
Correct usage is:
```
path_tsi = r'<force TSI image>'
reader = RasterReader(path_tsi)
reader.centerTime(1)
```
I will add the FORCE format.

**Comment by jakimowb** [comment]
test_issue9 fails on all systems that don't know `r'D:\data\software\force\1984-2021_060-319_HL_TSA_LNDLG_NDV_TSI.tif'`
To not break CI workflows local / platform specific tests need to be skipped in case local sources do not exists.
You may check for this using the  @unittest.skiIf decorator. https://docs.python.org/3/library/unittest.html

**Comment by jakimowb** [comment]
> the RasterReader is not using the hacky approach of mixing aquisition time and spectral wavelengths information.

I agree, but nevertheless the "wavelength" key is often used in that way. If it is unable to handle the values stored as "wavelength" it may better return None or NaN and throw a warning, but not crash.

**Comment by janzandr** [comment]
Agreed, returning None and a Warnung is a good ideal.
