### ISSUE TITLE
Add option to set a mask layer in the "Predict classification" tool and in the Advanced Classification workflow

### ISSUE THREAD

**Issue by gthuser** [EnMAP-Box/enmap-box#930]
In the older versions of EnMAP-Box there was an option to set a mask layer from a vector file when using the Predict classification tool. It was very useful but in v3.14.3 it is not available.

**Comment by janzandr** [comment]
Having a mask applied before processing is potentially useful for many other algorithms as well.
However, we decided to not have such a mask parameter in all the algorithms as input.
We see masking as a preprocessing step, similar to spatial subsetting and band subsetting etc.
You can use this algorithm for applying a mask to a raster:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/4c212c8f-920d-4b68-bdee-8340f9478645)
Afterwards, you can use the masked raster layer as input for the "Predict classification" algorithm.

I understand, that this is not as convenient as before.
To make raster masking more convinient, I would propose a shortcut "Apply mask" here:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/b157dc12-510c-43db-a7b0-934a4936e6f0)

**Comment by janzandr** [comment]
Follow-up issue: #942
