### ISSUE TITLE
Regression based unmixing | problem with implementation of LinearSVR

### ISSUE THREAD

**Issue by patrchristen** [EnMAP-Box/enmap-box#967]
Hi,
The implementation of the LinearSVR in the "Regression based unmixing" application outputs the following error:

> Traceback (most recent call last):
> File "C:\Users\pata2\.conda\envs\enmapbox\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
> retval = func(*args, **kwargs)
> File "C:\Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\fitregressoralgorithmbase.py", line 88, in processAlgorithm
> regressor.fit(dump.X, dump.y.ravel())
> File "C:\Users\.conda\envs\enmapbox\lib\site-packages\sklearn\base.py", line 1473, in wrapper
> return fit_method(estimator, *args, **kwargs)
> File "C:\Users\pata2\.conda\envs\enmapbox\lib\site-packages\sklearn\multioutput.py", line 252, in fit
> raise ValueError(
> ValueError: y must have at least two dimensions for multi-output regression but has only one.

The other regressors work fine.

From a first look it seems to be related to the MultiOutputRegressor() function and the way the dataset is structured. 

Here´s the content of the pkl file produced by "Create classification dataset (from categorized spectral library)":

> Shape of X: (588, 174)
> {'categories': [Category(value=1, name='agri', color='#3c1ffc'), Category(value=2, name='bare_soil', color='#cc6bc2'), Category(value=3, name='dec_tree', color='#3c193f'), Category(value=4, name='grassland', color='#305db1'), Category(value=5, name='grey_conif', color='#fd5a2f'), Category(value=6, name='h_conif', color='#86792e'), Category(value=7, name='impervious', color='#ef4ae5'), Category(value=8, name='uh_conif', color='#1c3b67')], 'features': ['Band 1', 'Band 2', 'Band 3', 'Band 4', 'Band 5', 'Band 6', 'Band 7', 'Band 8', 'Band 9', 'Band 10', 'Band 11', 'Band 12', 'Band 13', 'Band 14', 'Band 15', 'Band 16', 'Band 17', 'Band 18', 'Band 19', 'Band 20', 'Band 21', 'Band 22', 'Band 23', 'Band 24', 'Band 25', 'Band 26', 'Band 27', 'Band 28', 'Band 29', 'Band 30', 'Band 31', 'Band 32', 'Band 33', 'Band 34', 'Band 35', 'Band 36', 'Band 37', 'Band 38', 'Band 39', 'Band 40', 'Band 41', 'Band 42', 'Band 43', 'Band 44', 'Band 45', 'Band 46', 'Band 47', 'Band 48', 'Band 49', 'Band 50', 'Band 51', 'Band 52', 'Band 53', 'Band 54', 'Band 55', 'Band 56', 'Band 57', 'Band 58', 'Band 59', 'Band 60', 'Band 61', 'Band 62', 'Band 63', 'Band 64', 'Band 65', 'Band 66', 'Band 67', 'Band 68', 'Band 69', 'Band 70', 'Band 71', 'Band 72', 'Band 73', 'Band 74', 'Band 75', 'Band 76', 'Band 77', 'Band 78', 'Band 79', 'Band 80', 'Band 81', 'Band 82', 'Band 83', 'Band 84', 'Band 85', 'Band 86', 'Band 87', 'Band 88', 'Band 89', 'Band 90', 'Band 91', 'Band 92', 'Band 93', 'Band 94', 'Band 95', 'Band 96', 'Band 97', 'Band 98', 'Band 99', 'Band 100', 'Band 101', 'Band 102', 'Band 103', 'Band 104', 'Band 105', 'Band 106', 'Band 107', 'Band 108', 'Band 109', 'Band 110', 'Band 111', 'Band 112', 'Band 113', 'Band 114', 'Band 115', 'Band 116', 'Band 117', 'Band 118', 'Band 119', 'Band 120', 'Band 121', 'Band 122', 'Band 123', 'Band 124', 'Band 125', 'Band 126', 'Band 127', 'Band 128', 'Band 129', 'Band 130', 'Band 131', 'Band 132', 'Band 133', 'Band 134', 'Band 135', 'Band 136', 'Band 137', 'Band 138', 'Band 139', 'Band 140', 'Band 141', 'Band 142', 'Band 143', 'Band 144', 'Band 145', 'Band 146', 'Band 147', 'Band 148', 'Band 149', 'Band 150', 'Band 151', 'Band 152', 'Band 153', 'Band 154', 'Band 155', 'Band 156', 'Band 157', 'Band 158', 'Band 159', 'Band 160', 'Band 161', 'Band 162', 'Band 163', 'Band 164', 'Band 165', 'Band 166', 'Band 167', 'Band 168', 'Band 169', 'Band 170', 'Band 171', 'Band 172', 'Band 173', 'Band 174'], 'X': array([[0.02175091, 0.02263951, 0.02424603, ..., 0.14647979, 0.14460452,
>         0.        ],
>        [0.02175367, 0.02438243, 0.02554159, ..., 0.15090528, 0.14977567,
>         0.        ],
>        [0.02228417, 0.02363015, 0.02656646, ..., 0.16629072, 0.16589952,
>         0.        ],
>        ...,
>        [0.01980272, 0.01747094, 0.0193088 , ..., 0.04314011, 0.04061959,
>         0.        ],
>        [0.02155756, 0.0202968 , 0.02233505, ..., 0.08566951, 0.08445098,
>         0.        ],
>        [0.01974302, 0.020581  , 0.02212618, ..., 0.08627065, 0.08441443,
>         0.        ]], dtype=float32), 'y': array([[2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [2],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [1],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [3],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [4],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [5],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [6],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [7],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8],
>        [8]]), 'classifier': None}

Best regards,
Patrick

**Comment by janzandr** [comment]
Confirmed

**Comment by janzandr** [comment]
A quick workaround is to remove the **MultiOutputRegressor** part:
![image](https://github.com/user-attachments/assets/360eadb0-88bd-44d4-842b-499d48b42afe)
