### ISSUE TITLE
Create LUT | Error messages when selecting bsq-file within "Create new sensor"

### ISSUE THREAD

**Issue by patrchristen** [EnMAP-Box/enmap-box#972]
Hi,
When I try to select a bsq-file within the "Create new sensor" function within the "Create LUT" application, I receive two error-messages:

1. **KeyError: 'fwhm'** 

> Traceback (most recent call last):
>   File "C:\Users\christen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuvegetationapps\LUT\CreateLUT_GUI.py", line 1102, in 
>     self.gui.mLayer.layerChanged.connect(lambda: self.open_image(mode="imgDropdown"))
>                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\christen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuvegetationapps\LUT\CreateLUT_GUI.py", line 1257, in open_image
>     self.image_read()
>   File "C:\Users\christen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuvegetationapps\LUT\CreateLUT_GUI.py", line 1275, in image_read
>     fwhm = meta['ENVI']['fwhm']
>            ~~~~~~~~~~~~^^^^^^^^
> KeyError: 'fwhm'

Here is the metadata from the header of the file:

> ENVI
> description = {D:/project/PRS_bsq.bsq}
> samples = 1269
> lines = 1233
> bands = 234
> header offset = 0
> file type = ENVI Standard
> data type = 4
> interleave = bsq
> byte order = 0
> map info = {UTM, 1, 1, 345687.5, 5528112.5, 30, 30, 32, North, WGS-84}
> coordinate system string = {PROJCS["WGS_1984_UTM_Zone_32N", GEOGCS["GCS_WGS_1984", DATUM["D_WGS_1984", SPHEROID["WGS_1984", 6378137.0, 298.257223563]], PRIMEM["Greenwich", 0.0], UNIT["Degree", 0.0174532925199433]], PROJECTION["Transverse_Mercator"], PARAMETER["False_Easting", 500000.0], PARAMETER["False_Northing", 0.0], PARAMETER["Central_Meridian", 9.0], PARAMETER["Scale_Factor", 0.9996], PARAMETER["Latitude_Of_Origin", 0.0], UNIT["Meter", 1.0]]}
> band names = {Band 1 (Band 1) (406.993408 Nanometers), Band 2 (Band 2) (415.838989 Nanometers), Band 3 (Band 3) (423.784760 Nanometers), Band 4 (Band 4) (431.334686 Nanometers), Band 5 (Band 5) (438.656891 Nanometers), Band 6 (Band 6) (446.014709 Nanometers), Band 7 (Band 7) (453.389465 Nanometers), Band 8 (Band 8) (460.731750 Nanometers), Band 9 (Band 9) (468.098419 Nanometers), Band 10 (Band 10) (475.318848 Nanometers), Band 11 (Band 11) (482.548157 Nanometers), Band 12 (Band 12) (489.794861 Nanometers), Band 13 (Band 13) (497.058655 Nanometers), Band 14 (Band 14) (504.511719 Nanometers), Band 15 (Band 15) (512.046387 Nanometers), Band 16 (Band 16) (519.543762 Nanometers), Band 17 (Band 17) (527.305298 Nanometers), Band 18 (Band 18) (535.052551 Nanometers), Band 19 (Band 19) (542.885132 Nanometers), Band 20 (Band 20) (550.914612 Nanometers), Band 21 (Band 21) (559.020264 Nanometers), Band 22 (Band 22) (567.206116 Nanometers), Band 23 (Band 23) (575.486816 Nanometers), Band 24 (Band 24) (583.844116 Nanometers), Band 25 (Band 25) (592.338989 Nanometers), Band 26 (Band 26) (601.014404 Nanometers), Band 27 (Band 27) (609.958191 Nanometers), Band 28 (Band 28) (618.719971 Nanometers), Band 29 (Band 29) (627.778442 Nanometers), Band 30 (Band 30) (636.676270 Nanometers), Band 31 (Band 31) (645.963806 Nanometers), Band 32 (Band 32) (655.418762 Nanometers), Band 33 (Band 33) (664.894104 Nanometers), Band 34 (Band 34) (674.464355 Nanometers), Band 35 (Band 35) (684.137268 Nanometers), Band 36 (Band 36) (694.128357 Nanometers), Band 37 (Band 37) (703.737000 Nanometers), Band 38 (Band 38) (713.726868 Nanometers), Band 39 (Band 39) (723.879944 Nanometers), Band 40 (Band 40) (733.955200 Nanometers), Band 41 (Band 41) (744.149536 Nanometers), Band 42 (Band 42) (754.469604 Nanometers), Band 43 (Band 43) (764.856445 Nanometers), Band 44 (Band 44) (775.273499 Nanometers), Band 45 (Band 45) (785.659546 Nanometers), Band 46 (Band 46) (796.127014 Nanometers), Band 47 (Band 47) (806.711060 Nanometers), Band 48 (Band 48) (817.311035 Nanometers), Band 49 (Band 49) (827.919495 Nanometers), Band 50 (Band 50) (838.527222 Nanometers), Band 51 (Band 51) (849.209961 Nanometers), Band 52 (Band 52) (859.973145 Nanometers), Band 53 (Band 53) (870.742554 Nanometers), Band 54 (Band 54) (881.456055 Nanometers), Band 55 (Band 55) (892.080933 Nanometers), Band 56 (Band 56) (902.801636 Nanometers), Band 57 (Band 57) (913.445068 Nanometers), Band 58 (Band 58) (923.950195 Nanometers), Band 59 (Band 59) (934.112061 Nanometers), Band 60 (Band 60) (944.627319 Nanometers), Band 61 (Band 61) (956.271484 Nanometers), Band 62 (Band 62) (967.026672 Nanometers), Band 63 (Band 63) (977.365417 Nanometers), Band 64 (Band 3) (943.357910 Nanometers), Band 65 (Band 4) (951.401428 Nanometers), Band 66 (Band 5) (959.973999 Nanometers), Band 67 (Band 6) (969.844910 Nanometers), Band 68 (Band 7) (979.223999 Nanometers), Band 69 (Band 8) (988.917908 Nanometers), Band 70 (Band 9) (998.908203 Nanometers), Band 71 (Band 10) (1008.644287 Nanometers), Band 72 (Band 11) (1018.535706 Nanometers), Band 73 (Band 12) (1029.343994 Nanometers), Band 74 (Band 13) (1037.987793 Nanometers), Band 75 (Band 14) (1047.675049 Nanometers), Band 76 (Band 15) (1057.573730 Nanometers), Band 77 (Band 16) (1067.794800 Nanometers), Band 78 (Band 17) (1078.216064 Nanometers), Band 79 (Band 18) (1088.760986 Nanometers), Band 80 (Band 19) (1099.277588 Nanometers), Band 81 (Band 20) (1109.889404 Nanometers), Band 82 (Band 21) (1120.675903 Nanometers), Band 83 (Band 22) (1131.304810 Nanometers), Band 84 (Band 23) (1142.070312 Nanometers), Band 85 (Band 24) (1152.650146 Nanometers), Band 86 (Band 25) (1163.676025 Nanometers), Band 87 (Band 26) (1174.714233 Nanometers), Band 88 (Band 27) (1185.588379 Nanometers), Band 89 (Band 28) (1196.339355 Nanometers), Band 90 (Band 29) (1207.273682 Nanometers), Band 91 (Band 30) (1217.863525 Nanometers), Band 92 (Band 31) (1229.185181 Nanometers), Band 93 (Band 32) (1240.214478 Nanometers), Band 94 (Band 33) (1250.979858 Nanometers), Band 95 (Band 34) (1262.532227 Nanometers), Band 96 (Band 35) (1273.496338 Nanometers), Band 97 (Band 36) (1284.487793 Nanometers), Band 98 (Band 37) (1295.421753 Nanometers), Band 99 (Band 38) (1306.218018 Nanometers), Band 100 (Band 39) (1317.256592 Nanometers), Band 101 (Band 40) (1328.299316 Nanometers), Band 102 (Band 41) (1339.129395 Nanometers), Band 103 (Band 42) (1349.787720 Nanometers), Band 104 (Band 43) (1361.053101 Nanometers), Band 105 (Band 44) (1372.911743 Nanometers), Band 106 (Band 45) (1383.279785 Nanometers), Band 107 (Band 46) (1394.754028 Nanometers), Band 108 (Band 47) (1405.626831 Nanometers), Band 109 (Band 48) (1416.537354 Nanometers), Band 110 (Band 49) (1427.374756 Nanometers), Band 111 (Band 50) (1438.465942 Nanometers), Band 112 (Band 51) (1449.188843 Nanometers), Band 113 (Band 52) (1459.315674 Nanometers), Band 114 (Band 53) (1469.930786 Nanometers), Band 115 (Band 54) (1480.842163 Nanometers), Band 116 (Band 55) (1491.429199 Nanometers), Band 117 (Band 56) (1502.023560 Nanometers), Band 118 (Band 57) (1512.633301 Nanometers), Band 119 (Band 58) (1523.222168 Nanometers), Band 120 (Band 59) (1533.776367 Nanometers), Band 121 (Band 60) (1544.226196 Nanometers), Band 122 (Band 61) (1554.816772 Nanometers), Band 123 (Band 62) (1565.368774 Nanometers), Band 124 (Band 63) (1575.627441 Nanometers), Band 125 (Band 64) (1585.859741 Nanometers), Band 126 (Band 65) (1596.245361 Nanometers), Band 127 (Band 66) (1606.491333 Nanometers), Band 128 (Band 67) (1616.833618 Nanometers), Band 129 (Band 68) (1627.020996 Nanometers), Band 130 (Band 69) (1637.091919 Nanometers), Band 131 (Band 70) (1647.231567 Nanometers), Band 132 (Band 71) (1656.932983 Nanometers), Band 133 (Band 72) (1667.185059 Nanometers), Band 134 (Band 73) (1677.319336 Nanometers), Band 135 (Band 74) (1687.426880 Nanometers), Band 136 (Band 75) (1697.294312 Nanometers), Band 137 (Band 76) (1707.094482 Nanometers), Band 138 (Band 77) (1716.858887 Nanometers), Band 139 (Band 78) (1726.651611 Nanometers), Band 140 (Band 79) (1736.488281 Nanometers), Band 141 (Band 80) (1746.219238 Nanometers), Band 142 (Band 81) (1755.833008 Nanometers), Band 143 (Band 82) (1765.512695 Nanometers), Band 144 (Band 83) (1775.117798 Nanometers), Band 145 (Band 84) (1784.717285 Nanometers), Band 146 (Band 85) (1793.953125 Nanometers), Band 147 (Band 86) (1803.590210 Nanometers), Band 148 (Band 87) (1813.051392 Nanometers), Band 149 (Band 88) (1822.441284 Nanometers), Band 150 (Band 89) (1832.027222 Nanometers), Band 151 (Band 90) (1841.325562 Nanometers), Band 152 (Band 91) (1850.554321 Nanometers), Band 153 (Band 92) (1859.558716 Nanometers), Band 154 (Band 93) (1868.173218 Nanometers), Band 155 (Band 94) (1878.742554 Nanometers), Band 156 (Band 95) (1887.081055 Nanometers), Band 157 (Band 96) (1896.091309 Nanometers), Band 158 (Band 97) (1904.934692 Nanometers), Band 159 (Band 98) (1914.301514 Nanometers), Band 160 (Band 99) (1923.385742 Nanometers), Band 161 (Band 100) (1932.259888 Nanometers), Band 162 (Band 101) (1941.110718 Nanometers), Band 163 (Band 102) (1949.900757 Nanometers), Band 164 (Band 103) (1958.624390 Nanometers), Band 165 (Band 104) (1967.341797 Nanometers), Band 166 (Band 105) (1976.012939 Nanometers), Band 167 (Band 106) (1984.853027 Nanometers), Band 168 (Band 107) (1993.548218 Nanometers), Band 169 (Band 108) (2002.110596 Nanometers), Band 170 (Band 109) (2010.661377 Nanometers), Band 171 (Band 110) (2019.321411 Nanometers), Band 172 (Band 111) (2027.726685 Nanometers), Band 173 (Band 112) (2036.260742 Nanometers), Band 174 (Band 113) (2044.680908 Nanometers), Band 175 (Band 114) (2053.007812 Nanometers), Band 176 (Band 115) (2061.378662 Nanometers), Band 177 (Band 116) (2069.795654 Nanometers), Band 178 (Band 117) (2077.991455 Nanometers), Band 179 (Band 118) (2086.382324 Nanometers), Band 180 (Band 119) (2094.625244 Nanometers), Band 181 (Band 120) (2102.821289 Nanometers), Band 182 (Band 121) (2111.039062 Nanometers), Band 183 (Band 122) (2119.231445 Nanometers), Band 184 (Band 123) (2127.337158 Nanometers), Band 185 (Band 124) (2135.510254 Nanometers), Band 186 (Band 125) (2143.465576 Nanometers), Band 187 (Band 126) (2151.386230 Nanometers), Band 188 (Band 127) (2159.563965 Nanometers), Band 189 (Band 128) (2167.484863 Nanometers), Band 190 (Band 129) (2175.344238 Nanometers), Band 191 (Band 130) (2183.420166 Nanometers), Band 192 (Band 131) (2191.100342 Nanometers), Band 193 (Band 132) (2199.135254 Nanometers), Band 194 (Band 133) (2206.843018 Nanometers), Band 195 (Band 134) (2214.625000 Nanometers), Band 196 (Band 135) (2222.426270 Nanometers), Band 197 (Band 136) (2230.007568 Nanometers), Band 198 (Band 137) (2237.904053 Nanometers), Band 199 (Band 138) (2245.448486 Nanometers), Band 200 (Band 139) (2253.110352 Nanometers), Band 201 (Band 140) (2260.866455 Nanometers), Band 202 (Band 141) (2268.288330 Nanometers), Band 203 (Band 142) (2276.053711 Nanometers), Band 204 (Band 143) (2283.493408 Nanometers), Band 205 (Band 144) (2290.826660 Nanometers), Band 206 (Band 145) (2298.609375 Nanometers), Band 207 (Band 146) (2305.722656 Nanometers), Band 208 (Band 147) (2313.200684 Nanometers), Band 209 (Band 148) (2320.895508 Nanometers), Band 210 (Band 149) (2327.824219 Nanometers), Band 211 (Band 150) (2335.526367 Nanometers), Band 212 (Band 151) (2342.822754 Nanometers), Band 213 (Band 152) (2349.791504 Nanometers), Band 214 (Band 153) (2357.293701 Nanometers), Band 215 (Band 154) (2364.594482 Nanometers), Band 216 (Band 155) (2371.552246 Nanometers), Band 217 (Band 156) (2378.770996 Nanometers), Band 218 (Band 157) (2386.061768 Nanometers), Band 219 (Band 158) (2393.038818 Nanometers), Band 220 (Band 159) (2400.035889 Nanometers), Band 221 (Band 160) (2407.604492 Nanometers), Band 222 (Band 161) (2414.356689 Nanometers), Band 223 (Band 162) (2421.237305 Nanometers), Band 224 (Band 163) (2428.667725 Nanometers), Band 225 (Band 164) (2435.544189 Nanometers), Band 226 (Band 165) (2442.403076 Nanometers), Band 227 (Band 166) (2449.142334 Nanometers), Band 228 (Band 167) (2456.585693 Nanometers), Band 229 (Band 168) (2463.030273 Nanometers), Band 230 (Band 169) (2469.627197 Nanometers), Band 231 (Band 170) (2477.054932 Nanometers), Band 232 (Band 171) (2483.792969 Nanometers), Band 233 (Band 172) (2490.219238 Nanometers), Band 234 (Band 173) (2497.115479 Nanometers)}
> data ignore value = 0.0
> bbl = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}
> wavelength units = Nanometers
> wavelength = {406.99341, 415.83899, 423.78476000000006, 431.33469, 438.65689, 446.01471, 453.38946000000004, 460.73175, 468.09842, 475.31885, 482.54816, 489.79486, 497.05865, 504.51171999999997, 512.04639, 519.54376, 527.3053, 535.05255, 542.88513, 550.91461, 559.02026, 567.20612, 575.48682, 583.84412, 592.33899, 601.0144, 609.95819, 618.71997, 627.77844, 636.67627, 645.9638100000001, 655.41876, 664.8941000000001, 674.46435, 684.13727, 694.1283600000002, 703.737, 713.72687, 723.87994, 733.9552, 744.14954, 754.4696000000001, 764.85645, 775.2735, 785.65955, 796.12701, 806.7110600000001, 817.31103, 827.91949, 838.5272200000002, 849.20996, 859.97315, 870.7425500000002, 881.45605, 892.08093, 902.80164, 913.44507, 923.9502000000001, 934.11206, 944.62732, 956.2714800000001, 967.02667, 977.3654200000001, 943.3579100000001, 951.40143, 959.9740000000002, 969.84491, 979.224, 988.9179100000001, 998.9082000000001, 1008.6442899999998, 1018.5357100000001, 1029.34399, 1037.98779, 1047.67505, 1057.57373, 1067.7948, 1078.21606, 1088.76099, 1099.27759, 1109.8894, 1120.6759, 1131.30481, 1142.07031, 1152.65015, 1163.67602, 1174.71423, 1185.58838, 1196.3393600000002, 1207.2736800000002, 1217.86352, 1229.18518, 1240.21448, 1250.97986, 1262.5322300000003, 1273.49634, 1284.4877900000001, 1295.42175, 1306.21802, 1317.25659, 1328.29932, 1339.12939, 1349.78772, 1361.0531, 1372.91174, 1383.27978, 1394.75403, 1405.62683, 1416.53735, 1427.37476, 1438.4659400000003, 1449.1888400000003, 1459.31567, 1469.93079, 1480.84216, 1491.4292, 1502.02356, 1512.6333, 1523.22217, 1533.77637, 1544.2262, 1554.81677, 1565.36877, 1575.6274400000002, 1585.85974, 1596.24536, 1606.49133, 1616.83362, 1627.021, 1637.09192, 1647.23157, 1656.93298, 1667.18506, 1677.31934, 1687.42688, 1697.29431, 1707.09448, 1716.85889, 1726.65161, 1736.48828, 1746.21924, 1755.83301, 1765.51269, 1775.1178, 1784.71728, 1793.95312, 1803.59021, 1813.05139, 1822.44128, 1832.0272200000002, 1841.32556, 1850.5543200000002, 1859.5587200000002, 1868.17322, 1878.74255, 1887.08106, 1896.09131, 1904.93469, 1914.30151, 1923.3857400000002, 1932.25989, 1941.11072, 1949.90076, 1958.62439, 1967.3418, 1976.01294, 1984.85303, 1993.54822, 2002.1106, 2010.6613800000002, 2019.3214099999998, 2027.7266900000002, 2036.26074, 2044.6809100000003, 2053.00781, 2061.37866, 2069.79565, 2077.99145, 2086.38232, 2094.62524, 2102.82129, 2111.03906, 2119.23144, 2127.33716, 2135.51025, 2143.46558, 2151.38623, 2159.56396, 2167.48486, 2175.34424, 2183.42017, 2191.1003400000004, 2199.13525, 2206.84302, 2214.625, 2222.42627, 2230.00757, 2237.90405, 2245.44849, 2253.11035, 2260.86645, 2268.28833, 2276.05371, 2283.49341, 2290.82666, 2298.60938, 2305.72266, 2313.20068, 2320.89551, 2327.82422, 2335.52637, 2342.82275, 2349.7915, 2357.2937, 2364.59448, 2371.55225, 2378.7710000000006, 2386.06177, 2393.03882, 2400.03589, 2407.60449, 2414.35669, 2421.23731, 2428.66772, 2435.5441900000005, 2442.40308, 2449.1423300000006, 2456.58569, 2463.03027, 2469.6272000000004, 2477.05493, 2483.79297, 2490.21924, 2497.1154800000004}
> fwhm = {11.35225, 10.37719, 9.75085, 9.33258, 9.22605, 9.19563, 9.12398, 9.05917, 8.920170000000002, 8.91463, 8.90811, 9.00745, 9.20635, 9.292700000000002, 9.36691, 9.50707, 9.64145, 9.66956, 9.79513, 10.01753, 10.0598, 10.17392, 10.31268, 10.39586, 10.55413, 10.82666, 10.92411, 11.07151, 11.219970000000002, 11.14275, 11.54829, 11.633200000000002, 11.71825, 11.83851, 11.979170000000002, 12.03604, 11.98218, 12.48248, 12.3492, 12.419, 12.56453, 12.6277, 12.80503, 12.74426, 12.76413, 12.8545, 12.94817, 12.95626, 12.98768, 13.00886, 13.088380000000003, 13.145900000000001, 13.17149, 13.04319, 13.10606, 13.11041, 13.06629, 12.88077, 12.75405, 13.2776, 13.46378, 12.94441, 12.9128, 10.94131, 11.01296, 12.20068, 12.150510000000002, 12.13259, 12.28469, 12.67056, 12.45165, 12.97453, 12.95649, 13.562420000000001, 13.631410000000002, 13.820860000000001, 14.04518, 14.16227, 14.28531, 14.23894, 14.60808, 14.18617, 14.544170000000001, 14.33643, 14.47423, 14.86172, 14.45989, 14.564520000000002, 14.46939, 14.74439, 14.60077, 14.88926, 14.525330000000002, 14.98299, 15.11242, 14.74775, 14.707240000000002, 14.62443, 14.654750000000002, 14.73632, 14.81003, 14.64971, 14.76456, 15.28233, 14.68959, 15.1555, 14.52482, 14.59148, 14.51218, 14.24291, 14.87913, 13.97905, 13.88232, 14.44627, 14.35108, 14.191100000000002, 14.32816, 14.153310000000001, 14.08894, 14.10293, 13.93796, 14.14927, 13.99827, 13.81272, 13.9294, 13.90129, 13.76013, 14.02094, 13.6674, 13.57168, 13.39514, 12.85818, 13.46423, 12.99487, 13.04663, 13.22678, 13.25414, 13.02038, 12.810990000000002, 12.83528, 12.97547, 13.07779, 12.71341, 12.47488, 12.59507, 12.72824, 12.548140000000002, 12.37174, 13.079380000000002, 12.48864, 12.584, 12.62173, 12.361820000000002, 11.46573, 12.567370000000002, 11.77403, 11.63578, 12.72553, 11.89709, 12.18463, 11.81017, 11.95356, 11.72708, 11.54942, 11.735330000000001, 11.5738, 11.81588, 11.40911, 11.53911, 11.38756, 11.43358, 11.25816, 11.42366, 11.12836, 11.17084, 11.09842, 11.26351, 11.0925, 11.20486, 11.01622, 11.008940000000003, 10.97452, 10.96091, 10.83949, 10.90404, 10.71089, 10.72788, 10.97973, 10.40529, 10.81814, 10.42951, 10.53476, 10.70757, 10.25385, 10.56897, 10.31996, 10.48997, 10.47026, 10.24898, 10.35342, 10.39724, 10.10566, 10.39185, 9.95032, 10.22006, 10.14063, 9.81789, 10.38666, 9.86135, 9.87342, 10.23499, 9.7339, 9.74175, 10.13382, 9.64241, 9.70783, 9.82816, 9.87084, 9.44856, 9.84293, 9.833660000000002, 9.11424, 9.90752, 9.63344, 9.60992, 8.92421, 9.60746, 9.56854, 9.059480000000002, 9.32855, 9.81114, 9.12272, 9.21801, 9.729}

2. **AttributeError: 'SensorEditor' object has no attribute 'x'**

> Traceback (most recent call last):
>   File "C:\Users\christen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuvegetationapps\LUT\CreateLUT_GUI.py", line 1101, in 
>     self.gui.cmdInputImage.clicked.connect(lambda: self.open_image(mode="imgSelect"))
>                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\christen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuvegetationapps\LUT\CreateLUT_GUI.py", line 1268, in open_image
>     self.check_flags()
>   File "C:\Users\christen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuvegetationapps\LUT\CreateLUT_GUI.py", line 1382, in check_flags
>     text = "Create Generic SRF from Imagery OK: " + str(len(self.x[:, 0])) + " Bands."
>                                                             ~~~~~~^^^^^^
> AttributeError: 'SensorEditor' object has no attribute 'x'

**Comment by janzandr** [comment]
@steffi1296 can you please have a look at this.

**Comment by steffi1296** [comment]
Thank you for reporting the issue. It has been fixed and released in version 3.15.2. If you are still using version 3.15.1, please update the EnMAP-Box 3 plugin, and it should resolve the problem
